### ISSUE TITLE
Setting Pane location within a DockPanel

### ISSUE THREAD

**Issue by louwill** [dockpanelsuite/dockpanelsuite#135]
I've been playing with the 3.0 dev builds and really like the VS2012 theme.  One question I had was whether it's possible to set the pane explicit location of a tab within a DockPanel AutoHideStrip.  For example, in the attached example I would like the "Trace Console" DockContent tab to display on the right side of the AutoHideStrip.

Thanks!
![question](https://f.cloud.github.com/assets/1969592/618481/76b0654c-ceb5-11e2-964b-99ac2a4de2a3.png)

**Comment by lextm** [comment]
After implementing VS2012/2013 recently, I can conclude that to achieve what you wanted, the only way is to write your own VS2012AutoHideStrip and change how it renders itself.
