### ISSUE TITLE
Main window pushed to background when docking happens

### ISSUE THREAD

**Issue by ghost** [dockpanelsuite/dockpanelsuite#155]
On windows 8.  Docking a component occasionally causes the main window to lose focus and be pushed to the background (as If I'd pressed ALT-TAB)

Steps to reproduce:
1 Build and launch latest DockSample
2 Show Task List and drag into undocked position
3 Close and relaunch DockSample
4 Drag Task List into docked position

**Comment by lextm** [comment]
We can minimize the impact by adding a check,
```
var parentChanged = value != Form.Parent;
Form.Parent = value;
if (parentChanged)
{
    Form.Focus();
}
```
I will add some mechanism to include experimental patches like this one, so that later we can merge patches like this one and ship them to users for crowd testing. Of course, experimental patches will be enabled only if the users choose to do so.
