### ISSUE TITLE
Exception 0xC000041D on application exit

### ISSUE THREAD

**Issue by Fadi-git** [dockpanelsuite/dockpanelsuite#157]
This exception raises under these special circumstances:
- Native debugging is enabled.
- System.Diagnostics.StackTrace is used.

So, it is not a big deal. but it may hiding something bigger.

After investigation I found that calling SetWindowsHookEx (in LocalWindowsHook.Install) without calling UnhookWindowsHookEx (in LocalWindowsHook.Uninstall) can cause this exception.

Ver 3.0 relies on GC finalizer to call "Uninstall" method, and this can be solved by calling it directly from FocusManagerImpl.Dispose.

```
private class FocusManagerImpl : Component, ....
{
       .
       .
       .
        protected override void Dispose(bool disposing)
        {
            if (!m_disposed && disposing)
            {
                if (!Win32Helper.IsRunningOnMono)
                {
                    sm_localWindowsHook.HookInvoked -= m_hookEventHandler;
                }
                sm_localWindowsHook.Dispose(); //FIX________

                m_disposed = true;
            }

            base.Dispose(disposing);
        }
}
```

If the fix is acceptable, kindly include it in the next version.
Thanks for such great package, it gave my application a professional look and functionality

**Comment by Engineerumair** [comment]
Hi I am facing same issue could you please give me confirmation about resolution of this issue?

Was it resolvable or any workaround
