### ISSUE TITLE
Add Built-In Support For Maximizable Float Windows

### ISSUE THREAD

**Issue by roken** [dockpanelsuite/dockpanelsuite#17]
A common question in the forums is "how do I make my float windows maximizable."

Although this isn't difficult to extend on your own, the support for this should really just be built in to make it easier to achieve.

**Comment by Media-Hub** [comment]
Just altered some code in FloatWindow.cs 


`        internal void RefreshChanges()
        {
            if (IsDisposed)
                return;

            if (VisibleNestedPanes.Count == 0)
            {
                ControlBox = true;
                return;
            }

            for (int i=VisibleNestedPanes.Count - 1; i>=0; i--)
            {
                DockContentCollection contents = VisibleNestedPanes[i].Contents;
                for (int j=contents.Count - 1; j>=0; j--)
                {
                    IDockContent content = contents[j];
                    if (content.DockHandler.DockState != DockState.Float)
                        continue;
                    **if (content.DockHandler.DockState == DockState.Float)
                    {
                        this.FindForm().FormBorderStyle = FormBorderStyle.Sizable; 
                    }
                    if (this.FindForm().WindowState == FormWindowState.Maximized)
                    {
                        content.DockHandler.DockState = DockState.Document;
                    }**

                    if (content.DockHandler.CloseButton && content.DockHandler.CloseButtonVisible)
                    {
                        ControlBox = true;
                        return;
                    }
                }
            }
            //Only if there is a ControlBox do we turn it off
            //old code caused a flash of the window.
            if (ControlBox)
                ControlBox = false;
        }`

**Comment by Media-Hub** [comment]
You can change Dock Style as per your requirement 
change 'DockState.Document' to your required dock style
