### ISSUE TITLE
dockpanelsuite does not show in toolbox in visual studio 2013

### ISSUE THREAD

**Issue by zl0523** [dockpanelsuite/dockpanelsuite#184]
I am not sure whether any other person has this problem. 
I tried to install it on my visual studio 2013 ultimate through Nuget. The command in package manager console as follows:   install-package DockPanelSuite -Pre

It shows the DockPanelSuite 3.0.0-alpha7 is installed successfully. But I can not see it in Toolbox. 

Do it has version limitation?

Thanks,
Jack

**Comment by lextm** [comment]
The extra installer is kind of a burden to maintain. So please follow Ryan's tip on Dec 24, 2013 to manually add DPS to Toolbox.
