### ISSUE TITLE
Create New Default Skin

### ISSUE THREAD

**Issue by roken** [dockpanelsuite/dockpanelsuite#19]
Rather than modify the existing skin we should create an additional skin that takes on the contributed changes (SharpDevelop and John Barton both have skin changes).

Additonally, we should move the skin files around so they are better organized, and add a Skin designer property to the DockPanel that will allow selection of the built-in skin.

**Comment by lextm** [comment]
I think after #306 and #315 we can now close this item.

My personal preference is that we leave VS 2005 theme the default, and its elements stored in DPS main assembly, while all other themes (VS 2003, VS 2012 light, and VS 2013 blue) in separate assemblies. Then new themes can be developed completely out of band and distributed via NuGet as individual packages.

@roken what's your comment?

**Comment by lextm** [comment]
After several rounds of refactoring, now the VS2012 themes are much more mature than its initial state. We now officially support

- Visual Studio 2003
- Visual Studio 2005
- Visual Studio 2012 Light
- Visual Studio 2012 Dark
- Visual Studio 2012 Blue
- Visual Studio 2013 Blue

Though there are still a few minor issues with the VS2012/2013 themes, they can be used in many scenarios to replace the default VS2005 theme.

As a result, close this item now.
