### ISSUE TITLE
How to programmatically make the active tab?

### ISSUE THREAD

**Issue by ghost** [dockpanelsuite/dockpanelsuite#204]
How to make when  click the mouse on the project tree, tab shapes changed and became active form??
![guibuilder](https://cloud.githubusercontent.com/assets/7125662/2577951/e53ddabe-b986-11e3-90d7-129eae729426.png)

**Comment by WhitneyOnTheWeb** [comment]
I needed the ability to check which document was active, and set that document to active again after changing some UI elements that automatically reset the active tab, so I used some pieces from here to return the name of the active document:

`public string GetActive()
        { //Verify if forms that dock in main window are already open
            foreach (DockContent form in dockMain.Contents)
            {
                if (form.DockHandler.Pane.ActiveContent.DockHandler.Form.Name.ToString() == form.Name.ToString())
                {
                    string formName = form.Name.ToString();
                    return formName;
                }
            }
            return null;
        }`
And then in some other method you will call:

`string activeForm = GetActive();`

**Comment by db300** [comment]
my demo as following:

    private void SwitchDockpanelDocument(int tag)
    {
        if (tag == 0) return;
    
        var documentList = dockPanel1.Documents.ToList();
        var index = documentList.IndexOf(dockPanel1.ActiveDocument);
        System.Diagnostics.Debug.WriteLine($"current window index: {index}");
        var nextIndex = -1;
        if (tag > 0)
        {
            System.Diagnostics.Debug.WriteLine("switch to next window");
            nextIndex = (index + 1) % dockPanel1.DocumentsCount;
        }
        else if (tag < 0)
        {
            System.Diagnostics.Debug.WriteLine("switch to previous window");
            nextIndex = (index - 1 + dockPanel1.DocumentsCount) % dockPanel1.DocumentsCount;
        }
        System.Diagnostics.Debug.WriteLine($"next window index: {nextIndex}");
        if (nextIndex == index) return;
        var document = documentList[nextIndex];
        ((DockContent)document).Activate();
    }
