### ISSUE TITLE
Docking between multiple windows

### ISSUE THREAD

**Issue by CoryGH** [dockpanelsuite/dockpanelsuite#208]
The demo application contains the menu option Window --> New Window to create a new dock container window, however dockable windows cannot be dragged between the two.  This would be a huge asset to have for multiple-monitor displays and I'm curious if this is already possible via some settings unknown to me or if there is a plan to include the ability to transfer dockable content from one containing window to another in the future?

**Comment by wackyteseo** [comment]
Hi rocken , i have the same need , can you explain me how i have to do ?

**Comment by lextm** [comment]
Close it now. Anyone who would like to work on it can send a pull request.
