### ISSUE TITLE
ArgumentOutOfRangeException when removing a tab from a group with a document tab

### ISSUE THREAD

**Issue by DavidBasnett** [dockpanelsuite/dockpanelsuite#209]
In an application with a document tab and some other docking content.
Drag another window into the 'centre' square of the document tab to create a group with the two of them, and then drag it out again, and an exception results. 
The content of the document tab is not drawn, and the 'strip' at the top of the document tab is drawn as red crosses.
NOTE - this was found during testing on a slow VM, but couldn't be recreated from the debugger on a faster development machine.

Screenshot of the failed state and exception is attached

![docking error](https://cloud.githubusercontent.com/assets/6471598/2839673/3c3dfacc-d04a-11e3-8593-7fa1a9080b2d.jpg)

**Comment by yevgrig** [comment]
We may have stopped the issue from happening just observing symptoms without fully understanding it.

At some point in the past, we started running a custom FloatWindow for the Extender.FloatWindowFactory that disables floating window's close button

```c#
        protected override CreateParams CreateParams
        {
            get
            {
                CreateParams myCp = base.CreateParams;
                myCp.ClassStyle = myCp.ClassStyle | CP_NOCLOSE_BUTTON;
                return myCp;
            }
        }
```

We believe that after the change we started having the "Red X" problem (referenced here as well) after content windows are hidden as described issue #310
The "Red X" is consistently present and can be easily recreated.

After disabling the docked content close button as well in DockContent's subclasses' constructors

```c#
this.CloseButtonVisible = false;
```

the problem in #310 appears to have stopped for our end users. The problem in #310 could not be recreated by development.

**Comment by lextm** [comment]
In some rare cases, the index parameter can be -1 due to some unknown reasons. I modified VS2012DockPaneStrip.EnsureDocumentTabVisible to check against -1. So maybe we should do the same for VS2005DockPaneStrip.

**Comment by lextm** [comment]
Should cherry pick https://github.com/DavidBasnett/dockpanelsuite/commit/2d4758ef9dae62d9777390346b9eb25e62a87d76

**Comment by yevgrig** [comment]
We are still in 2005 skin. Stopped the issue as described, porting fixes to that is very much appreciated.

**Comment by lextm** [comment]
Finished.

**Comment by yevgrig** [comment]
thank you and thank you for working on 2.11.
