### ISSUE TITLE
Dockpanelsuite does not work with Mono

### ISSUE THREAD

**Issue by thomask77** [dockpanelsuite/dockpanelsuite#223]
Hi!

I just tried to use DockPanelSuite under XUbuntu 14.04. 

    $ mono --version
    Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1)

Neither the master nor the development_3.0 branch works.
The development branch also has some build issues under monodevelop.

The DockSample program does not work at all - it's not possible to move the dock windows. Resizing does not work either and leaves behind a translucent rectangle. Also, it crashes all the time..

It's not worthwhile to give a detailed bug report, because the problems are so obvious.

Is this supposed to run under mono at all?

**Comment by thomask77** [comment]
Why has this been closed?
Mono support should be an important goal for DockPanelSuite. 
Even more so since Microsoft has released their framework under an open-source license.

**Comment by lextm** [comment]
Closing it means we won't be able to do much in the near future. Mono's WinForms is not what the current maintainers are able to support, while Microsoft's WinForms is far from being released as open source and cross platform.
