### ISSUE TITLE
Invalid Content: ActiveContent must be one of the visible contents

### ISSUE THREAD

**Issue by Nessi2410** [dockpanelsuite/dockpanelsuite#226]
Hello,.

i m using dockpanel suite.
i am getting "Invalid Content: ActiveContent must be one of the visible contents, or null if there is no visible content"
exception on 

 form.Show(DockPanelMain, DockState.Float);

please help me whats wrong here.

Thanks

**Comment by zsohu** [comment]
Hi,

I have the same issue.

VB.Net code:

        Dim NewMDIChild As New frmDBSel()
        NewMDIChild.MdiParent = Me
        NewMDIChild.DockAreas = WeifenLuo.WinFormsUI.Docking.DockAreas.DockLeft
        NewMDIChild.ShowHint = WeifenLuo.WinFormsUI.Docking.DockState.DockLeft
        NewMDIChild.Show(DockPanel1)
        NewMDIChild.Activate()

If I comment out this: NewMDIChild.MdiParent = Me everything is alright. But when it's uncommented I got the same error message when I try to open a new form.

If I just simply open a child form with a code like this:

        Dim NewMDIChild As New frmDBSel()
        NewMDIChild.MdiParent = Me
        NewMDIChild.Show(DockPanel1)

Everything is working fine.

I found this thread about this error: http://sourceforge.net/p/dockpanelsuite/discussion/402316/thread/39dbe63b

I'm using DockPanel Suite v2.9.0.0 from NuGet.

**Comment by ExperiaConsulting** [comment]
Hello everyone ; 

You can only define the childform Dockstyle  like this and it works .

 '                                                           formchild.Mdiparent=Me '  
 formchild.Dock = DockStyle.Fill
     formchild.Show(DockPanel1)   


NB: do not link the form child to the MDIparent

**Comment by CodeSurfing145** [comment]
Error seems to occur on my project 😢 

Exception pops up here
![image](https://user-images.githubusercontent.com/6624832/35806891-58540a1a-0a81-11e8-9ea6-7d8413dac672.png)

And I am assigning MdiParent in the constructor here
![image](https://user-images.githubusercontent.com/6624832/35806899-621da6a0-0a81-11e8-9c00-589a80d234d2.png)

I am running v3.0.4 of DockPanelSuite with .NET 4.5.2
![image](https://user-images.githubusercontent.com/6624832/35806907-69437310-0a81-11e8-89f6-cbdd08b2ba9a.png)

Any ideas how to fix this?

**Comment by lextm** [comment]
@CodeSurfing145 Can you provide a complete sample? Merely the information above won't help me reproduce the issue.
