### ISSUE TITLE
restore form Programatically.

### ISSUE THREAD

**Issue by Nessi2410** [dockpanelsuite/dockpanelsuite#249]
Hello,

I want to restore the form programatically when its minmized. Using 
Restore function of windows but its not applying on the DockContent.

**Comment by lextm** [comment]
Idon't think that `dockPanel.Handle` is valid for your PInvoke call. That Win32 function expects a window handle.

**Comment by TsudaKageyu** [comment]
Excuse me for cutting in.
MSDN Library clearly describes that ```Control.Handle``` returns ```HWND``` and I usually pass it to native Win32 functions.
http://msdn.microsoft.com/en-us/library/system.windows.forms.control.handle%28v=vs.110%29.aspx

**Comment by roken** [comment]
Yes, but the handle of the DockPanel is not the handle of the form that is desired to be shown.  It isnt necessary to make a native call here; given a dockcontent you can find the parent form (which will be either the form housing the dockpanel when the content is docked, or the floatwindow if the content is floating). Once you have the form you can minimize/restore said form directly.

**Comment by Nessi2410** [comment]
Ok.. But can u tel me how can i Maximize a floating minimize window Programatically?
