### ISSUE TITLE
Need VS2010, VS2012-13 Blue Theme

### ISSUE THREAD

**Issue by astrohart** [dockpanelsuite/dockpanelsuite#260]
Hi-

@roken Want to ask about how can we add the "Blue" theme from VS2010, VS2012/13 to the project as a skin.  And part of this is having to do with, how do we change the tab shape.  

I was curious to know if there was a means to skin DockPanel suite with the “Blue Theme” from VS2010 – also, to alter the shapes of the document tabs such as are implemented in VS2010:

![pic1](https://cloud.githubusercontent.com/assets/8261875/5049744/e5d2602c-6bdc-11e4-939d-9199fb30a802.png)

And also, to do a version of the Blue Theme but for the VS2012-like look:

![pic2](https://cloud.githubusercontent.com/assets/8261875/5049760/ff44a61e-6bdc-11e4-9cb7-c12e6883ec08.png)

When I do a sample program with DockPanel suite, I see the tabs have an “angled” edge to them, and I don’t know how to get them to be straight such as in VS:

![pic3](https://cloud.githubusercontent.com/assets/8261875/5049766/0cb6acac-6bdd-11e4-89ef-1ad519989c18.png)

@roken Kudos to you for maintaining the DockPanel suite, and I want to thank you in advance for mentioning any tips/hints as to where I can find out how to implement the VS2010 color tables and tab shapes with my DockPanel-enabled apps.

**Comment by thijse** [comment]
I've submitted a Pull request for some code that implements the VS Blue style. 

Somewhat of-topic: While DPS is relatively old (and perhaps superseded by WPF-based docking implementations), I find myself going back to Winforms whenever I can because of it's simplicity and Mono compatibility. If am very happy that you are keeping this project alive!

**Comment by lextm** [comment]
@thijse The Mono support is "best effort" in fact. We could hardly resolve difficult issues, as the debugging is too complex to carry out (like #273).

**Comment by lextm** [comment]
#306 has added a rough blue theme (following VS 2013). #316 is still open for future contribution to finish this theme.

Close this item now.
