### ISSUE TITLE
Merge 3.0 Branch to Master

### ISSUE THREAD

**Issue by roken** [dockpanelsuite/dockpanelsuite#264]
The 3.0 dev branch has really gotten away, and it is long overdue to be pulled into master.

This issue is a tracking task for discussion and analysis of how painful the merge will be.

**Comment by roken** [comment]
I haven't found any issues with the merge.  I'd vote we go ahead and promote this to nuget as the stable 3.0 release.

**Comment by lextm** [comment]
@roken Do you want to skip 2.10 release?
