### ISSUE TITLE
How to dock panels side by side instead of in tabs

### ISSUE THREAD

**Issue by tetsuo81** [dockpanelsuite/dockpanelsuite#267]
Good morning, I'v attached two images.

I've no problem with the 'number one case', this is my code:
dmcDownloadMonitor.DockState = DockState.DockBottom; (Red area)
amcActivateModsMonitor.DockState = DockState.DockRight; (blu area)

How to recreate the 'number two case'? If I write:
dmcDownloadMonitor.DockState = DockState.DockBottom; (Red area)
amcActivateModsMonitor.DockState = DockState.DockBottom; (blu area)

both sections are at the bottom, but not splitted half and half.
Thanks for your time.

Luca

![one](https://cloud.githubusercontent.com/assets/10205329/5450046/03512fde-8500-11e4-830e-563c3a739ccb.jpg)

![two](https://cloud.githubusercontent.com/assets/10205329/5450050/1c3559f8-8500-11e4-9d53-fc4ee6159aa0.jpg)

**Comment by ErrolErrolson** [comment]
I'm having the same issue as tetsuo81.  If I set the DockState of two DockContent forms to the same value they simply tab instead of sitting next to each other.  I've tested on 2.9.0 and the 3.0.0 alpha 8.  
Is there some additional code required to avoid the tabbing?

**Comment by lextm** [comment]
For number 2 case, the reason behind tabbing is because there is by default only a single bottom pane. So all panels with bottom docking state are inserted into this pane and folded in tabs.

To get the side by side (split) effect, you need to force create nested panes. That requires you to call a few `DockContent.Show` overloading methods, which accept `DockPane` as the first parameter.

You can find such calls in `menuItemLayoutByCode_Click` method,

https://github.com/dockpanelsuite/dockpanelsuite/blob/master/DockSample/MainForm.cs

The sample uses such tricks to show panels in VS style.

**Comment by ErrolErrolson** [comment]
Many thanks and apologies for not looking harder.  I'd played with the sample a little but hadn't tried that menu item.

This is the code I ended up using:

```c#
// widgets inherit from DockContent
var rightContainer = new DockContent();
var transform = new widgetTransform();
var structure = new widgetStructure();

rightContainer.Show(dockPanel, DockState.DockRight);
transform.Show(rightContainer.Pane, DockAlignment.Top, 0.5);
structure.Show(rightContainer.Pane, DockAlignment.Bottom, 1.0);
```

Obviously my panel is on the right and the sub panels are arrayed top and bottom.  It seems the proportion parameter is "proportion of available space" not "proportion of total space"?

**Comment by lextm** [comment]
I just tried and could reproduce what you meant by "proportion of available space". Nope. You misunderstood the behavior.

Note that when `transform.Show(rightContainer.Pane, DockAlignment.Top, 0.5);` is called, DPS smartly creates extra panes to achieve the effect you want (`rightContainer` and `transform` then each take half of the original right pane, and each in fact leaves in a smaller pane.

Thus when `structure.Show(rightContainer.Pane, DockAlignment.Bottom, 1.0);` is called, `rightContainer.Pane` is no longer the whole right pane, but the small pane for `rightContainer`. Thus, `structure` completely hides `rightContainer` afterward.

You can change the last line to `m_toolbox.Show(m_propertyWindow.Pane, DockAlignment.Bottom, 0.5);`, and then guess/confirm what can be the final layout.
