### ISSUE TITLE
Not working GotFocus event by clicking on tab?

### ISSUE THREAD

**Issue by Progress1** [dockpanelsuite/dockpanelsuite#268]
![tabs_focus](https://cloud.githubusercontent.com/assets/10151485/5490287/b41f1dc2-86d0-11e4-8570-e506afa98852.jpg)

I have 3 window like on the pic. When you click on tab 1 and 2, switching between them (NOT inside document, just head tabs!) forms create Activated or GotFocus event, but when you click from tab 1 or 2 to 3 nothing happened (component inside receive focus but no event is created). When you click inside form it's ok - all working. It's just about tab clicking. It looks like documents in different dock don't create this event - only on same. Can you check it?
(DockingMdi, AllowEndUserDocking, AllowEndUserNestedDocking)

Update: if i check Me.ActiveMdiChild on main form and dckPanel.ActiveDocument there is difference. ActiveDocument is updated and show right information (new tab), ActiveMdiChild show old info (not updated, previous tab)

**Comment by Huntk23** [comment]
This sounds like tab 3 (possibly new form/window?) does not have it's Activated or GotFocus event registered correctly to communicate with all tabs across the board. To be honest I'd need to see what you are even doing. Don't think this is a DPS issue.
