### ISSUE TITLE
Utilizing Language Features Beyond .NET 2.0

### ISSUE THREAD

**Issue by roken** [dockpanelsuite/dockpanelsuite#27]
For discussion:

Currently the code base is written such that it will compile against .NET 2.0 on a .NET 2.0 era compiler.  At what point do we increase the minimum requirements so that we can use auto-implemented properties, the var keyword, or other features not available to developers under the .NET 2.0 compiler?

The compiler under Visual Studio 2010 supports these language features even when targeting the build to .NET 2.0.  So in effect, we can raise the minimum requirements for the source code without raising the .NET CLR requirements to execute the binaries.

I believe this to be a fair trade off, as the only impact would be that those running VS 2005 would only be able to use the binaries.

**Comment by lextm** [comment]
I started to use a few new syntax while working on the new features. I think we should do it bit by bit.

**Comment by joelbyren** [comment]
Using the latest MonoDevelop on Linux (yeah, I know, this is not your main priority) I currently have to change the target framework from 3.5 to 4.0 each time I start a new branch.
Have you considered moving to 4.0 (or newer) in the near future, if at all?
Oh, and is there any actual plans for a 3.0.0 release?

**Comment by lextm** [comment]
@joelbyren I have changed the projects to .NET Framework 4.0 by default and cross compile to .NET Framework 3.5 during NuGet package generation.

**Comment by lextm** [comment]
Close it now. We probably will not be rushed to use new language features. It can happen bit by bit.
