### ISSUE TITLE
[Question] How to sort tabs?

### ISSUE THREAD

**Issue by lukeer** [dockpanelsuite/dockpanelsuite#270]
Hi there,

I have a DockPanel and several instances of a DockContent-derived class are put into it using
```c#
    DockContent dockContent = new DockContent();
    content.Show(dockPanel, DockState.Document);
```
So they nearly form a TabControl. User can then undock them and float them around. Instead of closing, the contents are put back into the DockPanel.

Now Customer wants a given contents order applied whenever contents are docked in the panel. My derived class has a float value for that to get the order of contents. But DockPanel.Contents doesn't support a  Sort() method. Nor can I remove contents from it in order to put them back in the correct order. I tried
```c#
    dockContent.Show(dockPanel, DockState.Document);
    dockContent.Show(dockContent.Pane, newIndex);
```
to get contents placed in different Indexes. But it doesn't work. Just like
```c#
    dockContent.Pane.SetContentIndex(dockContent, newIndex);
```
User, however, can simply drag'n'drop contents. That includes putting tabs into arbitrary locations and therefore sorting them manually.

How am I supposed to get DockContents docked in a given order programmatically?

**Comment by lextm** [comment]
You should not post both here and at StackOverflow, as maintainers actively track both.

http://stackoverflow.com/questions/28021246/dockpanel-suite-tab-sorting
```
doc1.Show(dockPanel, DockState.Document);
doc2.Show(doc1.Pane, null);
doc3.Show(doc1.Pane, null);
doc4.Show(doc1.Pane, null);
doc1.Show(doc1.Pane, null);
doc2.Show(doc1.Pane, null);
```
The order can be easily controlled by code if you call Show in this way.

**Comment by lukeer** [comment]
Sorry for that, thanks and see you at SO.
