### ISSUE TITLE
Is a 9 element dock indicator in the works?

### ISSUE THREAD

**Issue by EntityDev** [dockpanelsuite/dockpanelsuite#272]
Does DPS now support or will it support the docking behavior in VS 2010+, ie. using a 9 element dock indicator?

Edit: My apologies, I couldn't figure out how to attach a question label.

**Comment by lextm** [comment]
Labels are controlled by maintainers.

It was on the radar, but had been delayed several times. If you are interested in exploring it, you can send us a pull request.

**Comment by EntityDev** [comment]
Lex,

 

Thank you. I did a little reading about labels and found the answer, after posting the issue. 

 

I appreciate the invitation to contribute. However, being a VB developer (who is not proficient in C#), I would not be of much help.

**Comment by lextm** [comment]
Close it now. Anyone who would like to work on it can send a pull request.
