### ISSUE TITLE
Drag & Drop on mono

### ISSUE THREAD

**Issue by ArsenShnurkov** [dockpanelsuite/dockpanelsuite#274]
What are the problems with D&D implementation on mono?

Looks like other people do this:
http://zetcode.com/gui/csharpwinforms/dragdrop/

**Comment by roken** [comment]
Drag & Drop, as well as other features in the DPS are currently implemented using p/invoke calls to Windows assemblies, which obviously wont work on a non-Windows OS.  It's possible that some of these system calls can be replaced with WinForms-level methods that would serve the same function while providing the necessary abstraction of os-level implementation details, but no one has taken the time to investigate it.

**Comment by lextm** [comment]
That sample is too simple (only drag/drop within a form/user control) to fulfill what DPS requires (drag/drop across forms).

**Comment by ArsenShnurkov** [comment]
> soon to close

why to close? Do you definitely know that nobody in the world will never imploement D&D ?

> DPS requires (drag/drop across forms).

How draging between forms differs? What exactly prevents D&D feature?

**Comment by lextm** [comment]
I created the soon-to-close tag, simply to indicate that it is less likely for the maintainers to work on this. You can check [the tag meanings here](https://github.com/dockpanelsuite/dockpanelsuite/wiki/KB100004).

We tried to keep the open item list as short as possible, so as to focus on other important items (especially bug fixes on Windows).

You are welcome to step in and investigate this issue if you like. We can accept PRs in such areas if they are proven to be useful.

**Comment by ArsenShnurkov** [comment]
ok, thanks for the link with explaination of tags
