### ISSUE TITLE
Detached child form also minimized when main form minimzed

### ISSUE THREAD

**Issue by zoracdev** [dockpanelsuite/dockpanelsuite#276]
I've added a dockable form to my main form, however when the child is detached outside the main form I wish to be able to minimize the main form leaving the child in its current position. My problem is that both forms minimize when the main form is minimized.

    MP3PlayerWindow = New MP3Player()
    MP3PlayerWindow.Show(DockPanel1, DockState.DockLeft)

Is there a solution to this please?

**Comment by roken** [comment]
The FloatWindow is owned by the Form on which the DockPanel is located and there isn't currently a built-in configuration to change that (and in WinForms, owned windows will always minimize with their owner).  It might be as simple as creating your own FloatWindow factory that unsets the Owner (see wiki cookbook), but there are likely some other ramifications to that.
