### ISSUE TITLE
DockPanel managing DockContents as Toolbars

### ISSUE THREAD

**Issue by ahuarte47** [dockpanelsuite/dockpanelsuite#280]
I would like to propose a new feature for the DockPanel suite. Implement a new DockArea enum for Toolbars. 

This new enum would define new zones where dock windows with a toolbar style. The new dockable windows are independent of the other non-toolbar DockContents.

I attach a splash of an application to show better the feature:

![dockpanel dockarea-toolbar](https://cloud.githubusercontent.com/assets/5576272/6366791/5082ce5e-bccb-11e4-9bac-dafa88bb665b.jpg)

**Comment by lextm** [comment]
Might be a useful idea, but toolbars + dock panels have been a pattern that is less popular these days, when Microsoft moves to Fluent UI.

So thanks for sharing the idea. If you can create a prototype and send a PR, I am happy to review it.

**Comment by ahuarte47** [comment]
Thanks Lex, I try it.

**Comment by astrohart** [comment]
@ahuarte47 These are called "Tear-Off ToolStrips".  I wrote an article for MSDN Magazine (now Visual Studio Magazine) that documents how to implement them "from scratch."  Perhaps these can give some food for thinking on how to enhance WinFormsUI to support these.

**Comment by ahuarte47** [comment]
Thanks Brian for the info. Unfortunately until now, for lack of time, I have not been able to advance in the development of the idea.

**Comment by astrohart** [comment]
@ahuarte47 Whenever you get around to it, I just randomly bumped into your post and I thought I'd chime in.

**Comment by ahuarte47** [comment]
Thanks @astrohart

**Comment by astrohart** [comment]
Hi Alvaro,

Mind sending a demo of how to utilize the new functionality -- or could you reply with just a high level outline of the steps to make a tear off toolbar with the new functionality.  Thanks.

Brian

**Comment by ahuarte47** [comment]
I prepare a prototype and I send a PR in few days

Best regards
Alvaro

**Comment by ahuarte47** [comment]
Hi, I have prepared a propotype:
https://github.com/dockpanelsuite/dockpanelsuite/pull/337

Best regards
Alvaro

**Comment by lextm** [comment]
Temp close it. Further comments should go to #337

**Comment by ahuarte47** [comment]
ok, Thanks @lextm !
