### ISSUE TITLE
Change dock panel color? Question

### ISSUE THREAD

**Issue by tanhung0506** [dockpanelsuite/dockpanelsuite#282]
![untitled](https://cloud.githubusercontent.com/assets/11399598/6567748/6b946bf6-c6ff-11e4-9f9f-6d857d0dea4f.png)

How can I change the color of this. Look at a picture.
Sorry, my english not good :-)

**Comment by Huntk23** [comment]
```c#
form1.DockPanel.Skin.DockPaneStripSkin.ToolWindowGradient.InactiveCaptionGradient.StartColor = Color.BlueViolet;
form1.DockPanel.Skin.DockPaneStripSkin.ToolWindowGradient.InactiveCaptionGradient.EndColor = Color.BlueViolet;
```

But supposedly "Skin" is obsolete and you need to use Theme. Which means you probably need to create your own theme that inherits ThemeBase or ITheme then you Theme.Apply(dockToApplyTo);
