### ISSUE TITLE
Parent - Child Controls

### ISSUE THREAD

**Issue by csalerno** [dockpanelsuite/dockpanelsuite#285]
I have a ProgressBar on a Parent form I need to access from a child form. I'm able to use the control while the child window is docked but when it is floating the cast I'm using in the child form becomes illegal. 

Anyone have a snippet to determine if the child form is floating and how to cast the MDIParent property to the Parent?

**Comment by Huntk23** [comment]
Do you have a screen shot I can see to reproduce an example? 
Are you doing work in a child form while floating and it's trying to update a progress bar on the main form (parent)?

**Comment by csalerno** [comment]
Thats exactly what im trying to do. I can post some code and screen shot tonight

**Comment by ccslabs** [comment]
Wouldn't it be easier just to raise an event in the child and subscribe to that event in the parent? Like ProgressChanged ?

**Comment by Huntk23** [comment]
Yes ccslabs I agree, I was curious the way he is trying to communicate child to parent.

**Comment by csalerno** [comment]
Ignorance.
Events are really confusing to me. Any examples of Parent\Child events someone can point to?

**Comment by Huntk23** [comment]
Best I can say is Google **c# parent child event** and read up on some Stackoverflow answers. If it still doesn't make sense I can help more if I see what you are doing.

**Comment by csalerno** [comment]
I've searched the above and it has shed some more light on it and beleive I can setup the Event & Listener but unsure as to which Event to use on the System.Windows.Forms.ToolStripProgressBar. My child form is inhereiting the DockContent class. From the Child form not sure what to send thru the event to increment the ProgressBar.

**Comment by ccslabs** [comment]
Create your own event for UpdateProgress Within the Child like this:

internal delegate void ProgressEventHandlerHandler(int progressPercent);
internal event ProgressEventHandlerHandler ProgressEvent;

Then call it within your method like this

if(ProgressEvent != null) ProgressEvent(10);  // Or whatever the value is

the If statement prevents a null exception if the parent (or no one) is subscribed to the event

within the parent you created your Control like this

MyControl ctrl = new MyControl();

You then need to subscribe to the event

ctrl.ProgressEvent +=

press tab twice at this point and VS will complete the rest of the subscriber Method for you

within the subscriber method write

myProgress.Value = progressPercent;

That's you done. Don't forget to set Progress to 0 (Zero) when you are done.

**Comment by csalerno** [comment]
Thank you very much I will take a look.

**Comment by csalerno** [comment]
In looking at your example I'm stuck on the Parent ToolStripProgressBar not having an event of "ProgressEvent".

**Comment by ccslabs** [comment]
It is the child form which has the ProgressEvent

**Comment by csalerno** [comment]
ok, so I guess I'm not clear on what the event is interacting with on the Parent.

In the Child, what is the MyControl ctrl = new MyControl(); representing?

**Comment by ccslabs** [comment]
In the Child Form you have a value which you want the main form's progress bar to display.
You create the Event as shown in the Child form.
then you subscribe to the event in the main form by writing ChildForm cForm = new ChildForm()
cForm.ProgressEvent +=

then a method will be created for you (after pressing tab twice)

in that method you will write
ProgressBar.Value = value;

**Comment by csalerno** [comment]
Thank you that was a lot of help.
