### ISSUE TITLE
How to recreate panels just like the last time after reopening the software?

### ISSUE THREAD

**Issue by qdwang** [dockpanelsuite/dockpanelsuite#286]
I want to remember the panel structure, then to recreate panel arrangement from some data structure after reopening the software.
Is it possible?

**Comment by Huntk23** [comment]
DockSample project is your friend. It has an example how **DockPanel.SaveAsXml(...)** and **DockPanel.LoadAsXml(...)** is used. That will save and restore the original structure of the layout when it closed.

**Comment by qdwang** [comment]
thanks~
