### ISSUE TITLE
Controls on Autohide ToolWindow not visable

### ISSUE THREAD

**Issue by csalerno** [dockpanelsuite/dockpanelsuite#288]
Using version 2.9.0, I have a AutoHide ToolWindow with a Treeview & Textbox controls that wont turn visable  until the window is Pinned. I've tried many repaints and refreshes in various events without luck. Is there a trick to this I'm not seeing?

**Comment by roken** [comment]
Are you still having trouble with this behavior?  If so, could you provide a sample to demonstrate the issue?

**Comment by csalerno** [comment]
Sorry Ryan this has been resolved.



Sent on a Sprint Samsung Galaxy Note® 3


-------- Original message --------

**Comment by roken** [comment]
Good to hear!
