### ISSUE TITLE
IndexOutOfRangeException when having more the one floating window

### ISSUE THREAD

**Issue by ghost** [dockpanelsuite/dockpanelsuite#291]
the exception happens with the following scenario:
having docked document and one or more floating window, it causes the dispose process of my app to crush.

Here are links to the problem in the code:
1)https://github.com/dockpanelsuite/dockpanelsuite/blob/master/WinFormsUI/Docking/DockPaneCollection.cs#L34
2)https://github.com/dockpanelsuite/dockpanelsuite/blob/master/WinFormsUI/Docking/FloatWindowCollection.cs#L28

during the dispose process, the code iterates over its collection and invoking the Close method, which in the described scenario invokes the following code :
https://github.com/dockpanelsuite/dockpanelsuite/blob/master/WinFormsUI/Docking/DockPaneCollection.cs#L41

the problem causes the collection to be changed within the Close method twice, while the i (index) still holding first value. which will causes  IndexOutOfRangeException to be thrown.

suggested solution (only for DockPaneCollection, it supposed to be the same solution for FloatWindowCollection):
internal void Dispose()
{
   List<DockPane> collection = new List<DockPane>(Items);
   foreach (var dockPane in collection)
   {
       dockPane.Close();
   }
   collection.Clear();
}

the internal Items collection, should be copied to an independent collection, which will iterate over the Items collection, those allowing the internal collection to be changed. at the end process just release the independent collection references to the DockPane items.

**Comment by roken** [comment]
Could you provide a copy of the exception with stack trace to better illustrate the issue?

**Comment by nakrul79** [comment]
Had the same problem. It resides in DockPaneCollection.cs. I fixed it changing the Dispose method. Closing seems to remove sometimes more than one item from the collection. Hope this helps.

        internal void Dispose()
        {
            for (int i=Count - 1; i>=0; i--)
            {
                if (i >= Count) { continue; }

                this[i].Close();
            }
        }
