### ISSUE TITLE
Add the DockPanelSuite as .NET framework component in visual studio 2013

### ISSUE THREAD

**Issue by orangely** [dockpanelsuite/dockpanelsuite#295]
Hi,

I'm just new on this and wanted to test it. However when i try to add the .NET framework component through the dll file, i got the error.

"There are no components in ...\WeifenLuo.WinFormsUI.Docking.dll that can be placed on the toolbox"

There is a way to add this as a component?
Thanks in advance.

**Comment by roken** [comment]
Please see #184
