### ISSUE TITLE
How to remove the tabstrip from the documents section.

### ISSUE THREAD

**Issue by JohnyMac** [dockpanelsuite/dockpanelsuite#296]
In some cases, When there is one form open.. I want to hide the tabstrip.
How can this be achieved ?

This is highly needed, Please answer ASAP.

**Comment by lextm** [comment]
I'd like to close this as won't fix, as what's the value of removing the tab strip? Without them it is never an easy task to switch among documents.

**Comment by lextm** [comment]
@roken what's your opinion on this?

**Comment by roken** [comment]
I would agree that this is an enhancement well outside the typical interaction of this control.  We could entertain it if presented in implemented form, but I don't foresee anyone spending time to create this feature.  I'm good with closing out as won't fix.

**Comment by lextm** [comment]
Closed as won't fix. But always, we welcome pull requests.

**Comment by wslkh** [comment]
In some case there will be only one document, and the user will play with the dock panels. I need this feature if it's available. Thanks.
