### ISSUE TITLE
How do I access one form to another in dock panel suite

### ISSUE THREAD

**Issue by ananth85** [dockpanelsuite/dockpanelsuite#297]
Hi all,

I am new to development and learning c# . Net . I have added this component in a form. In one form I have a tree with resource name and in another form I have datagridview. On selecting tree I need a tab to be added with data. Please advise how to do it !!

**Comment by roken** [comment]
This question is beyond the scope of the DockPanel Suite, and is a general question about how to communicate between Forms in WinForms.  Please take a look at [StackOverflow](http://www.stackoverflow.com) to find strategies to accomplish this or to re-ask the question [after having attempted an approach](http://whathaveyoutried.com/).
