### ISSUE TITLE
Question: Starting width on a docked auto-hidden window

### ISSUE THREAD

**Issue by redux8** [dockpanelsuite/dockpanelsuite#298]
I have some tool/work windows that the user can open (from menu or tool bar). The tool window then adds as auto hide on the left or right side depening on the type of window. When the users hovers over the button the tool windows opens and the user can work in it. 

My problem is that I want to set the starting width on each opened window seperatly since some have to be smaller and some larger than the default size. How can I do that? As of now the user have to manually resize it after opening it to get the correct size.

A related question is if it is possible to start with the window opened? And that it hides first after the user entered the window and then leaves it (with the mouse pointer)? It would also be helpful in some cases.

**Comment by lextm** [comment]
You might go through previous discussions. I think yours have already been discussed.

https://github.com/dockpanelsuite/dockpanelsuite/search?q=auto+hide&type=Issues&utf8=%E2%9C%93
