### ISSUE TITLE
Ability to Override Skin Settings on a Per-DockContent Basis

### ISSUE THREAD

**Issue by roken** [dockpanelsuite/dockpanelsuite#3]
Feature request for the ability to change appearances such as the color of a tab for a given DockContent, overriding the colors set in the active DockPanelSkin.

**Comment by lextm** [comment]
I did more theming in the past few days and I think if we allow each dock contents to have their own `ThemeBase` object, then this feature might be achieved. However, it would still be pretty difficult to complete, as the strip/caption/dock window/splitter rendering effect would be hard to associate with such a large amount of theme objects.

**Comment by lextm** [comment]
Close it now. Anyone who would like to work on it can send a pull request.
