### ISSUE TITLE
Designer code produces: 'WeifenLuo.WinFormsUI.Docking.DockPanel.Skin' is obsolete: 'Please use Theme instead.'

### ISSUE THREAD

**Issue by tom-seddon** [dockpanelsuite/dockpanelsuite#300]
I'm using DockPanelSuite (as at: f7ec4acb0b1f396e81e33dac1acf78c227605f51) with VS2013. The forms designer inserts the following line when I add a DockPanel:

    this.dockPanel1.Skin = dockPanelSkin1;

This gives a warning on each build, because the Skin property is deprecated.

I can't reset the property in the forms designer - the Reset option is greyed out on the context menu. I also tried creating a theme on the dialog before adding the DockPanel, but the result was the same.

What's the correct solution for this? I can put up with a warning for now but in the long run I'd much prefer a nice clean build!

Thanks,

--Tom

**Comment by mkalex777** [comment]
You can add designerserializationcisibility attribute with false value on that property in the docking panel source code. So Visual Studio designer will not generate code for it. After that remove the line which is generated by Visual Studio, or just open your form and save it.

**Comment by lextm** [comment]
@mkalex777 would you like to send a pull request?
