### ISSUE TITLE
Autohide Windows not displaying Controls

### ISSUE THREAD

**Issue by csalerno** [dockpanelsuite/dockpanelsuite#302]
I have a couple of Autohide windows, one anchored to the Left and the other to the Bottom. When I click the tab, it expands but the controls are not painted. I have to pin the window, then unpin it and then click the tab again for the Controls to be visible.

What am I doing wrong?

**Comment by lextm** [comment]
Can you provide more info? Since BCL controls do not experience this problem, you might be more specific on which control you were using (from certain vendors or open source projects).

**Comment by csalerno** [comment]
Using simple .Net 4.0 TextBox, Label and Treeview controls.

It's only happening on AutoHide windows. For the controls to display I must pin the window, unpin it and then the controls will be visiable.



Chuck



________________________________

**Comment by csalerno** [comment]
Still have not been able to resolve this. I have the same DockContent derived classed AutoHide windows working fine but the two that are not one has a couple of Textbox and button controls and a TreeView and the other has two Combobox and one ListView control. When I hover over the Autohide tab the window extends but none of the controls are visiable until I click the PushPin.

**Comment by lextm** [comment]
Unless a sample project that can reproduce this issue constantly is provided, it would be impossible to troubleshoot the cause. Temp close.
