### ISSUE TITLE
Ever Thought About Running Resharper Through The Code?

### ISSUE THREAD

**Issue by jtwine** [dockpanelsuite/dockpanelsuite#303]
This project might quality for a free license to Resharper (https://www.jetbrains.com/buy/opensource/).  Is there any reason no one has thought to do this?  Its "Possible NULL Reference exception" code warning is worth its weight in gold for preventing problems down the road.

Note that if you have never used R# professionally before, you need to try it before you shoot down the idea of using it.

**Comment by roken** [comment]
I can't properly function without resharper and DockPanel Suite already makes use of the open source licence generously provided by JetBrains.

Are there particular examples you think are at risk of null references?  Blindly performing null checks at every suggestion is not necessarily a productive exercise and can result in masking the root cause of issues.

**Comment by jtwine** [comment]
As an example of null checks, it is more than just performing null checks, it is performing them and raising a suitable exception that should include debugging information where available, which capitalizes on the experience of the primary developers.  

For example, getting the default NullReferenceException from deep within the code does not do much to help debug it.  But getting one that contains additional information such as "...this can happen in MDI scenarios when merging menu items if you did not set abc' first" would be more helpful, and might help a user figure out what they did wrong as opposed to assuming it is a bug in the library.

IMHO and experience, controlled exceptions are *always* better than uncontrolled ones. In the future, they could also hook into a logging system which could help end users even more when things go wrong.

At a minimum, if R# is already being used, it might be a good idea to annotate anything that would cause R# to light up.  This makes browsing the code much easier (at least, it would for me) when trying to figure out bug fixes or functionality/performance improvements.

**Comment by lextm** [comment]
I think it is more a challenge on WHO will perform the cleanup.

The status of such an old project with multiple technical debts to pay, without its original developer's love, is that current maintainers might not have deep understanding of every corner to perform various tasks such as the one you suggested with confidence.

R# is a good tool but to fix violations a dedicate person with adequate time is required. If you are willing to be the one, I think both @roken and I are more than happy to review and merge the changes submitted.

**Comment by jtwine** [comment]
As mentioned above, time is not the issue - experience with the codebase is.  There is only so much that can be gleaned by walking through the code.  Even if I performed a thorough breakdown of the code, there would still be tacit knowledge that you and/or roken have that I would not.  Suggesting someone that is basically brand new to the code to make such wide-sweeping changes is risky at best, and negligent at worst.

So, the TL:DR version is that none of the current, more experienced maintainers have the ability/capacity/desire to put forth this effort?

**Comment by roken** [comment]
It has already been said that this is a time (capacity) issue, not an ability or desire issue.  Having detailed exceptions for every possible scenario would be a great add, but time is a very limited commodity. Functional/behavioral issues take higher priority over nice-to-have-debugging-assistance on the triage chart, and not just with open source volunteer efforts but commercial products as well. 

Those having trouble with debugging or implementation have multiple forums available to them: this github site, StackOverflow, etc.  Many open source projects also more explicitly drive individuals with support issues or problems during implementation towards paid consulting, which is also an option here.
