### ISSUE TITLE
Skin Obsolete

### ISSUE THREAD

**Issue by Sirais** [dockpanelsuite/dockpanelsuite#307]
Vs comes up with a warning, that .Skin is obsolete, that Them should be used instead.
the designer itself adds the skin element to the dockPanel.
but now the Real Question : how can i Customize the Layout using Theme. i cant fint any hints somewhere (or am i blind?)

**Comment by lextm** [comment]
Just added a wiki page,

https://github.com/dockpanelsuite/dockpanelsuite/wiki/Themes
