### ISSUE TITLE
MenüStrip in another panel than the Document

### ISSUE THREAD

**Issue by Sirais** [dockpanelsuite/dockpanelsuite#308]
How can i make a Menustrip for a form that is attached to DockRight to be append to the Menu of the main form ? (for forms wich are attached to the Document panel this works fine)
![screenshot96](https://cloud.githubusercontent.com/assets/8981994/9519745/a44cfb0a-4cc1-11e5-9880-24c31c94d522.jpg)

**Comment by lextm** [comment]
That's not something falling in the scope of DPS. Even in WinForms you cannot get a form's menu strip merging with another form's menu strip automatically.

You might try to manipulate those strips in code manually instead.

**Comment by Sirais** [comment]
You can Merge the menu of an MDI-Child wit the Menu of the MDI Parent.
You can see it in the Graphic. The "Side menu" is the menu of the form "Form Side" and it merges with the main Menu. That happens only if the Form is shown in the Dockstate.Document.
the only difference between those forms in the Picture ist how they are shown.
            formSide f2 = new formSide();
            f2.Show(dockPanel1,DockState.Document);

            Centerwindow c = new Centerwindow();
            c.Show(dockPanel1); //not different than Document

            Center2 c2 = new Center2();
            c2.Show(dockPanel1, DockState.DockRight);

**Comment by lextm** [comment]
There are far more differences than dock state if you go deeper into the code. Non document mode dock contents are not MDI children at all, so how can the strips merge? In my opinion the behavior you want cannot be achieved without heavy changes and is not beneficial for all DPS users as well.

**Comment by Sirais** [comment]
Oh damn, i didnt knew that the Other forms arent MDI-Childs. in that 
case its realy no wonder that the menus doesnt merge.
topic can be closed.
thanks a lot for letting me know.
looks like i have to find another way to get what i need.


Am 27.08.2015 um 17:10 schrieb Lex Li:
