### ISSUE TITLE
Use dockpanelsuite in MEF, throw exception when load the assemblies. 

### ISSUE THREAD

**Issue by xiaominzi** [dockpanelsuite/dockpanelsuite#309]
# error.description:
**Fail to load file or assemblies “WeifenLuo.WinFormsUI.Docking, Version=2.3.2.0, Culture=neutral,    PublicKeyToken=null” or one of it's dependencies。The definition of the assemblies we found didn't match with the assemblies reference. Exception came from HRESULT:0x80131040**

I use VS2010, got dockpanelsuite 2.9.0.0(**why the version in exception is 2.3.2.0**) by "nuget".  
I also tried generated dockpanel 2.5/2.6/2.7 DLL by meself,  but I can't solved this exception! 
Is there anybody who has suffered this exception? Thanks for your experience !

**Comment by roken** [comment]
The dll from nuget appears to be version stamped properly as 2.9.0 so the fact that it is looking for 2.3.2.0 is indeed interesting, and the error seems to be telling you that something is expecting 2.3.2.0 and finding 2.9.0 or vice versa.  Do you have an explicit version in the dll reference in the project file?  Is SpecificVersion disabled on the assembly reference?  Do you have a version of DockPanelSuite GAC'd?

**Comment by xiaominzi** [comment]
There already existed a old version of DockPanelSuite (2.3.2.0) indeed !  I used the ATF to develop my software. I ignored this reason's existing !
I directly used the lower version and this exception disappeared !
Thanks   for your recommendation!
