### ISSUE TITLE
Split non-default themes to separate assemblies

### ISSUE THREAD

**Issue by lextm** [dockpanelsuite/dockpanelsuite#315]
The original theme based design a few years ago was aiming to separate the themes to individual assemblies. In this commit the split is finally carried out, 567cfde23a51d35b05723e8b9a52ddbe5a01104f

It should demonstrate how to create a new theme (VS 2013 Blue) from another theme (VS 2012 Light) gradually, as currently many elements are borrowed directly (while the final work might fully use its own elements, who knows).

**Comment by lextm** [comment]
@roken what's your feedback on this?

**Comment by roken** [comment]
I generally oppose using assemblies for purely organizational purposes, but it seems quite reasonable that an application would only package a single theme (not that these assemblies will have a very large footprint).  I can get behind this.

**Comment by lextm** [comment]
Merged vs2013blue branch via cb4182b4b6184416a8004201d485a1dc064cbef8. Closed this now.
