### ISSUE TITLE
Copy & Paste dont work in FastColoredTextbox in Docking Panel

### ISSUE THREAD

**Issue by GAMELASTER** [dockpanelsuite/dockpanelsuite#324]
Hello, i have Window with FastColoredTextBox docked in dockingPanel. I dont know, but when its docked, the Ctrl + V dont work, CTRL + B (bookmark), CTRL + F etc.. works, but Copy, paste dont. When i grab it outside dockingpanel to Float, Ctrl + V works.
I tryied to change documentstyle to others but anyway its dont work. Any ideas to fix?
Thanks

**Comment by GAMELASTER** [comment]
Keys what dont work: Control + YXCVNOP . O_O

**Comment by GAMELASTER** [comment]
Fixed! When deleting StatusTrip, toolStrip and MenuStrip Copy started working O_O.

**Comment by rogerjak** [comment]
I'm having the exact same issue, but removing menu/status/tool-strip is not a solution.
Why can't I have all that and FCTB in dockpanels?
Thanks
