### ISSUE TITLE
How to change the theme?

### ISSUE THREAD

**Issue by apachexampp** [dockpanelsuite/dockpanelsuite#326]
In DockPanel there is no option of selection the theme. 
There is a property SkinStyle but option to select the template does not exist. 
How do I change the theme, version downloaded from Nuget.

**Comment by lextm** [comment]
Simply add other theme NuGet packages and create instances of the themes. By assigning them one by one to `DockPanel.Theme` you get what you want.

**Comment by lextm** [comment]
Just finished an article on this topic, https://dockpanelsuite.readthedocs.org/en/latest/themes/existing-themes.html

**Comment by apachexampp** [comment]
About theme VS2013
1. Download from NuGet package from [GitHub](https://www.nuget.org/packages/DockPanelSuite.ThemeVS2013Blue/2.10.0-beta1)
2. Add to program before reading DockPanel config file: 
`this.dockPanel1.Theme = new VS2013BlueTheme();`
3. It's all
