### ISSUE TITLE
Gradient color tab - bad behaviour

### ISSUE THREAD

**Issue by Progress1** [dockpanelsuite/dockpanelsuite#329]
If goes tab to the right it looses StartColor gradient. On the picture i select red and white.
(DockPane.DockPanel.Skin.DockPaneStripSkin.DocumentGradient.InactiveTabGradient.StartColor)
and all is happened on this line:
 g.FillPath(new LinearGradientBrush(rectBack, startColor, endColor, gradientMode), path);

![clipboard01](https://cloud.githubusercontent.com/assets/10151485/11614238/93d85100-9c3c-11e5-9b0e-7edd7e5b7c08.png)

I think all tabs should have the same look. Now only the first tab has right gradient.

**Comment by Progress1** [comment]
Solution is comment:
**//rectBack.Width += rect.X;**
**//rectBack.X = 0;**
And replace it with:
**rectBack.Width += DocumentIconGapLeft;**
**rectBack.X -= DocumentIconGapLeft;**
then each tab has equal gradient
![clipboard01](https://cloud.githubusercontent.com/assets/10151485/11695390/27afa8f0-9eaf-11e5-8edd-864881cb851f.png)

**Comment by lextm** [comment]
Thanks for sharing, and can you send a pull request?
