### ISSUE TITLE
Document tab opened over a previous tab is not painting its background

### ISSUE THREAD

**Issue by astrohart** [dockpanelsuite/dockpanelsuite#335]
![transparentmdiform](https://cloud.githubusercontent.com/assets/8261875/12541177/f6efa5c0-c2c7-11e5-806e-781153c122c9.png)

This is happening in an albeit heavily customized application.

I have also not set MdiParent = this for either of these tabs, but the Main Window is having IsMdiContainer = true.  Setting view.MdiParent = this results in an "Error creating window handle" exception; however, if I do up a new app with the File -> New Project and then put the same version of WinFormsUI in the new project, I can set view.MdiParent = this no problem.

For testing purposes, I implemented a GreenForm who is derived from DockContent.  As you can probably see, then i open one of my application's document data files and of course said data file has its own form.

There are supposed to be dialog-style controls etc. in the form, along with a preview pane.  However, as you can tell, the GreenForm is 'under' the current tab and the 'insides' of the newly-opened tab aren't painting.  If I click the GreenForm tab and then the Arredondo, Frank tab with the mouse, then the newly-opened 'Arredondo, Frank' tab gets painted just fine, and the 'green' is covered up.

Brian Hart

**Comment by lextm** [comment]
Start as a question and I will try to reproduce it. Or if you can write a smaller sample to reproduce it.

**Comment by astrohart** [comment]
I've tried to reproduce this but for a simple, bare-bones app it works just fine. It's only if you make a very sophisticated, Windows-forms enterprise-level piece of software, with managed-window instantiation etc. that then i run into issues.  It's very sporadic.  Such as, I fixed it in the app screen-shotted above, but for the life of me, I can't remember how I fixed it.  It was some random change that got it working, and I don't know what.  It seems to be related to when a form has dialog-controls on it inside a document tab.  Then the document tab's insides won't paint until you click on the other tab and then click on the current tab again.

**Comment by astrohart** [comment]
Hi lextm,

Just another update.  The DockPane.IsActiveDocumentPane event seems to fire just once for the entire application -- when the first DockState.Document pane is shown/added.  Then it's not fired for any of the other tabbed-document windows, even when i click their tabs. 

From the moment I *click* with my mouse on a Tab in the Document Well, what is the call stack? What is the very first method/event that is triggered by that action?

I am finding Weifen's old code very hard-to-maintain.  He has a lot of really weird usage of design patterns in there.

Thanks.

**Comment by astrohart** [comment]
I marked this issue closed by mistake.  It needs to be reopened -- unless the code has been fixed?

Regards,
 
Brian Hart
CEO, xyLOGIX, LLC
11232 Vista Sorrento Pkwy #M103
San Diego, CA 92130
(858) 925-4638 mobile
www.xylogix.net
