### ISSUE TITLE
DockPanel Suite DockContent all appearing at top left of DockPanel

### ISSUE THREAD

**Issue by 7ASecond** [dockpanelsuite/dockpanelsuite#338]
Using latest Beta 2 NuGet Package
VS 2015 on Win 10
x86 Targetted Solution

![image](https://cloud.githubusercontent.com/assets/13124484/12780905/c76bdf96-ca68-11e5-9f22-131b07545ccc.png)

Sometimes when my program starts it fails to place the DockPanel DockContent in the correct places assigned in the configuration file.

The config file looks like this:

```
<?xml version="1.0" encoding="utf-16"?>
<!--DockPanel configuration file. Author: Weifen Luo, all rights reserved.-->
<!--!!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!!-->
<DockPanel FormatVersion="1.0" DockLeftPortion="0.25" DockRightPortion="0.25" DockTopPortion="0.25" DockBottomPortion="0.25" ActiveDocumentPane="-1" ActivePane="-1">
  <Contents Count="5">
    <Content ID="0" PersistString="Imogen3.Forms.Dockable.FrmLogging" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
    <Content ID="1" PersistString="Imogen3.Forms.Dockable.FrmTimers" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
    <Content ID="2" PersistString="Imogen3.Forms.Dockable.FrmImageAssessmentControl" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
    <Content ID="3" PersistString="Imogen3.Forms.Dockable.FrmRestrictedBrowser" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
    <Content ID="4" PersistString="Imogen3.Forms.Dockable.FrmGroupCandidates" AutoHidePortion="0.25" IsHidden="False" IsFloat="False" />
  </Contents>
  <Panes Count="3">
    <Pane ID="0" DockState="DockBottom" ActiveContent="0">
      <Contents Count="1">
        <Content ID="0" RefID="0" />
      </Contents>
    </Pane>
    <Pane ID="1" DockState="DockBottom" ActiveContent="1">
      <Contents Count="1">
        <Content ID="0" RefID="1" />
      </Contents>
    </Pane>
    <Pane ID="2" DockState="Document" ActiveContent="2">
      <Contents Count="3">
        <Content ID="0" RefID="2" />
        <Content ID="1" RefID="3" />
        <Content ID="2" RefID="4" />
      </Contents>
    </Pane>
  </Panes>
  <DockWindows>
    <DockWindow ID="0" DockState="Document" ZOrderIndex="1">
      <NestedPanes Count="1">
        <Pane ID="0" RefID="2" PrevPane="-1" Alignment="Right" Proportion="0.5" />
      </NestedPanes>
    </DockWindow>
    <DockWindow ID="1" DockState="DockLeft" ZOrderIndex="2">
      <NestedPanes Count="0" />
    </DockWindow>
    <DockWindow ID="2" DockState="DockRight" ZOrderIndex="3">
      <NestedPanes Count="0" />
    </DockWindow>
    <DockWindow ID="3" DockState="DockTop" ZOrderIndex="4">
      <NestedPanes Count="0" />
    </DockWindow>
    <DockWindow ID="4" DockState="DockBottom" ZOrderIndex="0">
      <NestedPanes Count="2">
        <Pane ID="0" RefID="0" PrevPane="-1" Alignment="Right" Proportion="0.5" />
        <Pane ID="1" RefID="1" PrevPane="0" Alignment="Right" Proportion="0.215625" />
      </NestedPanes>
    </DockWindow>
  </DockWindows>
  <FloatWindows Count="0" />
</DockPanel>
```
within my code I have these three DockPanel methods which Gets the ContentFromPersistString, Saves and Loads the Configuration file.

```
private readonly DeserializeDockContent _deserializeDockContent; 

private IDockContent GetContentFromPersistString(string persistString)
        {
            MainLog("GetContentFromPersistString " + persistString);
            if (persistString == typeof(FrmLogging).ToString())
            {
                logToolStripMenuItem.Checked = true;
                _frmLogging.Dock = DockStyle.Fill;
                return _frmLogging;
            }
            else if (persistString == typeof(FrmTimers).ToString())
            {
                timersToolStripMenuItem.Checked = true;
                _frmTimers.Dock = DockStyle.Fill;
                return _frmTimers;
            }
            else if (persistString == typeof(FrmImageAssessmentControl).ToString())
            {
                imageAssessmentToolStripMenuItem.Checked = true;
                _frmIac.Dock = DockStyle.Fill;
                return _frmIac;
            }
            else if (persistString == typeof(FrmRestrictedBrowser).ToString())
            {
                restrictedBrowserToolStripMenuItem.Checked = true;
                _frmRb.Dock = DockStyle.Fill;
                return _frmRb;
            }
            else if (persistString == typeof(FrmGroupCandidates).ToString())
            {
                groupCandidatesToolStripMenuItem.Checked = true;
                _frmGc.Dock = DockStyle.Fill;
                return _frmGc;
            }
            else
            {
                MainLog("Received Window PersistString: " + persistString);
                return null;
            }
        }

        private void LoadDockingWindowsConfiguration()
        {
            MainLog("LoadDockingWindowsConfiguration()");
            // ReSharper disable once AssignNullToNotNullAttribute
            string configFile = Path.Combine(Path.GetDirectoryName(Application.ExecutablePath), "DockPanel.config");

            try
            {
                if (File.Exists(configFile))
                    dockPanel1.LoadFromXml(configFile, _deserializeDockContent);
            }
            catch (Exception ex)
            {
                MainLog("Error: LoadDockingWindowsConfiguration " + ex.Message);
            }

        }

        private void SaveDockingWindowConfiguration()
        {
            MainLog("SaveDockingWindowConfiguration()");
            // ReSharper disable once AssignNullToNotNullAttribute
            string configFile = Path.Combine(Path.GetDirectoryName(Application.ExecutablePath), "DockPanel.config");
            if (_saveLayout)
                dockPanel1.SaveAsXml(configFile);
            else if (File.Exists(configFile))
                File.Delete(configFile);
        }
```
in the MainForm initializer I have this:

 `_deserializeDockContent = GetContentFromPersistString;  `
We Load the Docking configuration in the Form Load Event like this:

` LoadDockingWindowsConfiguration();  `
**This is a real nuisance, any help in getting the DockContent placed in the correct locations would be appreciated.**

**Comment by lextm** [comment]
It would be difficult for us to reproduce it locally. Can you prepare a small sample project that can reproduce this issue stably and share with us (via Dropbox or any similar service)?

**Comment by RedMser** [comment]
I am running the latest version of the DockPanel Suite (2.10.0.0) and am currently experiencing the same problem: [Screenshot](http://i.imgur.com/oZvHPah.png). This bug is not only happening when loading DockContent using LoadFromXML, but also when creating any _new_ DockContent and adding it to the DockPanel.

I will try to create a smaller project showcasing the same issue if possible.

**Comment by lextm** [comment]
@RedMser Thanks for your hard work, and now it is time to find a solution.

**Comment by lextm** [comment]
@RedMser Can you attach the sample projects to this issue so that I can take a look at the code? I tried to modify the default sample we ship to throw exceptions at the spots you mentioned, but they simply brought down the program, instead of leaving it with invalid layout.

**Comment by RedMser** [comment]
@lextm Here's the project file that I used to test this bug: [DockContentLoadingBug.zip](https://github.com/dockpanelsuite/dockpanelsuite/files/428328/DockContentLoadingBug.zip)

To reproduce: remove the docking.xml in the bin/Debug/ folder. Press the "new" button to create normally working DockContents, then press "Save". Restarting the program will load the XML, causing no DockContent loaded. If you however add another set of DockContents with "New", they will enter this state.

**Comment by lextm** [comment]
@RedMser Thanks. I finally get the points. This weird layout only comes after an unhandled exception is ignored at runtime.

My personal understanding is that the exceptions must be fully handled in deserialization handler as well as dock content constructors, which reliably prevents this issue from happening. So there is nothing to fix in DPS itself. Patching DPS might hide the exceptions from the developers which I think is a bad approach.

**Comment by RedMser** [comment]
@lextm Alright, I understand.

While I don't know too much about your implementation and what would be possible, one possible solution would be to throw an exception whose InnerException points to the exception thrown inside of the deserialize method. This is also done for TargetInvocationExceptions, and should be easy to understand by the regular user if the message hints at there being more info if you look at the InnerException.

Even then, having this weird layout issue instead of the Load being cancelled and having the DockPanel work as normally expected (which I can already assume would be pretty hard) would also be a useful solution.

**Comment by lextm** [comment]
The unhandled exception dialog should occur before such weird layout happens, so I think that is a more obvious indicator of critical problems. Meanwhile, without wrapping as an inner exception, it is much quicker for the debugger to break at the right spot.
