### ISSUE TITLE
Docked panel location

### ISSUE THREAD

**Issue by jhansensc** [dockpanelsuite/dockpanelsuite#339]

**Comment by jhansensc** [comment]
My users will have the ability to have many Documents opened and docked where they wish.  How do I grab the location of the docked panel before closing it, so I can open a new one in the exact same location?

**Comment by kostasvl** [comment]
Look for MainForm_Closing and MainForm_Load in the DockSample. That entire file is worth a good look. MainForm.SetSchema might be more educational, since, as you'll find out, your DockContents need to have been created before you load the layout. I had to write a lot of wrapper code in my application to get around this. I might post a rant/proposal about it at some point :)

**Comment by jhansensc** [comment]
Thank you for your response.  I am brand new to the DockPanel Suite and of course I have a deadline tomorrow ☺  I have yet to find ANY documentation for the Suite, are you aware of any?

I have a Search area of my screen, where users enter criteria and return results to a datagrid.  Currently, as they scroll through the grid, they have buttons that can open as many various child Documents as they need.  This allows them the flexibility to review different records at once.  However, one of our users would like to open certain child Documents, arrange them on his screen, scroll through the grid and refresh the criteria that appears in the existing Documents in the exact same layout.

Ideally, in order to reuse existing code,  I would like to have a checkbox that says “Use Same Windows”.  If it is checked, grab the location of each panel, close it, reopen it with the new data in the exact same place.  But maybe I’ll have to create permanent content panels that can’t be hidden, moved or closed, and just refresh the result selection change’s data.  It appears that the PersistString is good for retaining values at startup?

**Comment by kostasvl** [comment]
As you can tell, I don't have a lot of time to help, I'm sorry. Here's a summary of how you could accomplish what you want, assuming I understood it correctly. I've done it a bit differently in my program, but I think the below approach will work.

1) Create your "RecordViewer" Form in the Designer, and make it inherit from DockContent, of course.
2) Make sure they override GetPersistString (I think that's the name), to return something unique that identifies each of them. A simple number will do: "MyRecordViewerForm01", 2, etc.
3) Set HideOnClose=true
4) Make sure they are reusable, by being able to refresh their content from completely different data
5) Load the docking layout at the start of your program. It won't do anything the first time.
6) Let the user create instances of your DockContent forms as needed. See step 2 again! Call Show(dockpanel, ...) of course. Store them all in a list somewhere?
7) Reuse them as the user views different data. Create new ones if needed. Call Show again on any that have been hidden.
8) Save the layout on exit. Just before doing that, you might want to programmatically Hide any forms that are still visible, unless you want them to automatically be shown the next time.
9) Use that lambda in the layout load method to link the saved positions to the previous instances. You should dynamically recreate the instances here, within that lambda. If the lambda wants you to give it "MyRecordViewerForm04", create it and assign it the number 4, then return it. Don't call Show on it yet. The code from step 6 should be modified to use these instances first, before creating fresh ones.
10) You are effectively back to step 6 and 7 again. Done? :)

I hope this helps.
