### ISSUE TITLE
System.ArgumentOutOfRangeException on LoadFromXml

### ISSUE THREAD

**Issue by djjaysmith** [dockpanelsuite/dockpanelsuite#344]
When executing LoadFromXml I am getting a System.ArgumentOutOfRangeException which states;

Index was out of range. Must be non-negative and less than the size of the collection.\r\nParameter name: index

Full stack trace is here:

> at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)\r\n   at System.Collections.Generic.List`1.get_Item(Int32 index)\r\n   at WeifenLuo.WinFormsUI.Docking.DockContentCollection.get_Item(Int32 index)\r\n   at WeifenLuo.WinFormsUI.Docking.DockPanel.Persistor.LoadFromXml(DockPanel dockPanel, Stream stream, DeserializeDockContent deserializeContent, Boolean closeStream)\r\n   at WeifenLuo.WinFormsUI.Docking.DockPanel.Persistor.LoadFromXml(DockPanel dockPanel, Stream stream, DeserializeDockContent deserializeContent)\r\n   at WeifenLuo.WinFormsUI.Docking.DockPanel.Persistor.LoadFromXml(DockPanel dockPanel, String fileName, DeserializeDockContent deserializeContent)\r\n   at WeifenLuo.WinFormsUI.Docking.DockPanel.LoadFromXml(String fileName, DeserializeDockContent deserializeContent)\r\n   at sLiteExplorer.fMain.LoadLayout() in C:\\Users\\esmjaso\\Documents\\Visual Studio 2015\\Projects\\sLiteExplorer\\sLiteExplorer\\Forms\\fMain.cs:line 129\r\n   at 
sLiteExplorer.fMain.FormMain_Load(Object sender, EventArgs e) in C:\\Users\\esmjaso\\Documents\\Visual Studio 2015\\Projects\\sLiteExplorer\\sLiteExplorer\\Forms\\fMain.cs:line 70

[layout.zip](https://github.com/dockpanelsuite/dockpanelsuite/files/163317/layout.zip)

Attached is my layout.xml file used

**Comment by lextm** [comment]
Have you customized the persistence method in any way? Have the layout.xml file been modified after being generated by DPS?

http://docs.dockpanelsuite.com/en/latest/tutorials/customizing-persistence.html

Unless you can provide a stable sample project to reproduce this issue, we cannot work on it.

**Comment by lextm** [comment]
This issue can be reopened if more info is shared.
