### ISSUE TITLE
System.InvalidOperationException on LoadXML

### ISSUE THREAD

**Issue by Zeul** [dockpanelsuite/dockpanelsuite#345]
When resuming the layout from saved xml, InvalidOperationException is thrown if at least 1 of the panels is floating. If none of the panels are floating there is no problem.

The issue is caused by a workaround that has been added in DockContentHandler:SetParent. If the Activate (line 820) is not called there is no error and the load continues as expected.

**Comment by lextm** [comment]
Can you provide more information as below?

1. Which version of DPS do you use?
2. Have you use your own persistence customization as we documented in the documentation site?

http://docs.dockpanelsuite.com/en/latest/tutorials/customizing-persistence.html

I could not reproduce this issue right now by using the default sample we shipped.

**Comment by Zeul** [comment]
Well, the strangest thing - now it works as expected. Most bizarre.

**Comment by lextm** [comment]
This issue can be reopened if more info is shared.
