### ISSUE TITLE
DLL files

### ISSUE THREAD

**Issue by ahmeeeed** [dockpanelsuite/dockpanelsuite#346]
Hello , i had downloaded the source code, but i can't fing the DLL File.

thank you to help me

**Comment by lextm** [comment]
On a machine with .NET Framework 4 installed, use all.bat.

**Comment by ahmeeeed** [comment]
![capture](https://cloud.githubusercontent.com/assets/17782557/13709066/502340a2-e7b2-11e5-8cf4-4c3d66c97988.PNG)

**Comment by lextm** [comment]
Just update the steps in documentation site,

http://docs.dockpanelsuite.com/en/latest/getting-started/installing-in-visualstudio.html

You need to use all.bat to compile the source code to binaries and then install the binaries to Visual Studio.
