### ISSUE TITLE
The difference between  different DocumentStyle

### ISSUE THREAD

**Issue by chucklu** [dockpanelsuite/dockpanelsuite#348]
public enum DocumentStyle
    {
        DockingMdi,
        DockingWindow,
        DockingSdi,
        SystemMdi,
    }

**Comment by chucklu** [comment]
DockingSdi,  Sdi for what? single document interface?

**Comment by chucklu** [comment]
what does DockingWindow look like ?
i have check the docksample,can not totally understand the difference

**Comment by chucklu** [comment]
测试的时候，DockingMdi和DockingWindow，怎么感觉是一样的呀

**Comment by lextm** [comment]
The document style was designed in a way to better align with Windows Forms' builtin MDI/SDI design. Unless you are migrating a Windows Forms SDI/MDI application to DPS, you probably would not even bother to use anything other than `DockingWindow`.

**Comment by chucklu** [comment]
DPS?  文档处理系统（Document Processing System）

所以，默认使用DockingWindow就可以了？

**Comment by lextm** [comment]
DPS is DockPanel Suite.

**Comment by chucklu** [comment]
所以，DockingMdi和DockingWindow的区别是什么呢？

**Comment by chucklu** [comment]
额？人呢？DockingMdi和DockingWindow的区别？
我实际测试的时候，发现这2个，是一回事？

**Comment by roken** [comment]
They use different mechanisms.  DockingMdi uses [Windows OS MDI](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644908%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396), DockingWindow does not.

**Comment by chucklu** [comment]
@roken ,thank you
