### ISSUE TITLE
切换DocumentStyle的时候，从DockingWindow切换到Mdi或Sdi的时候，界面上的控件消失了

### ISSUE THREAD

**Issue by chucklu** [dockpanelsuite/dockpanelsuite#349]
如题所述

**Comment by chucklu** [comment]
用的是源码里面的DockSample

**Comment by chucklu** [comment]
而且默认选中的子窗体，每次都在变化

**Comment by lextm** [comment]
Please understand the fact that for an international project like this we only welcome English based discussion. I will close such threads.

**Comment by chucklu** [comment]
pls check the DockSample

**Comment by chucklu** [comment]
another problem is when i switch the DocumentStyle,the default selected form is not the same one

**Comment by chucklu** [comment]
could you reopen this issue?
http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github
you cannot re-open your own issues if a repo collaborator closed them
