### ISSUE TITLE
Show Content Icon in FloatWindow

### ISSUE THREAD

**Issue by roken** [dockpanelsuite/dockpanelsuite#35]
The float window should reflect the icon of the active content instead of showing the default winforms icon.  The benefit is only realized by applications that change the floatwindow style via the extender since by default no icon is shown.

**Comment by glopesdev** [comment]
Not sure when the regression might have happened, but this is still an issue in the latest version of DPS. Simply create a `DockPanel` with a single `DockContent` with an icon and set `ShowDocumentIcon = true`. Adding this content to the dock panel will show the Icon on the document, but not in the `FloatWindow` when dragging the document outside the dock panel.

I have confirmed that this code is in effect, and indeed the `Icon` property is set in `FloatWindow` and holds the correct icon, but for some reason it doesn't render.
