### ISSUE TITLE
DockSample中Tools下的Show Right to Left的意义？

### ISSUE THREAD

**Issue by chucklu** [dockpanelsuite/dockpanelsuite#350]
我测试的时候，发现这个东西的作用，是把整个视图，左右颠倒了？
这是干嘛用的？

**Comment by chucklu** [comment]
左右颠倒之后，新建的窗口，标题都看不到了

**Comment by lextm** [comment]
Please understand the fact that for an international project like this we only welcome English based discussion. I will close such threads.

**Comment by chucklu** [comment]
could you reopen this issue?

**Comment by lextm** [comment]
https://msdn.microsoft.com/en-us/library/7d3337xw(v=vs.100).aspx

Right-to-left is a feature to support some specific languages. If you don't design UI in those languages, you don't need to (and shouldn't) set it to `true`.
