### ISSUE TITLE
DockSample中的VSToolStripExtender皮肤

### ISSUE THREAD

**Issue by chucklu** [dockpanelsuite/dockpanelsuite#351]
这个怎么没有直接集成到dll里面？

**Comment by lextm** [comment]
Please understand the fact that for an international project like this we only welcome English based discussion. I will close such threads.

**Comment by chucklu** [comment]
Could you reopen this issue?

**Comment by lextm** [comment]
This class is used to change tool strip rendering and has nothing to do with DPS itself, so it will be part of the sample project only.

**Comment by lextm** [comment]
Please check #411 for more details.
