### ISSUE TITLE
HideOnClose property in DockContent class

### ISSUE THREAD

**Issue by chucklu** [dockpanelsuite/dockpanelsuite#352]
dockpanelsuite\winformsui\docking\dockcontent.cs

I have set HideOnClose property to be true,
When I call the Close method,and try to use dockcontent ,but the dockcontent was disposed

**Comment by lextm** [comment]
That property is only useful when you click the close button on UI, but takes no effect if you explicitly call `Close` method in code.

Please call `Hide` instead.
