### ISSUE TITLE
Can not hide the close button !

### ISSUE THREAD

**Issue by tungnxse03325** [dockpanelsuite/dockpanelsuite#356]
I want to hide the close button . i used this but it doesn't work
this.mydockcontent.CloseButtonVisible = false ;

**Comment by roken** [comment]
Which theme are you using?  A quick test in the DockSample has this working with everything except the 2003 theme (which should probably be addressed).

**Comment by tungnxse03325** [comment]
i used new blue theme . can u send me a sample project that u using CloseButtonVisible ?, i will try run it on my local .
Thanks  so much !

**Comment by roken** [comment]
In the sample application included in the solution, I opened DummyOutputWindow in the Designer and change CloseButtonVisible to `false`.  This worked as expected with the 2013 theme.

**Comment by Algorithman** [comment]
Have to disagree
Does not work for me.

I have my dockpanel set up as DockingWindow, adding 2 DockContents with DockState.Document, but CloseButtonVisible does nothing.

**Comment by Algorithman** [comment]
in DrawTab_Document (VS2012LightDockPaneStrip.cs) you do not check for visibility at all

**Comment by verysimplenick** [comment]
Same issue Vs2012LightTheme

**Comment by lextm** [comment]
Related to #194. To shed some light here with a long history. The original property `CloseButtonVisible` was designed for old themes VS2003 and VS2005, where there is a dedicate close button for all tabs.

When I worked on the new theme of VS2012, I decided not to use this property for the new theme, as there is a close button per tab. Thus, this behavior was desired.

If you do need to hide close buttons in VS2012/2013 themes, please derive from them your own themes and then remove the button rendering code.

It is a design goal to make each themes matching their corresponding VS look and feel, so I don't think we should left switches for visual elements everywhere to pollute the code base.

**Comment by verysimplenick** [comment]
if `CloseButtonVisible` only for vs2003\vs2005 theme remove it from new theme or add label like deprecated or something else. I think if object has setter `CloseButtonVisible` it's must work.

**Comment by lextm** [comment]
@verysimplenick if you run your own open source project, you will see how difficult a choice like that can be made. This thread has been marked as FAQ candidate and that's so far the thing I can do.
