### ISSUE TITLE
Set new floating window to behave like a document area?

### ISSUE THREAD

**Issue by Neverbirth** [dockpanelsuite/dockpanelsuite#358]
Is it possible to make a new floating window to behave like a document area? ie: tabs on top, close button, document list button, only allow to dock other documents, etc.

**Comment by lextm** [comment]
It is possible to customize the float window,

http://docs.dockpanelsuite.com/en/latest/tutorials/customizing-floatwindow.html

But whether the final effect you want can be achieved is unknown.

We welcome pull requests if you figure it out.

**Comment by Neverbirth** [comment]
Already saw that part of the documentation. I was hoping this was possible out of the box or known, as VS behaves like this. I'll try to take a look into this, but if someone beats me to it I won't complain heh, I never played with DockPanelSuite internals before.

**Comment by Neverbirth** [comment]
I got to implement this by adding a new DockState/DockArea. More work than desired, but feels like the right way, although maybe my implementation is not the best and there are issues I haven't found yet. It seems to be working fine with all my requirements, proper ActiveDocument behavior, document appearance, etc, etc.

I'll make a PR, although before I would like to know your opinion on the changes. I'll upload my changes ASAP.

**Comment by lextm** [comment]
Thanks for the contribution. If possible, make your custom `FloatWindow` part of the VS2012/2013 themes, so that it fits in the best places. VS2003/2005 themes do not need such customization.

Of course, send us a PR first, and we can start code review and further discussion.

**Comment by lextm** [comment]
This question can be reopened if more info is shared.

**Comment by Neverbirth** [comment]
Yeah, totally sorry. Completely busy days, once I can get back to this I'll create the PR, because I need other stuff to be approved first in other projects.

**Comment by DanCarterGMSL** [comment]
I would also find this useful.

The current behaviour of floating windows does not match Visual Studio, because the tabs are at the bottom like Solution Explorer rather than at the top like documents.

**Comment by glopesdev** [comment]
@Neverbirth any chance you still have your prototype lying around? Emulating a FloatWindow with an independent DockArea like VS is exactly what we need and would be great to have some idea of where to go around poking.

**Comment by glopesdev** [comment]
Seems like a lot of the current behavior stems from the assumption that all `FloatWindow` instances should be handled using `AppearanceStyle.ToolWindow`:

https://github.com/dockpanelsuite/dockpanelsuite/blob/577d5b8b85b27c0bcb48c885fed56eba31ed3bcc/WinFormsUI/Docking/DockPane.cs#L472-L475

Most drawing measurements, hit tests, etc. have already been correctly implemented throughout `DockPane` conditioned on this `Appearance` property, so if e.g. the above line gets changed to always return `AppearanceStyle.Document` we get almost all the way there, and new `FloatWindow` instances will render and behave almost identical to the main document panel. 

It would be nice to allow subclasses of `DockPane` to configure their default appearance style for theming purposes, so maybe this property could be made `virtual`?

Other than setting the appearance for float panes, there are a few remaining issues:
  - the now empty tool strip still takes up space at the bottom of the float (maybe it doesn't auto-hide properly);
  - the `ActiveDocument` property does not currently update taking floats into account;
  - the title of the float window becomes empty as soon as we dock two documents side-by-side; instead it should use the name of the currently focused document regardless of the docking layout (as it already does if only a single dock area is used).

Seems like it should be doable to fix all of the above by modifying / extending existing infrastructure.

> This question can be reopened if more info is shared.

@lextm Do you think the summary above is sufficient to reopen this issue? I would like to use it to keep track of developments. If you feel anything else is missing let me know and I am happy to investigate more.
