### ISSUE TITLE
Scrolling the docked form

### ISSUE THREAD

**Issue by ahmeeeed** [dockpanelsuite/dockpanelsuite#360]
Hi,
Is there a way to add scroll bars to the docked form, i put the AutoScroll=True but there is no scroll-bars.
thanks.
![image](https://cloud.githubusercontent.com/assets/17782557/14634768/cbc4c250-0623-11e6-8de3-d71f44024bfc.png)

**Comment by roken** [comment]
Setting AutoScroll to true on the DockContent is indeed the way to enable scrolling.  It sounds like your control containing the textboxes is not properly anchored to allow it to dictate the size.

Note that these are general WinForms concepts and are not specific to the DPS library.

**Comment by ahmeeeed** [comment]
Yes it's ok, the problem is caused by a method which set a groupbox in the middle of the form. when i delete it every thing works. thanks .
