### ISSUE TITLE
stop dockpanel resizing

### ISSUE THREAD

**Issue by travendrasingh** [dockpanelsuite/dockpanelsuite#363]
Hi, 

i need to stop dockpanel resizing when i resize the child movable window.
and dockpanel have autoscrolling = true.

(I have added a window form on dockpanel as document and set window form autoscroll = true 
then also added multiple movable window on previous added form.)

Thanks.

**Comment by lextm** [comment]
Can you provide more details, such as screen shots?

**Comment by lextm** [comment]
This question can be reopened if more info is shared.
