### ISSUE TITLE
Display long text in tab header (Long Tab Names Clipped)

### ISSUE THREAD

**Issue by dobalex** [dockpanelsuite/dockpanelsuite#364]
Hi,

I need to display long text in tab headers. Currently, if the text is long it is being clipped. Can I set the width of the tab headers or maximum width until the text is clipped?

For example, I have text: "SOME TAB HEADER TEXT". It is clipped to "SOME TAB HEA...". I want to have all my text displayed (if there is space): "SOME TAB HEADER TEXT".

Thanks in advance.

**Comment by lextm** [comment]
Such text is rendered at runtime by themes, such as this function in VS2012 Light theme that draws the document tab,

https://github.com/dockpanelsuite/dockpanelsuite/blob/master/WinFormsUI/ThemeVS2012Light/VS2012LightDockPaneStrip.cs#L1155

To achieve the effect you desired, it is very likely that you need to create your own theme.
