### ISSUE TITLE
VS2012 light theme doesn't redraw document tabs with OnMouseMove

### ISSUE THREAD

**Issue by antiduh** [dockpanelsuite/dockpanelsuite#365]
When using the VS 2012 light theme, tabs only get redrawn in response to a WM_MOUSEHOVER event, which has a noticable delay. If you constantly move your mouse over an inactive tab, it'll take 0.5 - 2 seconds for the tab to highlight, finally indicating that the tab is under the mouse.

Since the entire VS2012LightDockPaneStrip is a single control, the events OnMouseEnter and OnMouseLeave won't be much help to fix this, since if the mouse stays within the control (moving between tabs without leaving the control's area), the tabs don't repaint until WM_MOUSEHOVER fires which can be a while (especially if the mouse is never stationary).

A cheap fix is to take all of the code in VS2012LightDockPaneStrip.OnMouseHover, copy it to a new method, and then call that method from OnMouseHover and OnMouseMove. This will cause a lot of repainting, however, even if the active tab doesn't change (which is the complaint in https://github.com/dockpanelsuite/dockpanelsuite/issues/141). 

A better fix might be to always track enter/leave/move/hover on a per-tab basis, and redraw only the tab(s) that changed instead of the entire control, and only redraw when their state changes.

**Comment by antiduh** [comment]
Same problem occurs with the 2013 theme, probably for the same reason. You can really easily reproduce this in the sample by endlessly, quickly wiggling the mouse over the tabs - none of them will be highlighted (and thus show their close button) until you finally let the mouse be still over one tab.

**Comment by lextm** [comment]
Thanks for pointing out the issue. We welcome pull requests on such optimization.
