### ISSUE TITLE
dockpanel does't display icons correctly when the system text-size is 125%,

### ISSUE THREAD

**Issue by shenAwesome** [dockpanelsuite/dockpanelsuite#366]
![2016-05-31 18_14_13-display](https://cloud.githubusercontent.com/assets/1016216/15667891/ed97bdf2-275b-11e6-8156-657a587c281f.png)

![2016-05-31 18_13_36-docksample](https://cloud.githubusercontent.com/assets/1016216/15667893/f32824aa-275b-11e6-9e4a-24038deee7a3.png)

**Comment by shenAwesome** [comment]
2 problems I have when text-size is 125%: 
1) icons become rectangle instead of square (hover on icons if it's not obvious) 
2) the document & docked panels don't align anymore

**Comment by lextm** [comment]
Thanks for the report.

It seems that you are running the application on Windows 7. May I know what is the .NET Framework version installed? 

Similar to https://github.com/dockpanelsuite/dockpanelsuite/issues/330, you might have to run the latest .NET Framework release such as 4.6.1 to have all DPI related patches Microsoft produces.

If you can reproduce this issue with .NET Framework 4.6.1 on Windows 7 (with all latest updates), I might take a further look.

**Comment by lextm** [comment]
Closed as duplicate.
