### ISSUE TITLE
Add patch experiment controller mechanism

### ISSUE THREAD

**Issue by lextm** [dockpanelsuite/dockpanelsuite#369]
We have many patches with possible fixes to existing issues, but no good way to test them out with confidence.

Should merge the patches but govern with flags, so that users of this library can explicitly enable/disable them on demand.

Once they are tested well, we can move them out of patch experiment controller.

**Comment by lextm** [comment]
Will follow [.NET Framework's approach to support both environment variables and registry keys](https://github.com/Microsoft/dotnet/blob/master/docs/testing-with-ryujit.md). More information will be posted when I am ready.

**Comment by roken** [comment]
Notably that example is for the compiler and not the framework.  I'm very concerned about using the registry or environment variables as that adds a layer of nightmare to the deployment process for an application.

At worst it should use app.config for these settings; that is really the .NET approach.

**Comment by lextm** [comment]
I have added switches so that a patch can be enabled by,

* code
* app.config/web.config
* environment variables
* registry keys

Related unit test cases are also added.

Close via 619a036072c0c03426a843cbfa933c658dbcb7fa

**Comment by astrohart** [comment]
I am not sure what you mean...in the interest of documentation, can I ask if there would be a willingness to post an example?

And is there a mechanism to disable certain flags/switches for patches once a patch seems to work?

**Comment by lextm** [comment]
http://docs.dockpanelsuite.com/en/latest/tutorials/disabling-patches.html

This new article documents how a patch can be disabled. You can also refer to the latest commits in the master branch to see how it was implemented.
