### ISSUE TITLE
Document the Forms programtically

### ISSUE THREAD

**Issue by Nessi2410** [dockpanelsuite/dockpanelsuite#373]
Hello,

I want to dock some forms with equal widths and arranged as shown in the image. Please help me how to achieve  that.

In the image there is diagramatic representation of the output i require. consider each cell a new form

![dock](https://cloud.githubusercontent.com/assets/8386205/17807998/18d73476-662b-11e6-8849-9299178d79f0.png)

**Comment by lextm** [comment]
We documented how to put multiple dock contents in the same dock state in the official documentation,

http://docs.dockpanelsuite.com/en/latest/tutorials/basics.html#show-multiple-contents-in-the-same-dock-state

You can follow it to place your forms by manually calculating the percentage to pass to `Show` method with proper `DockAlignment` option.

**Comment by Nessi2410** [comment]
Thank you Lex,

I have checked that. But when i have Four windows. I first Document one window. and then use that pane for docking other windows. The Windows are not coming in equal Proportions.

PanelMain.Contents[1].DockHandler.Show(DockPanelMain, DockState.Document);
 
Other Windows as:

PanelMain.Contents[j].DockHandler.Show(PanelMain.Contents[1].DockHandler.Pane, DockAlignment.Right, 0.25);

**Comment by lextm** [comment]
It requires some mathematics than coding. To achieve equal widths, the first call should use 0.5 (1/2), while the second call should use 0.33 (1/3). If you want to call it one more time, you should then use 0.25 (1/4).

You cannot use a constant percentage every time, as that means a completely different layout effect.

**Comment by Nessi2410** [comment]
Hello lex, 
Tried your solution Still the results are not as expected.

**Comment by lextm** [comment]
Documents can be easily organized with the following code to achieve the layout,
```
DummyDoc doc1 = CreateNewDocument("Document1");
DummyDoc doc2 = CreateNewDocument("Document2");
DummyDoc doc3 = CreateNewDocument("Document3");
DummyDoc doc4 = CreateNewDocument("Document4");
DummyDoc doc5 = CreateNewDocument("Document5");
DummyDoc doc6 = CreateNewDocument("Document6");
DummyDoc doc7 = CreateNewDocument("Document7");
DummyDoc doc8 = CreateNewDocument("Document8");
DummyDoc doc9 = CreateNewDocument("Document9");

doc1.Show(dockPanel, DockState.Document);
doc4.Show(doc1.Pane, DockAlignment.Bottom, 0.66);
doc7.Show(doc4.Pane, DockAlignment.Bottom, 0.5);

doc2.Show(doc1.Pane, DockAlignment.Right, 0.66);
doc3.Show(doc2.Pane, DockAlignment.Right, 0.5);
doc5.Show(doc4.Pane, DockAlignment.Right, 0.66);
doc6.Show(doc5.Pane, DockAlignment.Right, 0.5);
doc8.Show(doc7.Pane, DockAlignment.Right, 0.66);
doc9.Show(doc8.Pane, DockAlignment.Right, 0.5);
```
It is just variation of the sample code in `MainForm.menuItemLayoutByCode_Click`.
