### ISSUE TITLE
SetButtonsPosition()

### ISSUE THREAD

**Issue by gmozhaev** [dockpanelsuite/dockpanelsuite#410]
not equal in VS2012DockPaneCaption.cs (also VS2013DockPaneCaption.cs) and VS2012LightDockPaneCaption.cs

**Comment by lextm** [comment]
Please make it clearer what you want to express.

**Comment by gmozhaev** [comment]
When theme was VS2012Light it was scaling for caption buttons. Now there is no scaling in VS2012/VS2013. Need copy code from old to new.

**Comment by lextm** [comment]
Is it related to DPI scaling? I see no need to scale button images if DPI is 100%.

**Comment by gmozhaev** [comment]
Yes, it is for DPI. It works in VS2005/VS2005MT, but changed in VS2012/VS2013.

**Comment by lextm** [comment]
Duplicate to #320 

I have to finish the theme related changes first, and then see how the patch can be improved. Will work on DPI support in Beta 2. Thanks.

**Comment by lextm** [comment]
Closed #320 and will not put more effort in this area.
