### ISSUE TITLE
Change dockpanel's Border width

### ISSUE THREAD

**Issue by poloab** [dockpanelsuite/dockpanelsuite#412]
Hi, the dockpanel suite is great and usefull, thank you for this.

I'd like to change the border width of de dockpanel that uses 2013, 2015 themes, or maybe is a padding propety, but cant`n find it. How can I do it?

In the linked image you can see what I mean:

![untitled1](https://cloud.githubusercontent.com/assets/5981254/18616341/ada8bb2c-7d7f-11e6-89a3-6faf584c8d9d.jpg)

Thanks.

**Comment by lextm** [comment]
Please check `Measures.DockPadding` and create your own theme.

**Comment by poloab** [comment]
Thank you, I found it. it is going better and better.
