### ISSUE TITLE
Customize color's theme

### ISSUE THREAD

**Issue by poloab** [dockpanelsuite/dockpanelsuite#413]
Hi one more time,

I am trying to change the color of 2013Darktheme but doesn't works.

This properties works and colors are changed:
vS2013DarkTheme1.ColorPalette.MainWindowActive.Background = Color.FromArgb(0x4F, 0x4F, 0x4F);
vS2013DarkTheme1.ColorPalette.TabSelectedActive.Background = Color.FromArgb(0x33, 0x33, 0x33);
vS2013DarkTheme1.ColorPalette.TabUnselectedHovered.Background = Color.FromArgb(0x73, 0x73, 0x73);
vS2013DarkTheme1.ColorPalette.TabSelectedInactive.Background = Color.FromArgb(0x9C, 0x9C, 0x9C);
vS2013DarkTheme1.ColorPalette.ToolWindowCaptionActive.Background = Color.FromArgb(0x33, 0x33, 0x33);

But this one does'nt works, colors are not changed :
vS2013DarkTheme1.ColorPalette.ToolWindowCaptionInactive.Background = Color.FromArgb(0x73, 0x73, 0x73);
vS2013DarkTheme1.ColorPalette.ToolWindowCaptionButtonActiveHovered.Background = Color.FromArgb(0x33, 0x33, 0x33);
vS2013DarkTheme1.ColorPalette.ToolWindowCaptionButtonInactiveHovered.Background = Color.FromArgb(0x33, 0x33, 0x33);
vS2013DarkTheme1.ColorPalette.ToolWindowCaptionButtonPressed.Background = Color.Black;
vS2013DarkTheme1.ColorPalette.TabButtonSelectedActiveHovered.Border = Color.FromArgb(0xFC, 0xFF, 0x01);
vS2013DarkTheme1.ColorPalette.TabButtonSelectedActiveHovered.Glyph = Color.FromArgb(0xFC, 0xFF, 0x01);
vS2013DarkTheme1.ColorPalette.TabButtonSelectedActivePressed.Background = Color.FromArgb(0xFF, 0x01, 0x31);
vS2013DarkTheme1.ColorPalette.TabButtonSelectedInactiveHovered.Background = Color.FromArgb(0x01, 0x01, 0xFF);
vS2013DarkTheme1.ColorPalette.TabButtonSelectedInactivePressed.Background = Color.FromArgb(0x01, 0xFF, 0x25);
vS2013DarkTheme1.ColorPalette.TabButtonUnselectedTabHoveredButtonHovered.Background = Color.FromArgb(0x31, 0x08, 0xFF);
vS2013DarkTheme1.ColorPalette.TabButtonUnselectedTabHoveredButtonPressed.Background = Color.FromArgb(0xFF, 0x48, 0x00);

dockPanel.Theme = vS2013DarkTheme1;

Or maybe this is not how it have to be done?

(colors are only for test only)

**Comment by lextm** [comment]
Please start a new theme from a new .vstheme file. The Color Theme Manager for Visual Studio from Microsoft gives you a visual way to generate such files.
