### ISSUE TITLE
AutoHidePortion for DockContent not applied properly after load

### ISSUE THREAD

**Issue by joelbyren** [dockpanelsuite/dockpanelsuite#414]
Set a layout where two panels are docked to the right (bug works for all docks, but this is what I primarily tested with) and have them auto hide. Resize the docked panels so they have different size. Save the layout, and verify the contents is correct (e.g. AutoHidePortion="0.13"). Load the layout, and somehow the value is not used! Both panels will have the same size, which seem to be propegated from the value set for the DockHandler.

When the DockPanel.Persistor.cs unloads all properties, the AutoHidePortion property is loaded and set (DockPanel.Persistor.cs:603) but somehow this value is then overwritten later on.

I have tested to capture the value at line 603 (when deserializing the IDockContent) and applying it again directly before calling dockPanel.ResumeLayout(true, true) on line 730, and then it works!

**Comment by lextm** [comment]
Thanks for reporting it. I will try to reproduce it first.

**Comment by joelbyren** [comment]
FYI, the issue is in ResetAutoHidePortion, being called from SetDockState, which in turn is called from IsHidden.set. By simply bypassing the line "m_autoHidePortion = value;" inside AutoHidePortion.set (in debugger) I got the correct behavior.
Not familiar enough with the code yet to come up with anything other than some kind of weird workaround (e.g. set DockContentHandler in some particular state to prevent changing the AutoHidePortion property at the wrong time).

**Comment by joelbyren** [comment]
Should this issue be closed?
