### ISSUE TITLE
DockContent with Mono on Linux

### ISSUE THREAD

**Issue by bjsrpt** [dockpanelsuite/dockpanelsuite#418]
I tried a DockContent experiment with a richbox control on Windows, which works nicely.
But  when i move the program to Linux and run it with Mono, there is no Control shows.
![sample on linux](https://cloud.githubusercontent.com/assets/8304498/18818681/171e3d0e-83dc-11e6-96ea-9fe4b1ebfa72.png)

i checked the Control list . the richbox(or other controls) exists.
Does anyone have a solution for this?

Thanks

**Comment by lextm** [comment]
Due to issues such as #273, Mono support is as it is and not more active development. PR is welcome though.
