### ISSUE TITLE
Documenting the form in tabpages makes blank

### ISSUE THREAD

**Issue by Nessi2410** [dockpanelsuite/dockpanelsuite#419]
Hello,

I have used dockpanel in the tabpages of tabcontol. But when i document the form in tabpages it becomes blank. Docking Right left works proper.

**Comment by lextm** [comment]
Could not reproduce this with HEAD on master branch.

**Comment by lextm** [comment]
[WindowsFormsApplication1.zip](https://github.com/dockpanelsuite/dockpanelsuite/files/494341/WindowsFormsApplication1.zip)

Attached a sample project that I used, which could not show the issue you described.

**Comment by Nessi2410** [comment]
Ok.. Thanks Lex.. My Document Style was causing the issue
