### ISSUE TITLE
TabPageContextMenuStrip not working on newer themes

### ISSUE THREAD

**Issue by joelbyren** [dockpanelsuite/dockpanelsuite#421]
When trying out the TabPageContextMenuStrip I was surprised that it only seemed to work in VS2005 or VS2003 theme.
Digging through the code I was quite surprised to see that the VS20xxDockPaneStrip classes was calling base.OnMouseLeave(e) from the overridden OnMouseUp [event] method. Testing to change this to the proper base.OnMouseUp(e), it worked on the other themes as well.

Note that neither VS2003 nor VS2005 theme is overriding OnMouseUp, which is probably why it works here.

**Comment by lextm** [comment]
Thanks for the reminder. Can you send us a pull request?
