### ISSUE TITLE
Cannot drag from auto hide window

### ISSUE THREAD

**Issue by lextm** [dockpanelsuite/dockpanelsuite#422]
Visual Studio 2012 and above themes should allow dock contents to be dragged from auto hide window to match VS behavior.

The current workaround is to disable auto-hide by clicking the Dock button, and then drag the pane.

**Comment by joelbyren** [comment]
It is the same for VS2003 and VS2005 themes, as far as I can see... Neither allows the auto-hide window (either the title bar or the "button") to be start a drag.

**Comment by zii-dmg** [comment]
Commenting just one line with [IsDockStateAutoHide check](https://github.com/dockpanelsuite/dockpanelsuite/blob/master/WinFormsUI/Docking/DockPaneCaptionBase.cs#L58) allows to drag.

**Comment by lextm** [comment]
@zii-dmg you can send a pull request.

**Comment by zii-dmg** [comment]
#446

**Comment by lextm** [comment]
@joelbyren The scope of this issue is to cover only new themes. 

I think the behavior in old themes like VS2003 and VS2005 are desired so as to match Visual Studio's behavior, and personally I don't want to break that.

**Comment by joelbyren** [comment]
@lextm oh, okay! I was mainly pointing it out to help narrow down where the error was.

**Comment by lextm** [comment]
@joelbyren Thanks. The cause has been found and now the question is how to address it in a good way via the pull request.

**Comment by lextm** [comment]
Closed via #446
