### ISSUE TITLE
Mouse move over DockPaneStrip

### ISSUE THREAD

**Issue by vlam13** [dockpanelsuite/dockpanelsuite#423]
When you move mouse over DockPaneStrip without stops then tabs are not updated when mouse is over them(not highlighted). 
I fixed this issue by moving DockPanelStrip.MouseHover handler to DockPanelStrip.MouseMove.

**Comment by lextm** [comment]
Thanks for reporting this. Can you send a pull request?

**Comment by vlam13** [comment]
Seems that it was already done - Commit ea64fe8a

**Comment by lextm** [comment]
Thanks for the confirmation. Duplicate to #365
