### ISSUE TITLE
DockPanel.ActiveContent [and DockPanel.ActiveDocument] not working on Mono, giving no TabPageContextMenu[Strip] on FloatWindow

### ISSUE THREAD

**Issue by joelbyren** [dockpanelsuite/dockpanelsuite#425]
In Windows, the ActiveContent and ActiveDocument properties on DockPanel are working as expected, mostly ActiveContent is unset, then set, and then ActiveDocument is changed (if switching between document tabs).
In Mono, the ActiveContent property is never changed it seems; tracking ActiveContentChanged gives nothing and trying to use ActiveContent is also not working.

This issue was found when trying to work around the fact that TabPageContextMenu[Strip] is not working (I was trying to manually add a MenuStrip in Mono, allowing me to re-dock after I had used the context menu to Float it)

I think it is related to the focus manager generally being bypassed by Win32Helper.IsRunningOnMon checks, so this might be a big issue to solve?

**Comment by joelbyren** [comment]
With some further digging I found that FloatWindow.cs is never even calling DockPane.ShowTabPageContextMenu on Mono, since it rely on SendMessage(WM_NCHITTEST) to know if it is the right thing to do.

**Comment by lextm** [comment]
Duplicate to Mono related issues such as #273
