### ISSUE TITLE
Resize panes does not work on Mono (SuSE 42.1)

### ISSUE THREAD

**Issue by joelbyren** [dockpanelsuite/dockpanelsuite#430]
I'm currently having problems with resizing panels on Mono/Linux:
1. The "drop" seems broken, after dragging the "resize bar" the panes are NOT resized
2. The "resize bar" lingers (I've seen this noted elsewhere as well and do not want to claim credit for it; I just want to make sure it gets fixed)

I already have a fix for it (one line for each fix) but I wanted an issue number to track it with.

**Comment by lextm** [comment]
This can be made a pull request.

**Comment by joelbyren** [comment]
Pull request created! I was having problems creating more than one pull request at a time, so I waited with  this one until the one I already had was merged.

**Comment by lextm** [comment]
You should create a new branch on your fork every time you want to add something new. Then a pull request can be created from that new branch and you can easily manage multiple pull requests by having multiple branches on your fork.

**Comment by joelbyren** [comment]
Ah, so *that's* how I should do it... Thanks, that will help! I'll probably find more things, especially for Linux/Mono!

**Comment by joelbyren** [comment]
This issue was solved by pull request #431, right?
