### ISSUE TITLE
Themes do not apply to ToolStrip in Mono

### ISSUE THREAD

**Issue by joelbyren** [dockpanelsuite/dockpanelsuite#432]
When applying a theme (ANY theme) in Mono, the tool strips are not setting the Renderer on its children, making them crash in OnPaintBackground due to Renderer being null.

A work-around is already in place, pull request coming...

**Comment by joelbyren** [comment]
Pull request coming as soon as #431 is in place (currently "in progress")

**Comment by lextm** [comment]
Related to #415 . The renderer comes from another open source project at CodePlex, so it might not be in perfect state yet. Any pull request is welcome.

**Comment by joelbyren** [comment]
I assume you set it as an Enhancement because it is only a bug in Mono?

**Comment by lextm** [comment]
Yes. It is a dependency bug, which we in most cases won't step up to fix. Thanks for the patch, as it shows a good workaround.
