### ISSUE TITLE
VS2015 theme forces "glass" for menu strips

### ISSUE THREAD

**Issue by joelbyren** [dockpanelsuite/dockpanelsuite#436]
When rendering menus with VS2015 theme a "glass" effect is added unconditionally. Since VS2015 actually does not show this in all cases, it should be made optional (keeping it set by default, so it won't effect VS2013 theme).

Either have this set by VS2013 by default and unset by VS2015 by default, or possible make it changeable for VS2015 theme?

**Comment by joelbyren** [comment]
Pull request coming as soon as #431 is in place (currently "in progress")

**Comment by lextm** [comment]
Related to #415 . The renderer comes from another open source project at CodePlex, so it might not be in perfect state yet. Any pull request is welcome.

**Comment by joelbyren** [comment]
Perfect! As stated, because I messed up I need pull request #431 (which was created to from "master" branch) to be merged (or rejected/closed) before I can create more... I now know how to do it properly (one branch per pull request) so for my other issues I'll create the pull requests in parallel!

**Comment by lextm** [comment]
Fixed by #440
