### ISSUE TITLE
Cursor (or) Control Not Focused on Disabled Dock Content (Form) Tab Selecting.

### ISSUE THREAD

**Issue by Baventhan** [dockpanelsuite/dockpanelsuite#443]
Dock Content Form is Disabled (Enable=False) On Tab. Select the Disabled Dock Content (Form) Tab, But Cursor (or) Control Not Focus the Selected Tab. Cursor (or) Control Focused on Existed Tab. Kindly Solve this Issue.

**Comment by lextm** [comment]
You'd better provide more info, or nobody can easily understand what you did and what is the problem.
