### ISSUE TITLE
Error	1	Invalid token '=' in class, struct, or interface member declaration	dockpanelsuite-Release_2.11_Beta1

### ISSUE THREAD

**Issue by bobper** [dockpanelsuite/dockpanelsuite#444]
Hi
I working on windows 10
Microsoft visual studio Ultimate 2013  version 12.0.21005.1 REL
Try 1: 
Install form source code : 
Open a project add this solution " Add WinFormsUI.csproj in WinFormsUI directory to your solution.
"  
And when i build solution give these errors 
one of them : 
Error	1	Invalid token '=' in class, struct, or interface member declaration	H:\project\dockpanelsuite-Release_2.11_Beta1\dockpanelsuite-Release_2.11_Beta1\WinFormsUI\Docking\ThemeBase.cs	21	43	WinFormsUI
and many other Errors like this
when i clicking on this error DockPanelSkin.cs opened and  go to this line 
Line 175:         public AutoHideStripPalette AutoHideStripDefault { get; } = new AutoHideStripPalette();
Try2 : Install with all.bat 
Run all.bat and give 75 errors  one of them : 
Docking\DockPanelSkin.cs(175,73): error CS1520: Method must have a return type [H:\project\dockpanelsuite-Rele
ase_2.11_Beta1\dockpanelsuite-Release_2.11_Beta1\WinFormsUI\WinFormsUI.csproj]

**Comment by lextm** [comment]
Thanks for reporting this and I have just updated the related documentation paragraphs.

The steps require you to use latest Visual Studio such as VS2015. If you cannot upgrade, please switch to the NuGet approach.
