### ISSUE TITLE
Dark Theme tool strips do not render correctly

### ISSUE THREAD

**Issue by aswanee** [dockpanelsuite/dockpanelsuite#450]
All menu items in Command Bar 
the CommandBarTextActive don't effected at all  when change its color . also it take dark color so not appear in the menu clearly
![dock](https://cloud.githubusercontent.com/assets/348178/20649890/f9b3b83a-b4d1-11e6-8c15-989f5c72bfb6.png)

**Comment by Progress1** [comment]
The same on window list 
![blacktheme](https://cloud.githubusercontent.com/assets/10151485/20649904/3024328a-b4ca-11e6-950b-e0a3968f6ba2.png)

**Comment by lextm** [comment]
Related to #415

**Comment by Progress1** [comment]
Checked 2.12 RC1 and looks fine. One small thing on VS 2015 Black theme, can be Checkboxes little bit lighter (not black) see pic for comparing. 
 
![check](https://cloud.githubusercontent.com/assets/10151485/21082654/3cfeb3c4-bfe0-11e6-9ebc-1488258eaac4.png)

**Comment by lextm** [comment]
That still falls under #415 and is not yet finished.
