### ISSUE TITLE
Themes xml configuration size/complexity

### ISSUE THREAD

**Issue by Progress1** [dockpanelsuite/dockpanelsuite#454]
This is just a question/idea ... Why we have so "big' theme configuration files?
e.g  vs2015blue.vstheme has 312kb ... for 3 themes has ThemeVS2015.dll  1Mb pure XML inside as resource...
Lets look what is inside XML. There is configuration for all Visual Studio windows (sections) like: SQL Results - Grid, Package Manager Console, Data Source Designer, WebClient Diagnostic Tools, SharePointTools .... But these data are for us **totally useless and just take space and time by processing** ...

Maybe if we can extract only colors that we need, and change little bit theming, size of ThemeVS2015.dll can be reduced from 1,5mb to 500kb ... This will also a lot of help other people to create new schemes, because they no need process 2312 different colors (vs2015blue), but just few that we exactly need.

It can also help by finding issues with theming colors like now exists in black theme ...

**Comment by lextm** [comment]
I rather leave the vstheme files untouched, but we might embed compressed versions to save disk space, and decompress them at runtime, as enabling ease of new theme development is far more important.

Without Visual Studio Color Theme Editor it would never be easy to create new themes. So your suggestion of "extracting only colors that we need" does not seem to be useful to me. If you never used that tool before, you might check it out, 

https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.VisualStudio2015ColorThemeEditor

**To keep compatible with such a valuable tool, leaving the vstheme files untouched is desirable.**

I am not sure what is the "issues with theming colors like now exists in black theme". The shipped dark themes use exactly the colors from Visual Studio vstheme files. You might describe more on that.

**Comment by Progress1** [comment]
i mean Issue #450 ... i have quick look what can do problems here, because i use only dark themes ...

I know Visual Studio 2015 Color Theme Editor and I understand need to use, it's great tool ...
I was thinking use just subset of styles that we use. (this can be problematic maybe)
If you look in Theme Editor you have "Common Elements" and "All Elemets". I think maybe Common Elements are just our styles that we need. We don't care about e.g. JavaScriptPerformanceTool MenuBorder colors in VS :D This will enormously simplify our themes that we use.

Question is: Can we separate only our colors and do it with minimal work and errors without future compatibility problems (next VS versions)

**Comment by lextm** [comment]
You should refer to #415 as it is the tool strip renderer who does not give the flexibility to override text color (or I failed to find that). I think a community member should step in and fill the gap while I am busy on other things. I left enough information for him/her to get started.

I am not sure what might happen if Color Theme Editor opens a "simplified" vstheme file. So to keep things easier for compatibility, I said above that such files should be kept untouched. Compression can save significant space, which I think we can address in 2.11 update release.

I rather not assume or plan for any "future compatibility". Each VS release does change the themes (sometimes just a few colors, but many visual elements in other cases). So a design approach for DPS is to just match the existing ones, and adapt to new releases when they are there for investigation.

**Comment by lextm** [comment]
Starting from 2.12 release, .gz files are shipped which are usually 1/10 of original size of .vstheme files. As stated above, no intention to further change the .vstheme files. The dark theme tool strip rendering problem will be addressed in other issues.
