### ISSUE TITLE
 How to access variables and Custom methods of Tool Window from Child 

### ISSUE THREAD

**Issue by Media-Hub** [dockpanelsuite/dockpanelsuite#455]
Have a look at my Question on StackOverflow
[http://stackoverflow.com/questions/41048102/dockpanel-suite-c-sharp-how-to-access-variables-and-custom-methods-of-tool-w](url)

I am not able to access methods and variables of ToolWindow from child window
but i can access active child form window methods and methods( means i can access others too). now i want to do the reverse.

**Comment by Media-Hub** [comment]
this  is similar to [https://sourceforge.net/p/dockpanelsuite/discussion/402316/thread/46d1b515/](url)

**Comment by lextm** [comment]
Even if you don't use DPS but WinForms MDI you might need to pass data among firms. So, this question is so general and you have tons of possible approaches.

Just to name a few,

* Mediator pattern,
* IoC/DI container,
* Service Provider pattern.

Close it now.

**Comment by Media-Hub** [comment]
Sorry, that was my mistake, Solved my problem. few hours back. Thanks.  there was a small mistake in my coding, now i resolved it.
