### ISSUE TITLE
CallbackOnCollectedDelegate MDA at end of drag

### ISSUE THREAD

**Issue by billybednar** [dockpanelsuite/dockpanelsuite#456]
I've run into an intermittent issue when docking windows. Releasing a panel that I've been dragging sometimes triggers the following MDA within `DockPanel.DragHandlerBase.WndProc`'s call to the base `WndProc` method. 

> **Managed Debugging Assistant 'CallbackOnCollectedDelegate' :** 'A callback was made on a garbage collected delegate of type 'System.Windows.Forms!System.Windows.Forms.NativeMethods+WndProc::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.'

You can make it happen every time by inserting `System.GC.Collect()` right before the call to `base.WndProc`. You won't see the MDA  when not running in the debugger since it isn't enabled by default in that case, but the underlying problem is still there.

The root cause seems to be calling `base.WndProc` after `EndDrag`.  `EndDrag` always calls `NativeWindow.ReleaseHandle` to stop the `DragHandlerBase` from wrapping the content being dragged. This sets the `Handle` property to 0 and [MSDN](https://msdn.microsoft.com/en-us/library/system.windows.forms.nativewindow.defwndproc(v=vs.110).aspx) says that calling `NativeWindow.DefWndProc`, which is what the base call does, is an error.

#401 made it much easier to trigger this by moving the most common `EndDrag` into `WndProc`, but there was already one there before.

I think the best solution is to add an `if (Handle != IntPtr.Zero)` right before the call to `base.WndProc`. It avoids changing the return value of `OnPreFilterMessage`, which may matter if we need to go back to using a message filter, and avoids adding an unnecessary flag to the class.

```c#
partial class DockPanel
{
    // ...
    public abstract class DragHandlerBase : NativeWindow, IMessageFilter
    {
        protected virtual bool OnPreFilterMessage(ref Message m)
        {
            if (m.Msg == (int)Win32.Msgs.WM_MOUSEMOVE)
                OnDragging();
            else if (m.Msg == (int)Win32.Msgs.WM_LBUTTONUP)
                EndDrag(false);
            else if (m.Msg == (int)Win32.Msgs.WM_CAPTURECHANGED)
                EndDrag(!Win32Helper.IsRunningOnMono);
            else if (m.Msg == (int)Win32.Msgs.WM_KEYDOWN && (int)m.WParam == (int)Keys.Escape)
                EndDrag(true);

            return false;
        }
        // ...
        protected sealed override void WndProc(ref Message m)
        {
            //Manually pre-filter message, rather than using
            //Application.AddMessageFilter(this).  This fixes
            //the docker control for ActiveX objects
            this.OnPreFilterMessage(ref m);

            if (m.Msg == (int)Win32.Msgs.WM_CANCELMODE || m.Msg == (int)Win32.Msgs.WM_CAPTURECHANGED)
                EndDrag(true);

            base.WndProc(ref m); // MDA within here
        }
    }
    // ...
}
```

**Comment by lextm** [comment]
Should be fixed by disabling the patch from #401. Please test the master after this commit, 99b77161721a63f4527bceafa4870bba5aa1540c

**Comment by billybednar** [comment]
That does fix my issue for when the ActiveX option is disabled. I think we still need an `if (Handle != IntPtr.Zero)` before the call to `base.WndProc` to fix it when the ActiveX option is on or when we end up in the WM_CANCELMODE/WM_CAPTURECHANGED case that's directly in `DragHandlerBase.WndProc`. One way to trigger the latter is if your program opens a message box while the user is dragging a panel (see #460 regarding a potential issue with that), but for some reason that case doesn't trigger the MDA. Unfortunately Visual Studio is acting up right now and I can't step into the framework to figure out why, but I think it's still incorrect to make the base call.

**Comment by lextm** [comment]
@billybednar You can send a pull request.

**Comment by lextm** [comment]
Closed temporarily and wait for a better patch to replace #401.
