### ISSUE TITLE
New margin is created betwen main window and content when new VS Theme ia applied

### ISSUE THREAD

**Issue by Progress1** [dockpanelsuite/dockpanelsuite#458]
On old native 2005 theme doesn't exist margin between main window and content. When you applied e.g. 2015 theme a new margin is created. Maybe a new theme should copy original margin? Or maybe can i influence this somehow? Can be see also on DockSample. See pic 2005/2015

![gap1](https://cloud.githubusercontent.com/assets/10151485/21082862/a42cec1a-bfe4-11e6-83c3-3216a048d18e.png)

**Comment by lextm** [comment]
This is intentional to match the VS look and feel.

**Comment by Progress1** [comment]
Nice, i will play with that ... Thank you!
