### ISSUE TITLE
DockContent event DockStateChanged is not enabled.

### ISSUE THREAD

**Issue by bhaktria** [dockpanelsuite/dockpanelsuite#459]
It seems that DockContent event DockStateChanged is not enabled. The code has lines below. If this is by design, then the related methods probably should be private.  If where building from source I would just comment out line with EnableFontInheritanceFix test. For now I changed my code to use  doc.DockHandler.DockStateChanged instead of doc.DockStateChanged.

       public DockContent()
        {
            m_dockHandler = new DockContentHandler(this, new GetPersistStringCallback(GetPersistString));
            if (PatchController.EnableFontInheritanceFix != true)
            {
                m_dockHandler.DockStateChanged += new EventHandler(DockHandler_DockStateChanged);
            }
        }

**Comment by lextm** [comment]
It seems to be a bug in 2.11 release. Will do more investigation.
