### ISSUE TITLE
切换皮肤未判断相同VS版本的样式

### ISSUE THREAD

**Issue by chencun** [dockpanelsuite/dockpanelsuite#462]
囧，只判断了VS的版本，导致相同的VS版本的不同样式，会调用默认的样式

**Comment by chencun** [comment]
目标文件：dockpanelsuite/WinFormsUI/Docking/VisualStudioToolStripExtender.cs
修改后的SetStyle代码，修改了判断逻辑，增加了一个保存样式主题名称的字段
`   private string ThemeName;
        public void SetStyle(ToolStrip strip, VsVersion version, ThemeBase theme)
        {

            var apply = false;
            ToolStripProperties properties = null;

            if (!strips.ContainsKey(strip))
            {
                properties = new ToolStripProperties(strip) { VsVersion = version };
                strips.Add(strip, properties);
                apply = true;
            }
            else
            {
                properties = strips[strip];
                if (properties.VsVersion == version && ThemeName == theme.ToString())
                {
                    apply = true;
                }
            }

            if (apply)
            {
                if (theme == null)
                    strip.Renderer = DefaultRenderer;
                else
                {
                    theme.ApplyTo(strip);
                    ThemeName = theme.ToString();
                }
                properties.VsVersion = version;
            }
        }`

**Comment by lextm** [comment]
Duplicate to #448.
