### ISSUE TITLE
DockState.Document设置的CloseButtonVisible 无效

### ISSUE THREAD

**Issue by chencun** [dockpanelsuite/dockpanelsuite#463]
通过 doc1.Show(dockPanel, DockState.Document) 加入的  DockContent

其设置的  CloseButtonVisible = true; 无效，关闭按钮依然是可见的。
-
另外，我反馈的那个 [切换皮肤未判断相同VS版本的样式](https://github.com/dockpanelsuite/dockpanelsuite/issues/462)

虽然已经关闭了，但是，这个问题还是没有解决呀。。看了新版的 2.12的 SetStyle代码，没有任何的变化

把反馈理解错误了？应该不会呀，我都提供了初步的修正代码了。。
-
点击 菜单的 Tool 子菜单 切换 Schema: VS2013 Light，Schema: VS2013 Blue，Schema: VS2013 Dark

可以发现，已经SetStyle 的mainMenu，toolBar，statusBar 不会应用，而是使用默认的皮肤

必须，选择一个其他的VS版本，这个才会生效，比如，当前是 Schema: VS2013 Blue

我想要，Schema: VS2013 Dark ，直接点击时，mainMenu，toolBar，statusBar 是默认皮肤

我必须，要点击 Schema: VS2015 Dark   （或其他非2013的VS版本），再点击Schema: VS2013 Dark

这时候，mainMenu，toolBar，statusBar 才会应用 Schema: VS2013 Dark 的皮肤。

最后再说下， 发布的 2.12 没有修改 AssemblyInfo 信息，依然是 2.11
-

**Comment by lextm** [comment]
First, please split different issues to their individual pages so that we can track them down one by one.

Second, it is tradition to use English for technical discussions at GitHub or any other international sites. Please avoid to use a localized language.
