### ISSUE TITLE
Schema :When the  Vs version at the same time will using the default values

### ISSUE THREAD

**Issue by chencun** [dockpanelsuite/dockpanelsuite#465]
Run the example

The default Schema  is VS2013 Blue

When I switch to the VS2013 Dark

it don't work because the vs version is same,so vsToolStripExtender1.SetStyle Get the default value.

At this time,mainMenu，toolBar，statusBar Use the default skin,Is not VS2013 Blue  or VS2013 Dark

**Comment by lextm** [comment]
I believe it is duplicate to #462 which was in Chinese.

Your proposed fix in #462 does not look simple enough. Ideally the tool strips should be attached to `ThemeBase` by calling `ApplyTo(ToolStrip)` method. Of course that requires more lines to be touched.
