### ISSUE TITLE
How to fill the layout window with Dockpane?

### ISSUE THREAD

**Issue by xuecat** [dockpanelsuite/dockpanelsuite#469]
I have saw the `Demo.exe`, There are always left some space after layout.
I want the dock-pane window fill the layout window. Like wpf's `Dockpane`.

So, Are you get my means?
Please,Give me some advises.
Thanks!!

**Comment by lextm** [comment]
Please paste a screen shot and then mark what is the space you don't want.

**Comment by xuecat** [comment]
Before:
![2](https://cloud.githubusercontent.com/assets/5563220/22230754/55450b20-e21a-11e6-8f4a-2caa29f8a06b.PNG)

After:
![1](https://cloud.githubusercontent.com/assets/5563220/22230756/5f223d20-e21a-11e6-8e21-d4f608a248ac.PNG)

**Comment by lextm** [comment]
I took a closer look and the highlighted blank space is expected.

The docking layout can be understood as below,

1. You have no document opened.
2. You docked Toolbox and Solution Explorer on the top side and dragged them side by side.
3. You docked Properties on the left side.

Then it is desired to show a blank space, as that area is reserved for the documents. If you use File | New to open any document, it would be filled.

**Comment by xuecat** [comment]
My means is remove the DocumentWindow's area.

I have try added this, but it not work.
![capture](https://cloud.githubusercontent.com/assets/5563220/22681645/4a572c2c-ed49-11e6-8869-47b435509b84.PNG)

**Comment by lextm** [comment]
@xuecat no plan to support such a mode. All designs require a visible document area.

**Comment by xuecat** [comment]
Got it. Thanks so much!!
