### ISSUE TITLE
NullReferenceException in VS2012SplitterControl.OnPaint

### ISSUE THREAD

**Issue by antiduh** [dockpanelsuite/dockpanelsuite#470]
VS2012SplitterControl does not always initialize _foregroundBrush. If the control is created and OnPaint fires before OnSizeChanged, _foregroundBrush will be null.

The code has to recreate _foregroundBrush whenever it resizes, so that the gradient get set correctly. However, it seems to be relying on that for initialization.

Here's the constructor, where its initialization is absent:

        public VS2012SplitterControl(DockPane pane)
            : base(pane)
        {
            _horizontalBrush = pane.DockPanel.Theme.PaintingService.GetBrush(pane.DockPanel.Theme.ColorPalette.TabSelectedInactive.Background);
            _backgroundBrush = pane.DockPanel.Theme.PaintingService.GetBrush(pane.DockPanel.Theme.ColorPalette.MainWindowActive.Background);
            _verticalSurroundColors = new[]
            {
                pane.DockPanel.Theme.ColorPalette.MainWindowActive.Background
            };
            SplitterSize = pane.DockPanel.Theme.Measures.SplitterSize;
        }

Here's the only place it's assigned:

        protected override void OnSizeChanged(EventArgs e)
        {
            base.OnSizeChanged(e);
            Rectangle rect = ClientRectangle;
            if (rect.Width <= 0 || rect.Height <= 0)
                return;

            if (Alignment != DockAlignment.Left && Alignment != DockAlignment.Right)
                return;

            _foregroundBrush?.Dispose();
            using (var path = new GraphicsPath())
            {
                path.AddRectangle(rect);
                _foregroundBrush = new PathGradientBrush(path)
                {
                    CenterColor = _horizontalBrush.Color,
                    SurroundColors = _verticalSurroundColors
                };
            }
        }

This is reproducible with the following steps:

* Create a set of document tabs in the center of the master panel.
* Create two tool window tabs, docked together to the right of the master panel.
* Drag the tool window so that they become docked as document tabs to the right of the existing document tabs.
* Exception and the UI shows the red box with x where the splitter should be.

Video demonstrating bug available here: https://www.antiduh.com/Dockpanel_bug.mp4

**Comment by antiduh** [comment]
Cause:

* Alignment is initially set to DockAlignment.Bottom
* SplitterControlBase.OnSizeChanged() fires
* VS2012SplitterControl.OnSizeChanged() override sees that Alignment is set to Bottom, skips initializing _foregroundColor
* Alignment is set to Right. Nothing informs VS2012SplitterControl that alignment changed.
* OnPaint fires with _foregroundColor null
* Exception

**Comment by antiduh** [comment]
Cheap fix:

Extract from OnSizeChanged the code that initializes _foregroundBrush. Invoke from OnSizeChanged; and in OnPaint if _foregroundBrush is still null.

--- VS2012SplitterControl_old.cs	Thu Jan 12 14:13:00 2017
+++ VS2012SplitterControl.cs	Tue Jan 24 15:29:33 2017
@@ -38 +38,8 @@ namespace WeifenLuo.WinFormsUI.Docking
-
+
+            MakeForegroundBrush( rect );
+        }
+
+        private void MakeForegroundBrush( Rectangle rect )
+        {
+            Debug.WriteLine( "Made foregroundBrush" );
+
@@ -48,3 +55,3 @@ namespace WeifenLuo.WinFormsUI.Docking
-            }
-        }
-
+            }
+        }
+
@@ -67 +74 @@ namespace WeifenLuo.WinFormsUI.Docking
-                return;
+                return;
@@ -73 +80,4 @@ namespace WeifenLuo.WinFormsUI.Docking
-                    {
+                    {
+                        if( _foregroundBrush == null )
+                            MakeForegroundBrush( rect );
+

**Comment by antiduh** [comment]
Better fix:

Add a new method to SplitterControlBase - OnAlignmentChanged. Invoke from bottom of set_Alignment.

VS2012SplitterControl overrides OnAlignmentChanged, and invokes MakeForegroundBrush(). 

Now OnPaint doesn't need the conditional that's used in the above cheap fix.

**Comment by lextm** [comment]
Is it possible to simply fix it with
```
        public VS2012SplitterControl(DockPane pane)
            : base(pane)
        {
            _horizontalBrush = pane.DockPanel.Theme.PaintingService.GetBrush(pane.DockPanel.Theme.ColorPalette.TabSelectedInactive.Background);
            _backgroundBrush = pane.DockPanel.Theme.PaintingService.GetBrush(pane.DockPanel.Theme.ColorPalette.MainWindowActive.Background);
            _verticalSurroundColors = new[]
            {
                pane.DockPanel.Theme.ColorPalette.MainWindowActive.Background
            };
            SplitterSize = pane.DockPanel.Theme.Measures.SplitterSize;
            OnSizeChanged(EventArgs.Empty);
        }
```

**Comment by lextm** [comment]
I just did a few experiments, and I think the cheap fix is enough (as this is only an issue related to VS2012 themes).

Can you send a pull request?

**Comment by antiduh** [comment]
Gladly.

**Comment by lextm** [comment]
@antiduh the patch has been scheduled for the next release, 2.13, on Feb 14. So please try to send the pull request a few days before that deadline. Thanks.
