### ISSUE TITLE
DockPanel Suite Contents of WinForm Read

### ISSUE THREAD

**Issue by Mattes80** [dockpanelsuite/dockpanelsuite#471]
Hello

How can I retrieve the contents of a WinForm where loaded in DockPanel?

I have the WinForm loaded in DockPanel Suite

VB.NET source code

         Dim Formstart As New Form2
         Formstart.Show (DockPanel1, DockState.Document)

Now I would like to load with another WinForm synonymous in the DockPanel1 the content of a text box of Form2.
Unfortunately, I do not get the content

I tried it so but unfortunately it does not work.
VB.NET source code

            Label1.text = form2.textbox1.text

If the shapes do not load in DockPanel Suite then go.

How to solve?

**Comment by lextm** [comment]
With or without DockPanel Suite, it would be your full responsibility to query data across forms/user controls, and it has been discussed too many times over the internet. Thus, try to use Google to find the answers please.
