### ISSUE TITLE
Problem with _DocumentStripGapTop

### ISSUE THREAD

**Issue by vlam13** [dockpanelsuite/dockpanelsuite#473]
Is it known issue that if you set _DocumentStripGapTop or _DocumentStripGapBottom some value bigger then 0 the tabs height is calculated wrong and grows each time when user switch between tabs? I think it occurs only for VS2013 style.

**Comment by lextm** [comment]
Private items are not designed to be exposed. If you do want to change them, you have to fully understand the code and address any issue on your own.
