### ISSUE TITLE
Issue - Does not run under OSX

### ISSUE THREAD

**Issue by arajar** [dockpanelsuite/dockpanelsuite#474]
Does not run under OSX.
I tried compiling on Windows and then running the sample app with mono on a mac without success, I always get these exceptions:

> 
> Unhandled Exception:
> System.NotImplementedException: The method or operation is not implemented.
>   at System.Windows.Forms.XplatUICarbon.SetClipRegion (System.IntPtr hwnd, System.Drawing.Region region) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.XplatUI.SetClipRegion (System.IntPtr handle, System.Drawing.Region region) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Control.CreateHandle () [0x00097] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Control.CreateControl () [0x0004b] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control:CreateControl ()
>   at System.Windows.Forms.Control.CreateControl () [0x00090] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control:CreateControl ()
>   at System.Windows.Forms.Control.CreateControl () [0x00090] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Control.SetVisibleCore (System.Boolean value) [0x00043] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Form.SetVisibleCore (System.Boolean value) [0x0007b] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Control.set_Visible (System.Boolean value) [0x0000c] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control:set_Visible (bool)
>   at System.Windows.Forms.Application.RunLoop (System.Boolean Modal, System.Windows.Forms.ApplicationContext context) [0x0005f] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Application.Run (System.Windows.Forms.ApplicationContext context) [0x00014] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Application.Run (System.Windows.Forms.Form mainForm) [0x00006] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at DockSample.Program.Main () [0x00010] in <2f06aa1b7caa4019a9e2f166a9431f4d>:0
> [ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: The method or operation is not implemented.
>   at System.Windows.Forms.XplatUICarbon.SetClipRegion (System.IntPtr hwnd, System.Drawing.Region region) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.XplatUI.SetClipRegion (System.IntPtr handle, System.Drawing.Region region) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Control.CreateHandle () [0x00097] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Control.CreateControl () [0x0004b] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control:CreateControl ()
>   at System.Windows.Forms.Control.CreateControl () [0x00090] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control:CreateControl ()
>   at System.Windows.Forms.Control.CreateControl () [0x00090] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Control.SetVisibleCore (System.Boolean value) [0x00043] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Form.SetVisibleCore (System.Boolean value) [0x0007b] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Control.set_Visible (System.Boolean value) [0x0000c] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control:set_Visible (bool)
>   at System.Windows.Forms.Application.RunLoop (System.Boolean Modal, System.Windows.Forms.ApplicationContext context) [0x0005f] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Application.Run (System.Windows.Forms.ApplicationContext context) [0x00014] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
>   at System.Windows.Forms.Application.Run (System.Windows.Forms.Form mainForm) [0x00006] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0

I was able to compile it fine retargeting the .net framework to "mono / .NET 4.0" using Xamarin Studio, but when trying to run the sample I get the same exceptions as before.

**Comment by lextm** [comment]
Please read #273 . We don't invest any more on Mono support.
