### ISSUE TITLE
Tab document with dockable tool windows?

### ISSUE THREAD

**Issue by cay7man** [dockpanelsuite/dockpanelsuite#475]
I'm creating an app for opening log files. Each log file is opened as a tabbed document with a list view. I'd like to have each tab to contain two tool windows (bookmarks and filters) at the bottom. 

any ideas?

thanks
muthu

**Comment by lextm** [comment]
So your main form should contain a tab control, which then hosts a few tab pages, and each pages host a dock panel control, and its own dock contents.

**Comment by cay7man** [comment]
ok, I think I got your suggestion. Will give it a try. thanks
