### ISSUE TITLE
MeasureText is not Accurate TabCaption is being cut 

### ISSUE THREAD

**Issue by godevseast** [dockpanelsuite/dockpanelsuite#477]
Sample of Text being cut is the word Company.
In order to fix you need to add period in you Text when using MeasureText.
Before
TextRenderer.MeasureText(tab.Content.DockHandler.TabText, TextFont).Width +
                        TextGapLeft + TextGapRight;
After
TextRenderer.MeasureText(tab.Content.DockHandler.TabText+**"."**, TextFont).Width +
                        TextGapLeft + TextGapRight;

**Comment by lextm** [comment]
That does not seem to be a valid fix. Can you share more information with us? A sample project would be the best.

**Comment by godevseast** [comment]
Ok I got version 2.5 with the New Version 2.13 it is not happening anymore.
For some MeasureText old version have issue that you have to put period at the end to text so that i will not cut off.
Thanks,

**Comment by lextm** [comment]
http://docs.dockpanelsuite.com/en/latest/getting-started/history.html

2.5 is really an old release. You should always use our latest release if possible.
