### ISSUE TITLE
Drag'n'Drop not working in release 2.13

### ISSUE THREAD

**Issue by Wolf561** [dockpanelsuite/dockpanelsuite#478]
Hi,
I have upgraded my project to current releae 2.13 of the DockPanelSuite. Now dragging functions (by dragging a DockPane's tab with the mouse) do not work any more. It worked great in release 2.8, which I used before.

Do I have to change anything, by setting an option etc., to get this working again?

**Comment by lextm** [comment]
I cannot reproduce what you said.

**Comment by Wolf561** [comment]
Thanks for your extremely quick response! 

I installed and ran now your sample DockSample, it worked there. So I debugged my applicatiion a bit, and found, that (for any reasons) DockPane.ActiveContent.DockHandler.AllowEndUserDocking was set to false. When manually enabling this switch, dragging works as great as before. 

So, this issue can be closed from my point of view.
Thanks a lot for your hints, and your great work!!
