### ISSUE TITLE
CreatingContent on DockPane to allow FloatWindow to know who is creating it

### ISSUE THREAD

**Issue by joelbyren** [dockpanelsuite/dockpanelsuite#490]
When I get a new FloatWindow created (using my own factory) I want the FloatWindow to be of different sizes depending on the DockContent that initiated the float.

I have not yet found any way of getting this from the DockPanel or DockPane in the FloatWindow ctor, nor overloading OnLoad in FloatWindow. When OnShow is called my DockPanel has its ActiveContent set, and here I can set the size of the FloatWindow as I want. This however results in the window being resized/moved AFTER it has been rendered ones, so it's a quite annoying flicker.

Hopefully there is simply something I'm missing or have not understood; if not I propose adding a CreatingContent property on the DockPane which is only set for the InternalConstruct method (set at the top, unset at the bottom) that will allow the FloatWindow creation to set a content-dependent size on creation or at least OnLoad. PullRequest on its way.

**Comment by lextm** [comment]
The changes you made look good, but would you mind providing more info (like some sample code) to illustrate the issue and how to use the new property to solve it? That would make future viewers of this issue (and PR) easier to understand your proposal. Thanks.

**Comment by joelbyren** [comment]
On my derived dock content I have properties for setting the float window size (and minimum size)
`public class DockContent : DPS.DockContent
{
    public Size FloatWindowSize { get; private set; }
    public Size FloatWindowMinSize { get; private set; }
}`

I also have a derived FloatWindow that I would like to use these properties in, either in the constructor directly or at least when overriding OnLoad event. Today however, this is not possible; I will not have any Contents set on my DockPane until OnShow event, and if I change the size/location of the FloatWindow here I will get flickering (i.e. window painted in one location and then suddenly changing to another).

Having something separate would solve it if I undock/float using context menu, but since I also want this to work with drag-undock I really need a way of getting this to work from within DockPanel Suite framework.

With my proposed solution the CreatingContent property will allow the FloatWindow to check who is creating this content (if any) and set any properties directly from the constructor.

**Comment by joelbyren** [comment]
Btw, I'm trying to do a work-around now, using the pane that is sent in to the FloatWindow constructor. If this solution is not accepted I still need that functionality, and I really would prefer to use "baseline" and not my own branch. I'll keep you posted.

**Comment by lextm** [comment]
You might notice that this PR exposes a new property. That makes it impossible to ship like other patches under patch controller and to be disabled when we no longer need it. Thus, we need big enough justification.

One previous case is the closing button on tab feature. It was a separate patch for years, and not merged into the code base until we started to support VS 2012 themes.

I think we need more time here to validate its value to other users.

**Comment by joelbyren** [comment]
I found a workaround that is okay for both Windows and Linux!

1. In ctor for MyFloatWindow (inherited) keep reference to the DockPane and add event handler for ControlAdded
2. When ControlAdded triggers, remove event handler (since we only care about the creating contents) and do any handling needed here

With this I have what I needed, so I will close this now. I'll check if I can reject the pull request myself, if not feel free to close it.
