### ISSUE TITLE
ActiveContent must be one of the visible contents, or null if there is no visible content.

### ISSUE THREAD

**Issue by Vindil** [dockpanelsuite/dockpanelsuite#502]
I'm getting this exception, it's replicated by having only one docking content, making the docking content hidden and then saving and restoring from XML. Anymore than one and it doesn't happen

**Comment by lextm** [comment]
Duplicate to #226 

Unless you can provide a 100% reproducible sample, it cannot be easily analyzed.

**Comment by Vindil** [comment]
I'm trying to write a minimal piece of code to produce the exception, in the process of doing it i found this also causes the exception:

private DockPanel _dockPanel;
        private DockContent _content;

        public Form1()
        {
            IsMdiContainer = true;
            _dockPanel = new DockPanel
            {
                Theme = new VS2015BlueTheme(),
                Dock = DockStyle.Fill
            };
            Controls.Add(_dockPanel);
            InitializeComponent();
            _content = new DockContent();
            _content.Show(_dockPanel, DockState.Document);
            _content.Hide();
        }

**Comment by Vindil** [comment]
I noticed that if i returned a brand new docking content the exception disappeared. So i compared the properties of a new dock content and the recycled one and noticed that the recycled one had a dockstate of hidden whereas the new one had a state of unknown, so doing this:

private void testToolStripMenuItem_Click(object sender, System.EventArgs e)
        {
            _content.Hide();
            _dockPanel.SaveAsXml("test.xml");
            _content.DockState = DockState.Unknown;
            _content.DockHandler.DockPanel = null;
            _dockPanel.LoadFromXml("test.xml", DeserializeContent);
        }

Fixed the issue.

**Comment by lextm** [comment]
Thanks. I think another way can ultimately resolve this, but I am not sure if any side effect might happen. Will make a patch and put it under patch controller.

**Comment by lextm** [comment]
Can you compile DPS from source code and test out the patch on master branch?

**Comment by Vindil** [comment]
Yep that fixes it, thank you!
