### ISSUE TITLE
how to use dockpanel in .net framework 3.5

### ISSUE THREAD

**Issue by weskerjiang** [dockpanelsuite/dockpanelsuite#504]
how to use in .net 3.5, it always says "you are using a higher framework"

**Comment by enodatio** [comment]
The previous version 2.15 works fine, downgrade it in NuGet.  
I tried to post about this on the version bump but I guess its the wrong place. (I'm a git-hub scrub).
I'm curious if it's deliberate or just a build mistake?  I didn't notice any major changes going through that would require a newer framework.

**Comment by lextm** [comment]
Published 2.16.1 NuGet packages which should fix this issue.
