### ISSUE TITLE
Autohide error

### ISSUE THREAD

**Issue by kafino** [dockpanelsuite/dockpanelsuite#505]
Hello,
i have a problem with easy application.

Code:
[DatabaseUI.zip](https://github.com/dockpanelsuite/dockpanelsuite/files/1182251/DatabaseUI.zip)

Please view this video:
https://youtu.be/C4b2citfU7E

Thanks for your time and code, it is very fine for me.

**Comment by lextm** [comment]
You are still using 2.13 release. Can you try to use 2.16.1 from NuGet? My test shows that this issue is already resolved.
