### ISSUE TITLE
Investigation on VS2017 themes

### ISSUE THREAD

**Issue by lextm** [dockpanelsuite/dockpanelsuite#506]
Microsoft published Color Theme Editor extension for Visual Studio 2017 after 15.3 Update. By using that tool, I was about to create three VS2017 themes for testing,

https://github.com/dockpanelsuite/dockpanelsuite/tree/vs2017

**Comment by lextm** [comment]
From unit testing we can see the colors are exactly the same as VS2015 themes. So right now we have no urgent need to ship them.

I am not yet aware of any visual element differences, and once we know any we can implement the new elements and ship new themes.

**Comment by lextm** [comment]
Thus, close temporarily.

**Comment by tfbroner** [comment]
The VS 2017 theme as well as VS 2015 are quite different to what's in the Visual Studio.
#1 All panels have the same title bar design, no matter if docked or not. The DPS reverts to standard tool window look and feel when undocked.
#2 The title bar of all windows have additional hatch pattern painted, DPS doesn't have any.
#3 The document tabs include the Pin tab button and are all sharp edges, no rounded corners.
