### ISSUE TITLE
vs2013 BlueTheme in release v2.10

### ISSUE THREAD

**Issue by Wzshun** [dockpanelsuite/dockpanelsuite#508]
I debug the docksample in release v2.10,the UI likes this picture:![image](https://github.com/Wzshun/FirstDemo/blob/master/dock2013.png).
The red rect points out color wrong in theme.
I don't want to upgrade to v2.10 above since my project maybe used with .Net 2.0 in the future.

**Comment by lextm** [comment]
.NET Framework 2.0 has no future, and it is even not shipped on latest Windows by default.

As we move to a monthly release cycle, there would be no support given to old releases. You would have to cherry pick the necessary patches to see if you can fix that on your own.
