### ISSUE TITLE
FixButton and CloseButton change Color  on first setFocus 

### ISSUE THREAD

**Issue by patrick-dmxc** [dockpanelsuite/dockpanelsuite#509]
If I change the ForeColor of the header, the change from the title is taken immediately,
The pin and the X takes the color only when the form once get the Focus.
![issue](https://user-images.githubusercontent.com/7863301/29950728-11cd7944-8ebe-11e7-8170-89cd1b9d65c9.PNG)

I do not change the color with a theme, i set the color directly in the code.

**Comment by lextm** [comment]
Changing colors via code is not supported. You have to change the color in the theme.

**Comment by patrick-dmxc** [comment]
But everithing else works fine this way.

**Comment by lextm** [comment]
Something happens to work does not mean it is supported.

**Comment by ericoporto** [comment]
@patrick-dmxc did you ever figured a way to fix this?
