### ISSUE TITLE
DockPanel.ActiveDocument is one step behind with DockingMdi style

### ISSUE THREAD

**Issue by NekoKoneko** [dockpanelsuite/dockpanelsuite#51]
The DockPanel.ActiveDocument value holds the previous active document when switching between documents with keyboard shortcuts (Ctrl+Tab, Shift+Ctrl+Tab) or by selecting document from the Window menu.

Steps to reproduce:
1. Load the WinFormsUI.Docking.sln.
2. Open MainForm in the designer.
3. Add ActiveDocumentChanged event handler to the dockPanel control.
4. Edit the created event handler to look like this:

```
    if (this.dockPanel.ActiveDocument != null)
        System.Diagnostics.Debug.WriteLine(this.dockPanel.ActiveDocument);
```
1. Build and run.
2. Create 3 empty documents (File -> New). The Visual Studio Output window should contain 3 lines, the last one being "DockSample.DummyDoc, Text: Document3". (http://imageshack.us/photo/my-images/600/32047518.png)
3. Go to the Window menu and select "1 Document1". The active tab changes to the "Document1", but there is no new line in the Output window, meaning the event handler wasn't invoked. (http://imageshack.us/photo/my-images/405/78826564.png)
4. Go to the Window menu again and select "2 Document2". This time the event handler was invoked, but the last line shows, that the ActiveDocument property contains the previous active document (Document1). (http://imageshack.us/photo/my-images/19/64776299.png)
5. The above step can be repeated multiple times, but the ActiveDocument property will always be one step behind.
6. Now activate some other window (Toolbox for example). The event handler is immediately invoked and the Output window contains the line with the correct ActiveDocument property value. (http://imageshack.us/photo/my-images/834/19438604.png)

The issue is not present when activating tab with a mouse button.

Testing environment: latest DockPanel Suite source (commit 7154d18125f9f49e91de9e60f84f2171bfc73f6f), Windows 7 x64, Visual Studio 2008.

**Comment by Raviraj2017** [comment]
hi i m getting the similar error 
i m trying to switch the current tab to next next open tab 
this.DockPanel.ActiveDocument = totalActiveTab[i];
to open the next tab open but its giving an error
can some one please say where i  am making mistake

**Comment by lextm** [comment]
@Raviraj2017 what you asked has nothing to do with the original issue. Post a new one please.
