### ISSUE TITLE
The close button on the tab does not respond after panel width is reduced

### ISSUE THREAD

**Issue by lujiaxing** [dockpanelsuite/dockpanelsuite#510]
When I reduce width of a panel to that the tab can not display entire contents, then i click close button ("X" on tab), panel does not closed. After I drag panel wider, the close button works.

DockPanelSuite 3.0.0 on .NET Framework 3.5
ThemeVS2015Dark/Light/Blue
Windows 10.15063

![image](https://user-images.githubusercontent.com/7188738/30017057-36bea380-918a-11e7-8d22-ba39b236e953.png)

[DockTest.zip](https://github.com/dockpanelsuite/dockpanelsuite/files/1273999/DockTest.zip)

**Comment by lextm** [comment]
Please test the latest commit in master.

Will further improve it before shipping the new release.

**Comment by lujiaxing** [comment]
Your change is in another theme. But it also works in theme "VS2013". So it's resolved. Thank you.

**Comment by lextm** [comment]
Thanks. This issue affects VS2012-2015 themes, so I fixed them all. The patch would be part of 3.0.1 release, which will be shipped in two weeks.
