### ISSUE TITLE
About DockPanel.SaveAsXml() behavior

### ISSUE THREAD

**Issue by K-Teraguchi** [dockpanelsuite/dockpanelsuite#511]
The saved file generated by DockPanel.SaveAsXml() gets broken, not so often, but no error messages appear in my application log, so I don't know how to find the cause.

When this happened last time, the displayed layout was 2 DocLeft windows,
3 DockRightAutoHide windows, 2 Document windows and 1 DockBottom window.
After calling DockPanel.SaveXml() via Form.FormClosing event, the saved layout had only 1 DocRightAutoHide window, and all the others were IsHidden="True".

Is this a known bug? Anyone ran into a same kind of problem?
I would appreciate any advice how to troubleshoot this problem.

**Comment by lextm** [comment]
Unless there is a way to reproduce it, such issues cannot be investigated.
