### ISSUE TITLE
Splitter has no effect - Missing NestedDockingStatus.NestedPanes.SwitchPaneWithFirstChild(this);

### ISSUE THREAD

**Issue by csantav** [dockpanelsuite/dockpanelsuite#524]
Steps to reproduce:
1) Document Style: Docking Window
2) You need 3 floating ToolWindows: Properties, Task List, Toolbox (happens aswell with normal Documents)
3) Dock Properties to the left (DockState.DockLeft)
4) Dock TaskList to the bottom of Properties
5) Dock Toolbox to the bottom of Task List
6) Doubleclick the caption of Task List -> Task List is floating now
7) **The splitter between Properties and Toolbox has no effect now**
  -> the panelPane of Task List is still in the middle of the NestedPanes collection

the same happens when the IsFloat property of a content is set to TRUE (programmatically) and the Pane panelPane is hidden afterwards

**Comment by csantav** [comment]
The missing calls to SwitchPaneWithFirstChild i discovered are in DockPane.Float() or DockContentHandler.IsFloat

**Comment by lextm** [comment]
Closed via #525
