### ISSUE TITLE
Can't add themes controls to visual studio toolbox.

### ISSUE THREAD

**Issue by nicholasyin** [dockpanelsuite/dockpanelsuite#535]
Steps:
1. Create a new winform project;
2. Install DockPanelSuite and DockPanelSuite.ThemeVS2015 in PMC:
PM> install-package dockpanelsuite
PM> install-package dockpanelsuite.themevs2015
3. Right-click on toolbox General tab, select 'Choose Items', select the dll under '\WindowsFormsApp2\packages\DockPanelSuite.ThemeVS2015.3.0.3\lib\net40'.

![image](https://user-images.githubusercontent.com/17007651/34549453-a8a4a3aa-f143-11e7-91d3-1d7f25288061.png)

However, using the same dll downloaded inside the official DockSample works. And the 2 dll files have different size!!!
 
p.s.: Adding the controls inside 'WindowsFormsApp2\packages\DockPanelSuite.3.0.3\lib\net40\WeifenLuo.WinFormsUI.Docking.dll' has no problem.

**Comment by nicholasyin** [comment]
psst...

**Comment by lextm** [comment]
The steps are clear in our documentation,

http://docs.dockpanelsuite.com/en/latest/getting-started/installing-in-visualstudio.html

You cannot add from the NuGet package folder, as VS won't be able to locate the dependencies.
