### ISSUE TITLE
Theme applying to DockContent Controls

### ISSUE THREAD

**Issue by WorksOfLiam** [dockpanelsuite/dockpanelsuite#541]
Hi

I am using the `VS2015DarkTheme` theme, which is working fine for all the tabs, etc.

Let's say I have a DockContent, which inside has a ListView inside. 

In my constructor I am calling `DockContent#ApplyTheme` but the ListView does not match the theme colour. Is this expected?

```
    public partial class UserToolList : DockContent
    {
        public UserToolList()
        {
            InitializeComponent();
            ApplyTheme();
        }

    ...
```

**Comment by lextm** [comment]
DockPanel Suite theme will only affect its own visual elements.

The `ListView` control within the `DockContent` is not considered part of DockPanel Suite, so you have to render it on your own if you want to match the theme (which is possible, but can be complex).

**Comment by WorksOfLiam** [comment]
Hi @lextm 

Thanks for your answer! I am really enjoying dockpanel-suite.

This is what I am using it for: https://www.youtube.com/watch?v=wjl-_ErEcXM&t=8s

Thanks!

**Comment by lextm** [comment]
Besides, `ApplyTheme` should not be called by your code explicitly. I just modified the code base to hide it.
