### ISSUE TITLE
MainForm out of screen - no content

### ISSUE THREAD

**Issue by gmozhaev** [dockpanelsuite/dockpanelsuite#544]
In DocSample MainForm.Designer.cs
change
this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
to
this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
this.Location = new System.Drawing.Point(-50, 0);
and see no content in Document1

**Comment by lextm** [comment]
Cannot reproduce it on my machine.

**Comment by gmozhaev** [comment]
Change code
Start DockSample.exe
New (create new windows)
Close app
Restart

**Comment by lextm** [comment]
Cannot reproduce it still.

By the way, it seems that you are using Windows XP or Windows Server 2003. As they both are end-of-life, we won't support them any more.
