### ISSUE TITLE
Cannot drag a toolwindow

### ISSUE THREAD

**Issue by dxc31202** [dockpanelsuite/dockpanelsuite#548]
I have created an app and included it as a project in another app. When it is stand alone it works fine, but when it is included in the other app it wont allow dragging of the toolwindows

**Comment by lextm** [comment]
What do you mean by "when it is included in the other app"?

**Comment by lextm** [comment]
http://idownvotedbecau.se/itsnotworking/

**Comment by dxc31202** [comment]
Very helpful!
