### ISSUE TITLE
closing any tab when using DocumentStyle == DockingWindow focus the very first tab

### ISSUE THREAD

**Issue by fabriceleal** [dockpanelsuite/dockpanelsuite#558]
Like the title says, when i close, for instance, the last tab, the very first is selected, which I find very annoying.

Is this behavior by design or a bug? I noticed that when using DocumentStyle == DockingMdi this doesnt happen. This is easily reproducible by changing the DockSample to use DockingWindow instead of DockingMdi.

I made a silly change that achieves the behavior I want - select the previous tab (there's another reference to CloseContent, but not sure about the best way of getting the ActiveContent's index other than seeking it in Tabs):

https://github.com/fabriceleal/dockpanelsuite/commit/d697ea8acdb77c0deee6ff5e16054edd2674cecd

If this is this good enough for a pull request, I'll make it.

**Comment by lextm** [comment]
It looks OK. If you are going to create a pull request, please also put it under patch controller,

http://docs.dockpanelsuite.com/tutorials/disabling-patches.html

You can refer to other patches listed, so as to learn what changes you need to make.
