### ISSUE TITLE
Docking DockContent to DockPane with given pane proportion

### ISSUE THREAD

**Issue by vlam13** [dockpanelsuite/dockpanelsuite#560]
In an older version of DockContentHandler was the method 
`        public void DockTo(DockPane pane, DockStyle dockStyle, int contentIndex, double proportion)`
using which was possible to create Pane with give proportion value. But in the latest version this method was removed. Is there any other way to set proportion of a new Pane?

**Comment by lextm** [comment]
Which version?

**Comment by vlam13** [comment]
Seems that it was my own modification. Sorry for this mistake. But anyway would be nice to have a possibility to set a DockPane proportion.
