### ISSUE TITLE
Document tabs reset to the first tab when a pane is removed

### ISSUE THREAD

**Issue by trylock** [dockpanelsuite/dockpanelsuite#563]
I'm not sure if this is a bug. If I set DocumentStyle to `DocumentStyle.DockingWindow` (from its default value `DocumentStyle.DockingMdi`), it works as expected. What is the difference between these 2 values? 

Steps to reproduce this:

1. Create 3 DockContent objects
2. Show 2 contents using DockState.Document and the third using DockState.DockRight
3. Select the second tab in the document content (labeled "Doc2" if you use the code example below)
4. Close the side window (this will activate the first tab)

Here is a code I used in my main form constructor to reproduce the issue:
```C#
IsMdiContainer = true;

var dockPanel = new DockPanel();
dockPanel.Dock = DockStyle.Fill;
Controls.Add(dockPanel);

var window1 = new DockContent();
var window2 = new DockContent();
var window3 = new DockContent();
window1.Text = "Doc1";
window2.Text = "Doc2";
window3.Text = "Doc3";

window1.Show(dockPanel, DockState.Document);
window2.Show(dockPanel, DockState.Document);
window3.Show(dockPanel, DockState.DockRight);
```

It only happens when a pane is removed.

**Comment by lextm** [comment]
Unfortunately that knowledge was not passed on, and it is difficult to tell the original design goals of the different docking modes.

Therefore, I personally consider what you observed as something by design.

**Comment by trylock** [comment]
Fair enough. Like I said, using `DocumentStyle.DockingWindow` solved the problem. So, I'm closing this issue. Thanks for your time.
