### ISSUE TITLE
InvalidOperationException on startup v3.1

### ISSUE THREAD

**Issue by barma1ey** [dockpanelsuite/dockpanelsuite#580]
When DocumentStyle property is defined in designer, VS auto-generates the code (it does it in alphabetical order) which prevents to set a theme first.  So the Exception is thrown after each modification in designer.

**Comment by lextm** [comment]
Thanks. That's still a beta release.

Please roll back to 3.0.6 while I am investigating the cause.

**Comment by barma1ey** [comment]
Well, I think I've found the answer. ISupportInitialize interface should help. See [https://msdn.microsoft.com/en-us/library/ms973818.aspx](url)

**Comment by lextm** [comment]
Addressed it locally. Will publish beta 3 for testing later this week.
