### ISSUE TITLE
SaveAsXml saving wrong data

### ISSUE THREAD

**Issue by bsabiston** [dockpanelsuite/dockpanelsuite#582]
We use DockPanelSuite to save and re-load our in-house application's window configurations.  Sporadically it is writing out bad window position, size, and hierarchy information to the XML file when using SaveAsXml.  I haven't been able to reproduce the issue live -- I can only view the xml files that have been written out after it happens to people here.  Positions and sizes of windows, as well as parenting information, are incorrect.
  
We're using the SaveAsXML() function this way.  When we get a WndProc->WM_CLOSE message, we call a function which calls SaveAsXML() to write out the window positions.  I'm wondering if somehow the window forms' memory is being released before it is saved, so that sometimes the data is bad.  In addition to the DockPanelSuite, that close function writes out other program settings, and one of those includes the position and size of the main form.  It, too, will sometimes write out bad data.  So it seems like not a problem within DockPanelSuite, but maybe something to do with the information provided to it?  

I am just wondering if this is familiar to anyone, if anyone knows what might be the problem?

**Comment by lextm** [comment]
"When we get a WndProc->WM_CLOSE message"? Cannot you try to use `FormClosing ` event, https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.formclosing?

**Comment by bsabiston** [comment]
I will try that if I can -- this is code I did not write, I am just looking to fix a bug.  Do you know of some problem with using the WM_CLOSE event?  Thanks for the suggestion.

**Comment by lextm** [comment]
I can only assume that the order of the events can have an impact on what is written to the disk (as if you use an event that is too close to the final shutdown of the process, DPS might have no time to write complete data to disk).

**Comment by lextm** [comment]
We only support the following ways to install it,

http://docs.dockpanelsuite.com/getting-started/installing-on-windows.html

So you can easily know the version number from the NuGet package or source code.

All other ways of installation are not considered supported by this repo, and beyond the scope of discussion.

**Comment by bsabiston** [comment]
I'm not sure how they installed it, but I'd like to check to see if it is outdated.  We use VS 2015 - so I guess if I need to update it, I would use the NuGet method.  But where in the source code can I find out which version we have, do you know?  I'm not seeing anything obvious so far.

**Comment by lextm** [comment]
This repo uses this file,

https://github.com/dockpanelsuite/dockpanelsuite/blob/master/WinFormsUI/Properties/AssemblyInfo.cs

**Comment by bsabiston** [comment]
Thanks - looks like we have version 2.7.0.0
