### ISSUE TITLE
Some bugs in v 3.0.6

### ISSUE THREAD

**Issue by barma1ey** [dockpanelsuite/dockpanelsuite#583]
I have checked the code with a static analyzer.  So, it says the following:
1. 'sm_localWindowsHook' object was used before it was verified against null. DockPanel.FocusManager.cs 158
2. '!Outline.FlagTestDrop' is always true. DockPanel.DockDragHandler.cs 785
3. Identical expression 'location.X' to the left and to the right of compound assignment. DockContentHandler.cs 1161
4 The same as previous: Identical expression 'location.X' to the left and to the right of compound assignment. DockPane.cs 1263 & Identical expression 'y' to the left and to the right of compound assignment. FloatWindow.cs 183
5. Expression 'index >= 0 || index < Tabs.Count' is always true. DockPaneStripBase.cs 281
6. The conditional expressions of the 'if' statements situated alongside each other are identical. Check lines: 110, 112. DockAreasEditor.cs 110
 public void SetStates(DockAreas dockAreas)
            {
                m_oldDockAreas = dockAreas;
                if ((dockAreas & DockAreas.DockLeft) != 0)
                    checkBoxDockLeft.Checked = true;
                if ((dockAreas & DockAreas.DockRight) != 0)
                    checkBoxDockRight.Checked = true;
                if ((dockAreas & DockAreas.DockTop) != 0) //<= here
                    checkBoxDockTop.Checked = true;
                if ((dockAreas & DockAreas.DockTop) != 0)  //<= here
                    checkBoxDockTop.Checked = true;
                if ((dockAreas & DockAreas.DockBottom) != 0)
                    checkBoxDockBottom.Checked = true;
                if ((dockAreas & DockAreas.Document) != 0)
                    checkBoxDockFill.Checked = true;
                if ((dockAreas & DockAreas.Float) != 0)
                    checkBoxFloat.Checked = true;
            }

**Comment by lextm** [comment]
There is no plan to address such, as static analyzers can report false positives. Even if they do report correctly, the performance impact of not fixing is not significant.

It is more risky to carry out changes as the code base does not come with a complete test suite.
