### ISSUE TITLE
How to change default size of window

### ISSUE THREAD

**Issue by bsabiston** [dockpanelsuite/dockpanelsuite#593]
I'm having a hard time figuring out how to prevent all my opened windows from being 300 x 300 the first time they are opened.  I try setting the size immediately before opening, and it still doesn't work.  How do you do this?

            Point oSize = new Point(500, 500);
            Point oTopLeft = oPanel.Location;
            Rectangle oRect = new Rectangle(800, 800, oSize.X, oSize.Y);
            oPanel.Show(oPanel.DockPanel, oRect);

This still shows up in the upper left hand corner at size 300x300...

**Comment by lextm** [comment]
Check the sample project please. What you experienced does not seem to be a DPS issue, and can be a typical WinForms issue, where you didn't let the UI element layout properly.

**Comment by bsabiston** [comment]
Well - we are using a very old version of DPS, so it's probably related to that.   It's been modified a lot and people don't want to update.

In any case, I fixed my problem by setting the FloatWindow size to the size specified in Winforms.
oPanel.FloatPane.FloatWindow.Size = oPanel.Size;
oPanel.Show();
