### ISSUE TITLE
Tab document style

### ISSUE THREAD

**Issue by nerogcy** [dockpanelsuite/dockpanelsuite#594]
how to set all tab as document style header instead of long bar header

Long bar style header
![Capture](https://user-images.githubusercontent.com/20985725/56060176-9f44a900-5d98-11e9-86ca-101aee92ec37.JPG)

Document style header 
![Capture2](https://user-images.githubusercontent.com/20985725/56060182-a66bb700-5d98-11e9-86a9-4482456bfb0e.JPG)

**Comment by lextm** [comment]
They are different visual elements, so rendered differently.

http://docs.dockpanelsuite.com/themes/basics.html#visual-elements-of-a-theme

**Comment by nerogcy** [comment]
u mean use ThemeBase.ApplyTo? but how to use it, if i wan my dockcontent always render as document

**Comment by lextm** [comment]
No. I mean if you want a rendering effect, learn which visual element you are looking for and create such elements. Don't expect one element (tool window) to look like another (document).
