### ISSUE TITLE
Cannot compile 

### ISSUE THREAD

**Issue by AngeloMascaro** [dockpanelsuite/dockpanelsuite#596]
I just cloned the project and try to execute it, but I got a lot of errors  namespace could not be found.
Attached the compiler output and the visual studio configuration

[errors.txt](https://github.com/dockpanelsuite/dockpanelsuite/files/3134772/errors.txt)
[visualstudio_info.txt](https://github.com/dockpanelsuite/dockpanelsuite/files/3134777/visualstudio_info.txt)

**Comment by lextm** [comment]
Restore NuGet packages and then compile it.

**Comment by AngeloMascaro** [comment]
I wasn't able to use NuGet and I cloned the software from github.
In Packet Manager console I issue the command "Install-Package DockPanelSuite -Version 3.0.6" but I always get this error:

Attempting to gather dependency information for package 'DockPanelSuite.3.0.6' with respect to project 'WinFormsUI', targeting '.NETFramework,Version=v4.0,Profile=Client'
Install-Package : An error occurred while retrieving package metadata for 'DockPanelSuite.3.0.6' from source 'nuget.org'.
  Failed to fetch results from V2 feed at 'https://www.nuget.org/FindPackagesById()?id='DockPanelSuite'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 404 (Not Found).
  Response status code does not indicate success: 404 (Not Found).
At line:1 char:16
+ Install-Package <<<<  DockPanelSuite -Version 3.0.6
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:02.6702518
PM>

**Comment by lextm** [comment]
I won't be able to help you on NuGet issues. The error message also indicates that you might be using a very old NuGet release. As of today, you are supposed to use only VS2015 and above, and also latest NuGet bits, so as to work with the latest technologies.
