### ISSUE TITLE
How to do On-The-Fly Workspace Presets?

### ISSUE THREAD

**Issue by NothingFaceX** [dockpanelsuite/dockpanelsuite#597]
Hi , First , Great Lib Nice Job!!!
I need to create a workspace preset combo box to make users able to save their current dock panels as presets , I found `SaveAsXml` and `LoadFromXml` , LoadFromXml is a little confusing to me , How can I load them on the fly without closing or destroying opened forms ?

For example :
- Animator Workspace
- Photographer Workspace
- Developer Workspace

Thanks

**Comment by lextm** [comment]
Seems to be duplicate to #213.

**Comment by NothingFaceX** [comment]
@lextm , no it's not , I don't want to remove current forms :D

**Comment by lextm** [comment]
As far as I can see, the behavior showed in the sample project is what this library can offer (also what's been discussed in #213.

**Comment by NothingFaceX** [comment]
I'm saying , I don't want to close documents ...
In example you used "CloseAllContents" and it will close all documents ...
I just want to change the workspace ...

**Comment by lextm** [comment]
Feel free to implement what you wanted and send us a pull request. But it is not available right now.
