### ISSUE TITLE
How to change color of Preview panel ? [Transparent Blue Rect]

### ISSUE THREAD

**Issue by NothingFaceX** [dockpanelsuite/dockpanelsuite#599]
Hi dear devs , How can I change color of preview panel on dragging ?
https://pasteboard.co/IeWhrad.jpg

I tried to find it but I don't know what is the name of this thing :D
thanks

**Comment by lextm** [comment]
The UI element is the drag form (DragForm.cs) and its colors are set in

https://github.com/dockpanelsuite/dockpanelsuite/blob/master/WinFormsUI/ThemeVS2012/VS2012DockOutlineFactory.cs#L22

**Comment by NothingFaceX** [comment]
That's it , Thank you !
