### ISSUE TITLE
Documents' FormClosed() event is not fired when DockPanel is closed

### ISSUE THREAD

**Issue by lafrank** [dockpanelsuite/dockpanelsuite#613]
I am wondering if this behavior is by design or I am missing something, but when I close the form having the DockPanel, none of the docked forms' FormClosed() event is fired.
As a workaround I need to close all docked Content programmatically, but I am not sure if this is the right approach.

**Comment by Polymaker** [comment]
I have a project that is using version 3.0.4 and I don't have the issue, so something broke in version 3.0.6. I tried to give a look but I haven't yet found the cause of the problem.

**Comment by rLindorfer** [comment]
I am using the latest version of DockPanelSuite and I do not have this problem. Could you give a more detailed explanation of the problem and when it occurred?

**Comment by lafrank** [comment]
Thanks René, it's been so long ago, I can't even remember the problem.
I must have resolved it since then.

**Comment by Progress1** [comment]
Hi, same problem start appear to me when i switch from 3.0.6 to 3.1.0 :)
When i close main app in 3.0.6 all child windows raised event FormClosing, FormClosed, properly close and then main app continue properly exit (FormClosed).
In 3.1.0 these events are **not raised** and main app crash on WndProc VM_KILLFOCUS message. Error happened after main app exit (FormClosed event).
Tested on Win10, x64, net40.
