### ISSUE TITLE
Support .NET Core 3.x

### ISSUE THREAD

**Issue by msneijders** [dockpanelsuite/dockpanelsuite#616]
A first try got DockSample working with ThemeVS2015 -- but some errors with persistence, not further investigated. I just created new .NET Core 3.0 projects enabling Winforms, adding all *.cs,*.resx,*ico etc and it just compiles and runs. So it is feasable without too much hassle.

Motivation: new C# 8.0 features like async stream, and probably all future language features will not work on .NET Framework 4.8, only on .NET Core and future .NET 5.x.

**Comment by lextm** [comment]
Most of the code base today is in C# 2.0, so really no plan to jump to C# 8.0. It will be too much effort to upgrade and review.

**Comment by msneijders** [comment]
I was under the assumption a .NET Core 3.x Winforms project would not be compatible with DockPanelSuite build as a 'normal' .Net Framework 4 library as a reference. But I just tested this, and I was wrong. I now only migrated 'DockSample' to .NET Core 3.0, referencing the .NET Framework 4 WeifenLuo.WinFormsUI.Docking.*.dlls. It seems to just work in runtime.

**Comment by rLindorfer** [comment]
I have problems using DockPanelSuite with .NET Core 3.1. When I try to dock a View, I get a System.TypeLoadException for the type System.Windows.Forms.ContextMenu. 

This is caused by the ContextMenu, because this class is not supported in .NET Core. 
Is there a way to disable this context menu or fix this compatibility issue?

**Comment by lextm** [comment]
@rLindorfer you have to either downgrade to .NET Core 3.0, or compile the latest source code from https://github.com/dockpanelsuite/dockpanelsuite

It is Microsoft who removed those types from .NET Core 3.1 which breaks many existing NuGet packages.

**Comment by rLindorfer** [comment]
I have just tried to downgrade my project to .NET Core 3.0, but I still get a System System.TypeLoadException for the type System.Windows.Forms.ContextMenu. 
Next, I will try to compile the latest source code from https://github.com/dockpanelsuite/dockpanelsuite.

**Comment by rLindorfer** [comment]
Today I tried to compile the latest source from https://github.com/dockpanelsuite/dockpanelsuite into a NuGet package with the included script "release.ps1". The build was successful, but I am not able to import it in my project, because it causes a circular dependency...

**Comment by lextm** [comment]
That's the .NET Core SDK I referred to earlier.

You have to use project reference at this moment, http://docs.dockpanelsuite.com/getting-started/installing-on-windows.html#install-dockpanel-suite-via-source-code

**Comment by rLindorfer** [comment]
Thank you very much! With project reference it works perfectly.

**Comment by rLindorfer** [comment]
Finally, I tried to set up my CI/CD toolchain using "dotnet build" for the compilation of my visual studio solution. Unfortunately, I cannot build a .NET Framework 3.5 project with "dotnet build", but the "WeifenLuo.WinFormsUI" project targets "net35".

Is there any functional need to support the .NET Framework 3.5 when using .NET Core?

**Comment by rLindorfer** [comment]
@lextm: And as already mentioned in https://github.com/microsoft/msbuild/issues/4704#issuecomment-540139063 it is required to add following lines into the WinFormsUI.csproj and the corresponding theme projects to successfully build a project with resources:

`<PackageReference Include="System.Resources.Extensions" Version="4.6.0" />`
to references and
`<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>`
to a property group

**Comment by lextm** [comment]
@rLindorfer You don't need that hack if you are not using their latest (but still buggy) .NET Core SDK but an old and stable version.

I rather wait till they fix all bugs that affect DockPanel Suite than wasting my time.
