### ISSUE TITLE
Doc on top of each other

### ISSUE THREAD

**Issue by BergChristian** [dockpanelsuite/dockpanelsuite#617]
Hi,

Need a little help...

On the right side I would like to have two windows, one up and another filling the rest of the right panel and then in the main window I add many documents tabbed.

Anyone know how to achieve this?

Best
Christian

**Comment by lextm** [comment]
Please try to draw it out and share here so that readers might understand what you mean.

**Comment by CBergAccount** [comment]
I have solved it. 
Posting the solution here:

  controldetails.DockHandler.CloseButton = False;
        controldetails.DockHandler.CloseButtonVisible = False;
        controldetails.Show(DockPanel1, DockState.DockRight);


        controlimage.DockHandler.CloseButton = False;
        controlimage.DockHandler.CloseButtonVisible = False;
        controlimage.Show(controldetails.Pane, DockAlignment.Top, 0.3);

This gives me this windows where I am adding tabbed documents in the main area and two windows on the right side on top each other,:
__________
|          |__|
|          |   |
-----------
