### ISSUE TITLE
AcitveDocument/ActivePane behavior does not match Visual Studio's behavior

### ISSUE THREAD

**Issue by Fatcrobe** [dockpanelsuite/dockpanelsuite#619]
The behavior that shows which pane is focused in DockPanelSuite does not match Visual Studio. The first difference is that only the active pane (focused) in visual studio is "highlighted" while DPS can have 1 pane and 1 document highlighted at the same time.

VS2019:
[![Image from Gyazo](https://i.gyazo.com/3aa3182140fb5f2e1379b935375fcc54.gif)](https://gyazo.com/3aa3182140fb5f2e1379b935375fcc54)

DPS:
[![Image from Gyazo](https://i.gyazo.com/5279866e04b9d2d6d82bf158844a90ec.gif)](https://gyazo.com/5279866e04b9d2d6d82bf158844a90ec)

The second difference is with floating panes, in visual studio the active document's tab strip will lose its highlight when you select a floating pane while with DPS the active document will remain highlighted:

VS2019:
[![Image from Gyazo](https://i.gyazo.com/1b9815ecbf22ecbaf3a7077ca66296e0.gif)](https://gyazo.com/1b9815ecbf22ecbaf3a7077ca66296e0)

DPS:
[![Image from Gyazo](https://i.gyazo.com/bd729e5a2cef5ed145b7264836a71069.gif)](https://gyazo.com/bd729e5a2cef5ed145b7264836a71069)

I also tested in visual studio 2017 and visual studio 2010 and they have same behavior. You might also wonder what about the panes that have buttons dependent on the active document, for example the "sync with active document" in solution explorer. They will work and in this case it will sync with the last document pane that was focused.

After analyzing the DPS code I came to the conclusion this cannot be fixed without changing DPS source code (I did find a solution but I it was a hack so I don't like it). The issue is that VS2013DockPaneStrip highlights the TabStrip of the pane depending on the IsActiveDocumentPane property but it should be based on IsActivePane instead. Note that SetIsActivated method on DockPane will need to be adjusted because RefreshChanges is not called if it's a document and it should.

I will probably make a pull request when I get a chance with the fix described above but wanted to hear your opinion

**Comment by lextm** [comment]
You probably should compare to VS2005/2008. DPS is WinForms based, and VS2010+ is WPF based, so from then on it is almost impossible to clone every behaviors.

**Comment by Fatcrobe** [comment]
You are right, VS2005 has the same behavior although you cannot have floating views. When I wrote this post I was under the impression that DPS was trying to replicate Visual Studio's docking as close as possible but after review it seems like I was wrong. The only mention about Visual Studio is on the NuGet page:

> The docking library for .Net Windows Forms development which mimics Visual Studio .Net.

So I understand if this is not considered a bug or an enhancement, what's your stance on this?

**Comment by lextm** [comment]
Several differences you noticed are caused by the different focus related design between WinForms and WPF. That's something this library alone won't be able to conquer.
