### ISSUE TITLE
Hello, I'd like to ask you about the .net requirement 

### ISSUE THREAD

**Issue by steven1536796418** [dockpanelsuite/dockpanelsuite#620]
Hello, if I want to use it in the .net3.5 environment, it may alert the version problem, may this support the .net 3.5?
Thank you

**Comment by lextm** [comment]
.NET Framework 3.5 is currently supported, but no promise that it will be supported in the future.

**Comment by steven1536796418** [comment]
ok, thank for your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lex Li"<notifications@github.com&gt;; 
发送时间: 2020年1月15日(星期三) 晚上11:00
收件人: "dockpanelsuite/dockpanelsuite"<dockpanelsuite@noreply.github.com&gt;; 
抄送: "天地景逸"<1536796418@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dockpanelsuite/dockpanelsuite] Hello, I&#39;d like to ask you about the .net requirement  (#620)



.NET Framework 3.5 is currently supported, but no promise that it will be supported in the future.

**Comment by steven1536796418** [comment]
Excuse me, how to install the suite for .net3,5

**Comment by lextm** [comment]
http://docs.dockpanelsuite.com/getting-started/installing-on-windows.html
