### ISSUE TITLE
 how to use LoadFromXml

### ISSUE THREAD

**Issue by wallysonn** [dockpanelsuite/dockpanelsuite#623]
Would anyone have an example of how to use this option? I tested some codes, but without success.

Vejam um exemplo:

```
private DockPanel DP = new DockPanel
{
 Dock = DockStyle.Fill,
Theme = new VS2015LightTheme()
};
...
var fileLayout = getFileXmlLayout();
if (File.Exists(fileLayout))
{
var m_deserializeDockContent = new DeserializeDockContent((string persistString) =>
{
//I don't know what to do here
});
DP.LoadFromXml(fileLayout,m_deserializeDockContent);
}
```

**Comment by rLindorfer** [comment]
Hello wallysonn,

take a closer look into the DockSample project and investigate following code snippet:

https://github.com/dockpanelsuite/dockpanelsuite/blob/a4a205d5660a3852d0697af9243c70bb14375dd8/DockSample/MainForm.cs#L103
