### ISSUE TITLE
Basic example error MDI container forms must be top-level

### ISSUE THREAD

**Issue by Yoonwoo** [dockpanelsuite/dockpanelsuite#624]
I am trying just to make it run but this line of code never works:
doc1.Show(dockPanel, DockState.Document);

I have a top level form with dockpanel in the designer, its set to an MDI container.

```
{
    public partial class Form1 : DockContent
    {
        public Form1()
        {
            InitializeComponent();
            this.IsMdiContainer = true;
            var theme = new VS2015BlueTheme();
            dockPanel1.Theme = theme; // error if I dont set this
            this.TopLevel = true;
            this.Show(dockPanel1, DockState.Document); // causes error
        }
    }
}
```

I have tried so many things and tried to find why it doesnt work but I cant

Unhandled Exception: System.ArgumentException: MDI container forms must be top-level.
Parameter name: value

**Comment by roken** [comment]
Top-level means it cannot have a parent, thus your Form1 cannot have the Parent property set if IsMDIContainer is true.

You cannot nest an MDI container inside another DockContent. The MDI container needs to be a the Form displayed at the top level of the application. This is a WinForms (or really, the underlying Windows OS) limitation.

**Comment by Yoonwoo** [comment]
Yes, I know but it is top-level, I cant see how it isnt. I made a template winforms project in visual studio, there is one auto generated form, the main window, and this main window is the class shown above.

So how it is not top level?

**Comment by roken** [comment]
Check the value of Parent on that form at the time of exception. If null, that is bizarre. Otherwise, it gives you the parent control and the form is not the top level

**Comment by Yoonwoo** [comment]
The value of parent for form 1 and form 4 is both null.

Maybe there is something else im doing wrong but its just a form and then form4 is an empty DockContent subclass and both are set to MDI container true

**Comment by Yoonwoo** [comment]
Well I tried to upload the project to github but just by uploading the files so doesnt compile but you can see the code in full

https://github.com/Yoonwoo/docktest

**Comment by roken** [comment]
Form1 is your MDI container, that is correct. Form4 should not be, set that back to false.  If you still hit the issue, please post the full stack trace

**Comment by Yoonwoo** [comment]
I dont know if this is it the call stack has not much information in it but this is the full error,
I had already tried with and without for that

Unhandled Exception: System.InvalidOperationException: Invalid parent form. When using DockingMdi or SystemMdi document style, the DockPanel control must be the child control of the main MDI container form.
   at WeifenLuo.WinFormsUI.Docking.DockPanel.get_ParentForm()
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetPane(DockPane pane)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetDockState(Boolean isHidden, DockState visibleState, DockPane oldPane)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.set_Pane(DockPane value)
   at WeifenLuo.WinFormsUI.Docking.DockPane.InternalConstruct(IDockContent content, DockState dockState, Boolean flagBounds, Rectangle floatWindowBounds, DockPane prevPane, DockAlignment alignment, Double proportion, Boolean show)
   at WeifenLuo.WinFormsUI.Docking.DockPane..ctor(IDockContent content, DockState visibleState, Boolean show)
   at WeifenLuo.WinFormsUI.ThemeVS2013.VS2013DockPane..ctor(IDockContent content, DockState visibleState, Boolean show)
   at WeifenLuo.WinFormsUI.ThemeVS2013.VS2013DockPaneFactory.CreateDockPane(IDockContent content, DockState visibleState, Boolean show)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel, DockState dockState)
   at WeifenLuo.WinFormsUI.Docking.DockContent.Show(DockPanel dockPanel, DockState dockState)
   at docktest.Form1..ctor() in C:\Code\docktest\docktest\Form1.cs:line 29
   at docktest.Program.Main() in C:\Code\docktest\docktest\Program.cs:line 16

**Comment by roken** [comment]
Yes, that is the call stack. Being able to read and understand exceptions and their stack is a key skill to software development and i suggest you focus on this aspect of debugging. If you read this exception you now see that the original error is gone and have encounter a new one... And it is telling you a lot of information:

"Invalid parent form. When using DockingMdi or SystemMdi document style, the DockPanel control must be the child control of the main MDI container form."

This is saying the Parent of the dockpanel, which was Form1 in the sample code you provided, is not an MDI container any longer.  Did you turn that off?

You might have better luck changing the DocumentStyle of the panel to DockingWindow, which will stop using the OS MDI. Please play around with the sample application to get familiar with the options.

**Comment by Yoonwoo** [comment]
Hi,
Yes sorry that error is the original error I had then it changed slightly when I tried making the form a dockcontent.
I have debugged form1 and IsMDIContainer is still true when the error occurs so I just think it doesnt work, maybe the OS MDI doesnt work.

Also when I did just this code

`
Form3 f3 = new Form3();
f3.Show(dockPanel1, DockState.DockRight);
`

it works, but if you drag it to the center the program crashes. 

I tried changing the document style to docking window it it works now. BUT that was something I had already tried before, but when you set it in the designer properties it says invalid value:
DockPanel.Theme must be set to a valid theme.

And it works in code
`
  dockPanel1.DocumentStyle = DocumentStyle.DockingWindow;
`

Because I happened to do it in code this time and its after the theme set been set.

**Comment by Yoonwoo** [comment]
So as you can see there are a lot of hurdles to overcome just to make a basic example sort of work, so I really think there should be a most basic possible 10 lines of code type example people can compile and run, and the sample program isnt suitable for that.

**Comment by Yoonwoo** [comment]
I have it working as long as its not MDI, thanks for helping me with it. Now I can actually do something with it. Thanks
