### ISSUE TITLE
how to creat a docked Grid?

### ISSUE THREAD

**Issue by biotech7** [dockpanelsuite/dockpanelsuite#626]
i want to creat a grid which is docked, but not know how to write the corresponding dock file? can anyone give me any help?

**Comment by lextm** [comment]
It is not clear what you wanted to achieve. You might try to draw something to illustrate more.

**Comment by biotech7** [comment]
hi, thanks for your reply, i am a novice。 i want to achieve a grid(table) as looks like below.
![33](https://user-images.githubusercontent.com/49674341/78035137-4603ca00-739b-11ea-9c53-d1e678580d03.jpg)

**Comment by lextm** [comment]
Then this has nothing to do with DockPanel Suite. You need to learn the default ListView control, https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/listview-control-windows-forms
