### ISSUE TITLE
Cefsharp browser not showing when dragging in/out of DockState Document

### ISSUE THREAD

**Issue by Dash83UPV** [dockpanelsuite/dockpanelsuite#627]
Hi everyone.

I have been using DPS (dock panel suite) for some time and I wanted to use it for my next project. It includes ChromiumWebBrowser for c# (cefsharp) available on NuGet. 

My issue is the following one (the code is below the explanation):

1) Create TestMainForm, set IsMdiContainer =true, and add a DockPanel to it.

2a) On Load, create a DockContent, add a Cefsharp browser to it and set it to DockState.Float
3a) When the program is running, drag the float window into the center position (Document)
      - The browser is still there, but it doesn't show.
3b) Drag it instead to a side/top/bottom position (ToolWindows)
     - Everything works perfectly

2b) This time instead, on Load, create a DockContent, add a Cefsharp browser to it and set it to DockState.Document
3) Drag it out of the center position (Document) 
      - The browser is still there, but it doesn't show

Also tested, that if I instantiate the browser again it work perfectly, so dragging it in/out does not "corrupt" the DockContent, it only "corrupts" the cefsharp browser.

Also tested changing the DockContent by code (instead of using the mouse) from Float to Document and vice versa. Same results.

Also tested with another more "advanced" Controls, such as MapServers, etc. Same results.

I have been reading the DPS library code and I understand the code, but not the architecture. Also I cannot find the issue at all.  

Please any help or comments will be appreciated.

Best regards.

-------------------------------------

using CefSharp.WinForms;
using WeifonLou.WinFormsUI.Docking;

public TestMainForm()
{
 InitializeComponent();
 IsMdiContainer = true;
}

private void TestMainForm_Load(object sender, EventArgs e)
{
 DockContent dockContent = new DockContent();
 dockContent.Text = "TEST";
 //dockContent.Show(dockPanel, DockState.Document);
  dockContent.Show(dockPanel, DockState.Float);
  dockContent.Controls.Add(new ChromiumWebBrowser("www.google.es"));
}

**Comment by Dash83UPV** [comment]
Just made another test. I played Youtube on the browser, and moving it to the ToolWindows and the video is still sounding, but when I moved it to the Document, the sound stopped. It seems it also affects the browser and the inside process, although the object still exists on memory.

**Comment by amaitland** [comment]
Likely what you are seeing is https://github.com/cefsharp/CefSharp/issues/2840

**Comment by Dash83UPV** [comment]
Hi amaitland.
Excellent response. That is exactly what is happening. 

The code suggested by rLindorfer (https://github.com/cefsharp/CefSharp/issues/2840#issuecomment-606495065) solved the issue perfectly. Some other modifications where necessary for the other OpenGL controls, but now all of them work perfectly. I'm going to continue testing them.

Thanks a lot
