### ISSUE TITLE
Dock Panel demo not working under Mono

### ISSUE THREAD

**Issue by devmaestro1** [dockpanelsuite/dockpanelsuite#629]
Hi there,
I am trying to run the demo example but I get various crashes under Mono.
In the first instance, the application crashes shortly after the Splash screen. I commented out the "LoadFromXml" routines from MainForm and this allowed me to progress further.
Pressing various buttons after that, however, will cause the application to crash again.

Could someone please tell me how these can be fixed?

Thanks!

**Comment by lextm** [comment]
In general this repo no longer attempts to support Mono WinForms for various reasons. You might find other forks created patches for such.

Please consider a true cross platform approach instead, https://blog.lextudio.com/the-story-about-net-cross-platform-ui-frameworks-dd4a9433d0ea

**Comment by devmaestro1** [comment]
Thanks for the link of potential approaches but none of the solutions/SDKs really facilitate a docking environment like DockPanel. Unfortunately there are few real choices for those developing rich/dense desktop applications except Winforms & Mono (that is, without writing lots of extra platform-specific code).

I'm hoping someone can add to this thread if they know of a fork that attempts to address Mono-compatibility. I haven't been able to find one so far.
