### ISSUE TITLE
Can't add controls to dock panel

### ISSUE THREAD

**Issue by Shadowblitz16** [dockpanelsuite/dockpanelsuite#630]
I can't add controls to the dock panel making it useless
![image](https://user-images.githubusercontent.com/2453707/88443388-fb381300-cdcc-11ea-9d58-e69b2701b3fb.png)

**Comment by lextm** [comment]
You are supposed to create dock contents (a type of child forms) and add controls to them. Dock panels are simply logic containers, so it never supports drag controls into itself,

http://docs.dockpanelsuite.com/getting-started/installing-on-windows.html

**Comment by Shadowblitz16** [comment]
@lextm wait so this has no design time features?

**Comment by lextm** [comment]
Commercial docking libraries might have their design time support, but this project does not.

**Comment by Shadowblitz16** [comment]
@lextm your link is broken

**Comment by lextm** [comment]
The doc site was down for a few hours. Now it is back.
