### ISSUE TITLE
please allow us to drag and drop things in at design time

### ISSUE THREAD

**Issue by Shadowblitz16** [dockpanelsuite/dockpanelsuite#631]
Please allow us to drag and drop things in at design time.
All the links to the docs are dead and I feel allowing us to drag and drop controls into the dock panel should be supported

**Comment by lextm** [comment]
You might evaluate commercial libraries from certain vendors to feel how the design time support might look like.

Personally I don't think that helps too much to build an application, but you might have a different view.

Pull requests are welcome, but the current maintainers might not have enough time to work on this. (Actually this project has been idle for quite a while now.)

**Comment by Shadowblitz16** [comment]
thats too bad :(
