### ISSUE TITLE
Simple Examples?

### ISSUE THREAD

**Issue by fourofspades** [dockpanelsuite/dockpanelsuite#633]
The tutorial leaves a huge amount to be desired, and the sample code attempts to demonstrate every available feature (which is nice if you want to work out how to do advanced stuff).  There is a MASSIVE gap for someone just trying to create a very simpleMDI form with a couple of dockable panels,

Has someone done a simple example?

When I say a simple example, no themes, no dynamic adding of panels, basically as little code as possible to create a Form with 3 panels, a bottom, a right and a main panel that fills the remaining window, where all the panels can be moved and re-parented.

**Comment by tznind** [comment]
```csharp
        public Form1()
        {
            InitializeComponent();

            this.IsMdiContainer = true;

            var panel1 = new DockPanel();
            panel1.Dock = DockStyle.Fill;
            Controls.Add(panel1);

            var tab1 = new DockContent();
            tab1.TabText = "My left pane";
            tab1.Show(panel1,DockState.DockLeft);
                        
            var tab2 = new DockContent();
            tab2.TabText = "My mid pane";
            tab2.Show(panel1,DockState.Document);
        }
```

![image](https://user-images.githubusercontent.com/31306100/92724341-5795c880-f362-11ea-8219-647dc14a6acc.png)

**Comment by CarlosEX** [comment]
Hi guys, suppose I've added a number of child controls to the tab1 and tab2 panel, what would be the approach to accessing this child elements (textbox etc...). grateful
