### ISSUE TITLE
Tab content is invisible if DocumentStyle is DockingMdi on Mono/Linux

### ISSUE THREAD

**Issue by ATAT2005** [dockpanelsuite/dockpanelsuite#643]
Hi!

First of all, I'd like to thank you all for this brilliant library! It's supercool and very useful!

Unfortunately, I've encountered a problem. DocumentStyle of my app is DockingMdi, and it works perfectly fine on Windows with .Net Framework 4.6.1. But the content of every tab is invisible on Mono/Linux. The same behaviour is being reproduced in the sample project I've downloaded from GitHub. I made a small sample project for testing from GitHub project, I cut some themes, made a small adaptation for Visual Studio 2015 and MonoDevelop, etc., I've attached it to the post (startup project is DockSample too).

I'v tried to made some changes in the setter of ActiveContent property in the DockPane.cs file, I've added these lines:
```
if (m_activeContent != null)
{
	m_activeContent.DockHandler.SetVisible();
	m_activeContent.DockHandler.Activate();
}
```
after the lines:
```
if (m_activeContent != null)
         m_activeContent.DockHandler.Form.BringToFront();
```
But it didn't help at all. Moreover, when I look at the content variables in the setter of this property at the breakpoint while debugging, everything seems to be good: active content is a Form with a RichTextBox control, they are both visible and so on.
![watches](https://user-images.githubusercontent.com/25947544/103345405-21b45580-4ab3-11eb-9fd2-4d33e94eb10d.png)

But in fact all the tabs are empty. Could you please help me? Maybe there's some kind of a workaround? Maybe I should to try to make active content visible later, in some other method or property?

Thank you!

## Steps to Reproduce

Compile and run the following solution with Mono on Linux, then press "New" menu item from the "File" in main menu:
[TestVS2015.zip](https://github.com/dockpanelsuite/dockpanelsuite/files/5753862/TestVS2015.zip)

### Current Behavior
Every tab has no visible contents:
![dockLinBad](https://user-images.githubusercontent.com/25947544/103344029-3bec3480-4aaf-11eb-9bb2-405d5f4b7972.gif)

### Expected Behavior
The same project is working good on Windows 10 with .Net Framework 4.6.1, all the tabs have visible contents.
![dockWinGood](https://user-images.githubusercontent.com/25947544/103344043-473f6000-4aaf-11eb-8086-096a559caa89.gif)

## I noticed it on the platform:
Linux (Debian 10.7)

**Version Used**:
Mono: 6.10.0.104
MonoDevelop: 7.8.4

**Comment by lextm** [comment]
No plan to support Mono any more.
