### ISSUE TITLE
How to prevent ToolDockContent auto-resize when I resize MainWindow?

### ISSUE THREAD

**Issue by mkornevich** [dockpanelsuite/dockpanelsuite#649]
Please answer for this question.

How to prevent **ToolDockContent** (Not center **DockContent**) auto-resize when I resize **MainWindow** where placed **dockPanel**?

Now:
![image](https://user-images.githubusercontent.com/16904774/108631766-8c16c000-747c-11eb-8fc9-873a154178a2.png)

I need:
![image](https://user-images.githubusercontent.com/16904774/108631853-0d6e5280-747d-11eb-87e2-15bc46106ccb.png)

How I might to achieve it?

**Comment by mkornevich** [comment]
Here is more info
Duplicate of 92#

**Comment by mkornevich** [comment]
Duplicate of #92

**Comment by mkornevich** [comment]
To perform it you need set (for example):

dockPanel.DockBottomPortion = 250;
dockPanel.DockLeftPortion = 250;
dockPanel.DockRightPortion = 250;
dockPanel.DockTopPortion = 250;

**Comment by SilverGreen93** [comment]
Hi! I have the same problem, the left and top panels do resize when window resize, but the bottom and right panels don't. I tried settings the Portion properties to fixes values, but it still resizes. I have the DockPanel docked in a Tool Strip Content Panel.
Any thoughts for making this panels NOT resize when windows resizes, except for the inner middle panel?
