### ISSUE TITLE
.NET 5+ Support?

### ISSUE THREAD

**Issue by joell29** [dockpanelsuite/dockpanelsuite#659]
Any plan to update this project to support .NET 5 and future releases of .NET Framework? 

I work for a company that heavily uses .NET Framework (currently 4.7.2 to be exact) & WinForms and I have been experimenting with making the switch to .NET 5 for us. I got our custom software converted & compiling on .NET 5 using the ".NET Upgrade Assistant" tool from Microsoft as well as some manual labor on my part. The problem is, is if I open a form that implements WeifenLuo.WinFormsUI.Docking.DockContent I get a runtime error of "System.TypeLoadException: 'Could not load type 'System.Windows.Forms.ContextMenu' from assembly 'System.Windows.Forms, Version=5.0.6.0,..." 

This is basically what our native .NET Framework project had from several places where we had used the depreciated "ContextMenu" and "MenuItem" instead of "ContextMenuStrip" and "ToolStripMenuItem". See [Microsoft Blog](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1/) in the "Windows Forms Controls Removal" section. Correcting them to use the supported controls was a breeze and I had it done in a matter of minutes and our project was able to compile. I obviously though can't fix this for the DockPanelSuite - NuGet package our project depends on...

This seems at a glance from a high-level where i'm standing currently that this is something I can correct rather easily myself with this repo's given source code but not sure what road blocks I will hit if i dig deeper. And even if I will have enough understanding to correct them. Would love to see this natively supported by you guys, the official DockPanelSuite project. :) 

Thanks! Hope to hear back!

**Comment by lextm** [comment]
Have you checked 3.1.0 beta? https://www.nuget.org/packages/DockPanelSuite/3.1.0-beta7

**Comment by joell29** [comment]
Thanks it worked! Had to update the Theme as well to this.
https://www.nuget.org/packages/DockPanelSuite.ThemeVS2015/3.1.0-beta7

I was hoping for some much needed speed ups by switching from .NET Framework 4.7.2 to .NET 5 but sadly doesn't look to be any. Probably will wait till .NET 6 is out and maybe by then this will also be marked as stable as my boss doesn't like using beta software and I don't feel like fighting this fight with him lol.

**Comment by lextm** [comment]
The beta release has been published for a very long time, so I do plan to re-publish it as a stable release later this year.

**Comment by loicmorvan-ansys** [comment]
Do you plan to publish it as a stable release soon?

**Comment by lextm** [comment]
Release 3.1.0 is out.
