### ISSUE TITLE
Child Form MenuStrip Not Showing

### ISSUE THREAD

**Issue by kOchirasu** [dockpanelsuite/dockpanelsuite#660]
I updated to the `3.1.0-beta7` (for .NET5 compatibility) and am having problems with the MenuStrip being updated when a child form is active. Both MainForm and ChildForm have a MenuStrip field. My program starts out with only the MainForm and MainForm's MenuStrip is showing, but it doesn't get switched to the ChildForm's after adding it. Previously, after adding the ChildForm, the MenuStrip would show for the ChildForm instead of the MainForm.

Example:
```csharp
// MainForm menu showing
var childForm = new ChildForm();
childForm.Show(mainFormDockPanel, DockState.Document);
// Expect ChildForm menu showing
```

**Comment by lextm** [comment]
What is ".net5 beta7"? You also need to provide a minimal sample project to reproduce the issue.

**Comment by kOchirasu** [comment]
.NET 4.8
![image](https://user-images.githubusercontent.com/7710340/124365568-cf88f400-dbfd-11eb-95b3-d90fa537bbea.png)

.NET 5
![image](https://user-images.githubusercontent.com/7710340/124365583-f21b0d00-dbfd-11eb-9aec-51e20d65d1c7.png)

Source Code:
[DockPanelSuite-MenuStripBug.zip](https://github.com/dockpanelsuite/dockpanelsuite/files/6758980/DockPanelSuite-MenuStripBug.zip)

**Comment by kOchirasu** [comment]
Looked into this a bit more and it seems like the problem is that in `3.1.0-beta7`, `ChildForm.MdiParent == null` after adding it to the dockPanel. Instead it should be `MainForm` which seems to result in the menu strips being merged.

**Comment by kOchirasu** [comment]
Figured it out, the default value for `DockPanel.DocumentStyle` was changed to `DocumentStyle.DockingWindow`. Previously it was `DocumentStyle.DockingMdi`. Setting this properly fixes the problem.
