### ISSUE TITLE
Get an extra color from .vstheme

### ISSUE THREAD

**Issue by Vanguger** [dockpanelsuite/dockpanelsuite#661]
How to get an extra color from the theme?
For example, **MainWindowButtonActiveBorder** from vstheme? Please show an example.

`control.BackColor = CurrentTheme.ColorPalette.MainWindowButtonActiveBorder.Background;` ???

**Comment by lextm** [comment]
No. That's not a support feature. At this moment, you have to parse the theme file on your own (reuse whatever code needed) and then extract the color you want.
