### ISSUE TITLE
Tabs are not visible anymore since v3.1

### ISSUE THREAD

**Issue by MscrmTools** [dockpanelsuite/dockpanelsuite#664]
Hi,

Thank you very much for this project that I'm using in my own project.

I tried latest version and I can't see tabs anymore (see screenshots below)

With version 3.0.6
![image](https://user-images.githubusercontent.com/10774317/132835402-143949a2-4794-4ded-8422-f93d82f8d05f.png)

With version 3.1
![image](https://user-images.githubusercontent.com/10774317/132835322-cc857715-afc2-4f37-8e0c-1aa1e2d6d689.png)

Is there anything I should do to make it works like before?

**Comment by MscrmTools** [comment]
They are not visible because they are behind the toolbar... So I guess the rendering is not well calculated since I did not change anything on my side.
the dock panel component is Docked as Fill and the statusbar docked as Top

**Comment by cuppm** [comment]
I get this sometimes with forms.  Go into the designer and find where the toolstrip and the dockpanel are added to the form's controls.  Then flip their order.

**Comment by lextm** [comment]
This is a generic WinForms issue, which you can reproduce with default menu strip and panel. Close it now as @cuppm provides the solution.
