### ISSUE TITLE
Menu merging broken in 3.1

### ISSUE THREAD

**Issue by spreeves** [dockpanelsuite/dockpanelsuite#669]
I recently updated to 3.1.0 and I found that menus in MDI child forms no longer merge in to the MDI parent menu, I reverted to 3.0.6 and the menus merge correctly. I haven't got time to download and look at the source to try to see what's changed - apologies! I'm sticking with 3.0.6 for now as there don't appear to be any issues with my application using that version.

**Comment by lextm** [comment]
Duplicate to #613 . Please change the docking style.
