### ISSUE TITLE
DockPanel showing content not working unless setting a theme

### ISSUE THREAD

**Issue by woutware** [dockpanelsuite/dockpanelsuite#670]
I just upgraded from the old weifenluo docking to the current, but it seems it doesn't work out of the box anymore. You MUST set a theme, otherwise you'll get the following exception from the DockContentHandler:

> System.ArgumentException
>   HResult=0x80070057
>   Message=DockPanel.Theme must be set to a valid theme.
>   Source=WeifenLuo.WinFormsUI.Docking
>   StackTrace:
>    at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel, DockState dockState)
>    at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel)
>    at WeifenLuo.WinFormsUI.Docking.DockContent.Show(DockPanel dockPanel)
> 

So I spent 2 hours googling how to set just a theme. Ended up installing a theme package (DockPanelSuite.ThemeVS2015) and using this theme:

`this.dockPanel.Theme = new WeifenLuo.WinFormsUI.Docking.VS2015LightTheme();`

It would be great if there was just a default theme so it would work out of the box and people don't waste 2 hours of their life googling how to fix this.

I did try to look at the documentation on how to the theming works after I got the exception, but the documentation page doesn't even show a basic example for how to set a theme like above. See this documentation page: [https://docs.dockpanelsuite.com/themes/basics.html](https://docs.dockpanelsuite.com/themes/basics.html).

**Comment by lextm** [comment]
Thanks for providing feedback.

Moving VS2005 theme out in its own NuGet package saves all users of this library more than 100KB. The change is recorded in 3.1 release notes, https://github.com/dockpanelsuite/dockpanelsuite/releases/tag/Release_3.1.0

The article to tell how to use existing themes is https://docs.dockpanelsuite.com/themes/existing-themes.html, not the one you linked to.

There is also a sample project in https://github.com/dockpanelsuite/dockpanelsuite/tree/master/DockSample for your reference.

**Comment by woutware** [comment]
Yes, setting a theme is not too difficult, but why doesn't it use a default basic theme that doesn't throw an exception to begin with? The ThemeBase that is the default will cause an exception.

I mean, all the examples here won't work, because the examples don't set a theme either: [https://docs.dockpanelsuite.com/tutorials/basics.html](https://docs.dockpanelsuite.com/tutorials/basics.html).

**Comment by woutware** [comment]
Also about the theming documentation pages, I guess what threw me off there were the titles. "Theming Basics" suggested to me that I would find how to just choose one of the pre-made themes and just set them, so I was confused, I wanted to find what was in topic "Existing themes". But instead it's a topic on how to create your own theme. Maybe retitle it "Creating your own theme". And the other topic retitle it something like "Using provided theme implementations", although "Existing themes" isn't terrible.
