### ISSUE TITLE
Use dockpanelsuite's border in float windows

### ISSUE THREAD

**Issue by krulci** [dockpanelsuite/dockpanelsuite#678]
https://docs.dockpanelsuite.com/tutorials/customizing-floatwindow.html
The above post explained on how to customize float window to have maximize buttom on the title bar.
Is their any posibility to hide the winforms defaul title bar and use dockpanelsuite's caption bar instead in float windows
I can simply hide the default title bar by setting `FormBorderStyle = FormBorderStyle.None;` 
However, the windows become undraggable and I can't find how to set dockpanelsuite's caption bar to show

**Comment by krulci** [comment]
Modifiying the dll HASCaption() does allow the caption bar to appear when nested panel is less than or equal to 1
However, simply setting FormBorderStyle = FormBorderStyle.None; leads to an unwanted excess white area at the right and bottom of the form.

**Comment by krulci** [comment]
Is it possible to make FormBorderStyle = FormBorderStyle.None sizable?

**Comment by lextm** [comment]
The mystery around `FormBorderStyle.None` is a generic WinForms nightmare for decades, so I don't expect this library be able to help much.
