### ISSUE TITLE
Dockpanelsuite won't display icon

### ISSUE THREAD

**Issue by krulci** [dockpanelsuite/dockpanelsuite#685]
My project is a console app.
I start dockpanelsuite by doing Application.Run()
This is a net 6 project
I have already setup icon through Properties>Application>Win32 Resources>Icon
The console windows does display my icon
However, the winform windows (dockpanelsuite window) does not display the setup icon.
As shown in the image, winform windows only show default icon
The one on the left is the console; the one on the right is the dockpanel suite window
![image](https://user-images.githubusercontent.com/52474054/188550315-7c3ae372-5376-473a-aa83-5b7bd45b14e2.png)

**Comment by lextm** [comment]
Tha main form of a WinForms app won't pick up icon from `Properties>Application>Win32 Resources>Icon` but the `Icon` property of its own `Form` object.

Has nothing to do with DPS.
