### ISSUE TITLE
  I don't know how to activate the old tab

### ISSUE THREAD

**Issue by yelangtangtang** [dockpanelsuite/dockpanelsuite#687]
In the example, create a new tab, and then the new tab can write text, but the old tab cannot be written
![image](https://user-images.githubusercontent.com/114210737/191899415-2d68f6e5-9943-4845-ad2b-a0eb14af9caa.png)
![image](https://user-images.githubusercontent.com/114210737/191899469-a4974221-16c1-4cb0-8983-f9d260c1e599.png)

Click the button three times

![image](https://user-images.githubusercontent.com/114210737/191899613-764358e2-ef43-4000-ae4e-4a4bee935cd9.png)
The first tab does not write anything
![image](https://user-images.githubusercontent.com/114210737/191899697-5487d98e-ca2b-4386-b48c-d424baef2fff.png)
The second tab is written three times
![image](https://user-images.githubusercontent.com/114210737/191899777-bcd4db03-6067-47ca-811a-e34d90eca330.png)

**Comment by lextm** [comment]
The sample only shows how to use DPS for layout. About how to properly implement other business logic such as multiple document editing, you should refer to more general WinForms programming guides.
