### ISSUE TITLE
how to hide close button?

### ISSUE THREAD

**Issue by GanZhiXiong** [dockpanelsuite/dockpanelsuite#688]
![image](https://user-images.githubusercontent.com/27394631/196852438-e45e9d35-e554-4432-8ec4-9eeaed14e657.png)

How to hide this close button of `VS2015Theme` theme?
The answer given in related issues is to make your own theme, so how to make a theme?
Can you give the corresponding code or question.

https://github.com/dockpanelsuite/dockpanelsuite/issues/464
https://github.com/dockpanelsuite/dockpanelsuite/issues/356

**Comment by GanZhiXiong** [comment]
The theme I use is `dockPanel.Theme = new VS2015LightTheme();`

**Comment by lextm** [comment]
duplicate to #356

**Comment by lextm** [comment]
About how to create new themes, the official documentation already covers the start, https://docs.dockpanelsuite.com/themes/creating-new-theme.html

Try to  read enough before posting duplicate questions.
