### ISSUE TITLE
DockPanel Presence of margins

### ISSUE THREAD

**Issue by oper1000** [dockpanelsuite/dockpanelsuite#692]
DockPanel Presence of margins

![image](https://user-images.githubusercontent.com/993995/225329257-862a0096-0193-4bc9-8d31-c1e90dccd7a9.png)

**Comment by lextm** [comment]
This repo only ensures the sample project to display properly in as many scenarios as possible, but not your any trial project. Please compile/run that sample project in the source code and see if it works properly.

Windows Forms has a sharp learning curve on how to proper place controls in a form and adapt to different resolutions. That's out of this project's scope.
