### ISSUE TITLE
Problem with Menu's

### ISSUE THREAD

**Issue by Sirais** [dockpanelsuite/dockpanelsuite#694]
I recently updated from VS205 Theme to VS 2015 Them, and i dont know what happened. Now the Menus of the Child window dont merge anymore with the Menu from the Main Window. im open to any Hint in the right direction.
Thanks a lot.

**Comment by lextm** [comment]
If you have also updated DPS NuGet package to latest, read the release notes and check out the breaking changes.

**Comment by Sirais** [comment]
Thanks a lot for answering, even if you dont maintain this rocking project anymore.
Today i found out what happened. i also updated from 30.6 to 3.1 and in 3.1 the default Documentstyle changed from **DockingMDI** to **DockingWindow**. after changing it back to Mdi it works well again.
So the Problem wasnt the theme, but the DPS Update.

can be closed
