### ISSUE TITLE
Please help me to run and apply this framework in my project

### ISSUE THREAD

**Issue by AronJake** [dockpanelsuite/dockpanelsuite#698]
I can't run the docSample, I want to start to impelement this framework to have my project form docking system.

**Comment by roken** [comment]
What happens when you try to run the sample? Do you see error messages in the build? Does it run but throw exceptions?  More detail and/or screenshots are needed for anyone to assist.

**Comment by AronJake** [comment]
@roken, Thanks for the comment. I already figure out the problem, I'm using .net 8 before. and I installed .net 4.0, reading the documentations is a big help and plenty of research.
