### ISSUE TITLE
Configuration file authorship clarification

### ISSUE THREAD

**Issue by glopesdev** [dockpanelsuite/dockpanelsuite#708]
I noticed when saving the dock panel layout to an XML file that the `Persistor` outputs a few comments at the top:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!--DockPanel configuration file. Author: Weifen Luo, all rights reserved.-->
<!--!!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!!-->
```

What does it mean for this library's author to be the "author" of all saved configuration files? This seems like a very strange assertion, especially when followed by the sentence "all rights reserved". Makes it seem like the author is asserting ownership over all saved user configuration data, which can send the wrong message to the user and create confusion.

I think it's fine to link the format to the `DockPanelSuite` library, but the following text should be revised to remove authorship assertions, in my opinion.

https://github.com/dockpanelsuite/dockpanelsuite/blob/577d5b8b85b27c0bcb48c885fed56eba31ed3bcc/WinFormsUI/Docking/Strings.resx#L328

**Comment by lextm** [comment]
The file wasn't meant for human consumption, so for decades you’re the first to report this as an issue.

You might create a pull request to delete that statement from the string if you like.

**Comment by glopesdev** [comment]
@lextm thanks for the feedback. I think this issue will mostly come up when embedding configuration in other existing XML documents. With that in mind, I just submitted a PR which resolves this issue in a fully backwards compatible way by adding a new overload to `SaveAsXml` accepting an existing `XmlWriter` instance.

In all situations where users want to customize their own XML document declaration, etc, this overload would be used.
