### ISSUE TITLE
.Show() does not 'reveal' autohide dock.

### ISSUE THREAD

**Issue by Lockszmith** [dockpanelsuite/dockpanelsuite#80]
I'm opening this issue after discussing it in detail on stackexchange: http://stackoverflow.com/questions/13843604/calling-up-dockpanel-suites-autohidden-dockcontent-programmatically

**Comment by lextm** [comment]
After analyzing the code, I think we should rather keep the behavior as it is.

We should not attempt to show a "auto hide" content simply via the `Show` method, as they should be hidden.

Also we already have a workaround there to simply set this content as `DockPanel.ActiveAutoHideContent`, then it would be less urgent to modify the code base.
